vividus-framework/vividus

vividus-tests/src/main/resources/story/integration/ExecutableSteps.story, vividus/src/main/java/org/vividus/bdd/steps/ExecutableSteps.java, vividus/src/test/java/org/vividus/bdd/steps/ExecutableStepsTests.java
Add step
```
When I execute steps while counter is $comparisonRule `$limit` with increment `$increment` starting from `$seed`:$stepsToExecute
```
=> Add step When I execute steps while counter is $comparisonRule `$limit` with increment `$increment` starting from `$seed`:$stepsToExecute

.travis.yml
https://docs.travis-ci.com/user/sonarcloud/#upcoming-improvements:
Future versions of this add-on will provide the following features:
- Support for external pull requests.
=> Disable SonarQube for PR-s

build.gradle, vividus-plugin-web-app/build.gradle, vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties, vividus-reporter/build.gradle, vividus-reporter/src/main/java/org/vividus/reporter/environment/EnvironmentConfigurer.java, vividus-reporter/src/test/java/org/vividus/reporter/environment/EnvironmentConfigurerTests.java, vividus-reporter/src/test/java/org/vividus/reporter/environment/PropertyCategoryTests.java, vividus/src/main/resources/properties/defaults/default.properties
=> Reorganize property categories of environment configurer

vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java, vividus/src/test/java/org/vividus/bdd/steps/BddVariableStepsTests.java
=> Simplify variable spelling in *.ftl to access one value parameter

vividus-tests/src/main/resources/properties/suite/integration/suite.properties
Travis CI image contains installed Chrome browser
=> [tests] Enable integration vividus-plugin-web-app tests in CI

vividus-plugin-web-app/src/main/java/org/vividus/ui/web/util/LocatorUtil.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/ScriptStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/util/LocatorUtilTests.java
=> Change the way normalize-space() works for text() to allow for searching in multiple text nodes

vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/HttpRequestSteps.java, vividus-plugin-web-app-to-rest-api/src/main/resources/org/vividus/bdd/steps/integration/browser-cookies.ftl, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/HttpRequestStepsTests.java
Header has its own background since it's sticky as we scroll down
=> Add publishing of cookies received from browser

vividus-plugin-rest-api/src/main/java/org/vividus/http/HttpRequestExecutor.java, vividus-plugin-rest-api/src/main/resources/spring.xml
=> [plugin-rest-api] Add back lost HTTP request attachment to report

vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpResponseValidationSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/HttpResponseValidationStepsTests.java
=> Add step Then size of decompressed response body is comparisonRule sizeInBytes

vividus-http-client/src/test/java/org/vividus/http/HttpRequestBuilderTests.java, vividus/src/test/java/org/vividus/bdd/issue/KnownIssueProviderTests.java
https://rules.sonarsource.com/java/RSPEC-1943
=> Replace Charset.defaultCharset() with StandardCharsets.UTF_8

vividus-plugin-visual/src/main/java/org/vividus/visual/engine/FileSystemBaselineRepository.java, vividus-plugin-visual/src/main/resources/spring.xml, vividus-plugin-visual/src/test/java/org/vividus/visual/engine/FileSystemBaselineRepositoryTests.java
=> Make baselines folder resolving lazy and cached

vividus-plugin-web-app/build.gradle
java.lang.NoSuchMethodError: io.appium.java_client.AppiumDriver.setElementConverter(Lorg/openqa/selenium/remote/internal/JsonToWebElementConverter;)V by using selenium 4.0.0-alpha-3
=> Downgrade selenium version to 4.0.0-alpha-1

vividus-plugin-web-app-to-rest-api/src/main/resources/org/vividus/bdd/steps/integration/browser-cookies.ftl
=> Fix cookie template to handle empty expire date

vividus-allure-adaptor/build.gradle, vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureRunContext.java, vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/adapter/VerificationErrorAdapter.java, vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/listener/AllureAssertionFailureListener.java, vividus-allure-adaptor/src/main/resources/org/vividus/bdd/report/allure/spring.xml, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/AllureRunContextTests.java
https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-setter-injection
=> [allure-adaptor] Use constructor-based dependency injection only

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/DragAndDropSteps.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/DragAndDropStepsTests.java, vividus-tests/src/main/resources/story/integration/DragAndDropSteps.story
Fixes #209.
Apply workaround mentioned in https://github.com/SeleniumHQ/selenium/issues/1365#issuecomment-547786925
=> [plugin-web-app] Use workaround for drag-and-drop action

vividus-plugin-web-app/src/main/java/org/vividus/bdd/converter/StringToListSequenceActionConverter.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/ActionSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/model/SequenceAction.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/model/SequenceActionType.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/converter/StringToListSequenceActionConverterTests.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/ActionStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/model/SequenceActionTypeTests.java
=> Add step When I execute sequence of actions: actions

vividus-plugin-db/src/main/java/org/vividus/bdd/steps/db/DatabaseSteps.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java, vividus-plugin-rest-api/src/main/java/org/vividus/http/HttpRequestExecutor.java, vividus-plugin-rest-api/src/test/java/org/vividus/http/HttpRequestExecutorTests.java, vividus-util/src/main/java/org/vividus/util/wait/Waiter.java, vividus-util/src/test/java/org/vividus/util/wait/WaiterTests.java
Stop condition for waiter is easier to read and more natural for humans rather than repeat condition.
=> [util] Use stop condition instead of repeat condition in Waiter

vividus-bdd-engine/src/main/java/org/vividus/bdd/expression/DelegatingExpressionProcessor.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/expression/StringsExpressionProcessor.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/ExpressionAdapterTests.java, vividus-plugin-datetime/src/main/java/org/vividus/bdd/expression/EpochExpressionProcessors.java, vividus-plugin-datetime/src/main/java/org/vividus/util/DateUtils.java, vividus-plugin-datetime/src/main/resources/spring.xml, vividus-plugin-datetime/src/test/java/org/vividus/bdd/expression/EpochExpressionProcessorsTests.java, vividus-tests/src/main/resources/story/integration/Expressions.story
- toEpochSecond(date) - converts specified date in ISO_DATE_TIME to epoch seconds
- fromEpochSecond(seconds) - converts specified seconds to ISO_DATE_TIME date
=> [vividus-plugin-datetime] Add expressions to work with epoch time

vividus-util/src/main/java/org/vividus/util/UriUtils.java, vividus-util/src/test/java/org/vividus/util/UriUtilsTests.java
=> [util] Percent-encode square brackets in URL query and URL fragment

vividus-bdd-engine/src/main/java/org/vividus/bdd/context/BddRunContext.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/context/IBddRunContext.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/variable/VariablesFactory.java, vividus-bdd-engine/src/main/resources/org/vividus/bdd/spring.xml, vividus-bdd-engine/src/test/java/org/vividus/bdd/context/BddRunContextTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/variable/VariablesFactoryTests.java, vividus-tests/src/main/resources/properties/environment/integration/envinroment.properties, vividus-tests/src/main/resources/story/integration/VariableTests.story
=> Add ability to make global variables specific to batches

vividus-util/src/main/java/org/vividus/util/UriUtils.java, vividus-util/src/test/java/org/vividus/util/UriUtilsTests.java
=> [util] Do not decoded percent-encoded hash sign in URLs

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/PageSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/SetVariableSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/selenium/manager/WebDriverManager.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/WaitActions.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/WindowsActions.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/listener/WindowSwitchListener.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/PageStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/SetVariableStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/manager/WebDriverManagerTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/WaitActionsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/WindowsActionsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/listener/WindowSwitchListenerTest.java
https://github.com/appium/appium/issues/6825
=> [plugin-web-app] Remove workaround for closed iOS-specific Appium bug

vividus-bdd-engine/src/main/java/org/vividus/bdd/resource/ResourceLoadConfiguration.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/variable/VariablesFactory.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/resource/ResourceLoadConfigurationTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/variable/VariablesFactoryTests.java, vividus-http-client/src/main/resources/org/vividus/http/client/spring.xml, vividus-plugin-rest-api/src/main/resources/spring.xml, vividus-plugin-web-app/src/main/java/org/vividus/selenium/WebDriverFactory.java, vividus-plugin-web-app/src/main/resources/spring.xml, vividus-util/src/main/java/org/vividus/util/property/IPropertyParser.java, vividus-util/src/main/java/org/vividus/util/property/PropertyParser.java, vividus-util/src/test/java/org/vividus/util/property/PropertyParserTests.java
=> Replace old mechanism getPropertyValuesByFamily(String) with getPropertyValuesByPrefix(String) in o.v.u.p.IPropertyParser

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/PageSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/ScrollDirection.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/ScrollSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/IJavascriptActions.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/JavascriptActions.java, vividus-plugin-web-app/src/main/resources/spring.xml, vividus-plugin-web-app/src/main/resources/steps/defaults/scroll.steps, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/PageStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/ScrollStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/JavascriptActionsTests.java, vividus-tests/src/main/resources/story/integration/ScrollStepsTests.story
=> Add ability to scroll context element horizontally

vividus-soft-assert/src/main/java/org/vividus/softassert/issue/KnownIssueChecker.java, vividus-soft-assert/src/main/java/org/vividus/softassert/issue/KnownIssueDataProvider.java, vividus-soft-assert/src/main/java/org/vividus/softassert/issue/KnownIssueIdentifier.java, vividus-soft-assert/src/main/resources/org/vividus/softassert/spring.xml, vividus-soft-assert/src/test/java/org/vividus/softassert/issue/KnownIssueCheckerTests.java, vividus-tests/src/main/resources/known-issues.json, vividus-tests/src/main/resources/story/integration/KnownIssues.story, vividus/src/main/java/org/vividus/bdd/issue/BddKnownIssueIdentifier.java, vividus/src/main/java/org/vividus/bdd/issue/DelegatingKnownIssueDataProvider.java, vividus/src/main/java/org/vividus/bdd/issue/KnownIssueCheckerBeanPostProcessor.java, vividus/src/main/resources/org/vividus/spring-vividus.xml, vividus/src/test/java/org/vividus/bdd/issue/DelegatingKnownIssueDataProviderTests.java, vividus/src/test/java/org/vividus/bdd/issue/KnownIssueCheckerBeanPostProcessorTests.java, vividus/src/test/java/org/vividus/bdd/issue/KnownIssueProviderTests.java
=> Add ability to filter known issues by BDD variables

vividus-bdd-engine/src/main/java/org/vividus/bdd/converter/SubStepsConverter.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/parser/StepExamplesTableParser.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/spring/ExtendedConfiguration.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/JoiningTableTransformer.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/MergingTableTransformer.java, vividus-bdd-engine/src/main/resources/org/vividus/bdd/spring.xml, vividus-bdd-engine/src/test/java/org/vividus/bdd/BatchedEmbedderTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/converter/SubStepsConverterTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/parser/StepExamplesTableParserTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/spring/ExtendedConfigurationTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/transformer/JoiningTableTransformerTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/transformer/MergingTableTransformerTests.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/ProxyAgentStoryReporter.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/ProxyAgentStoryReporterTests.java, vividus/src/main/java/org/vividus/runner/BddStepsCounter.java, vividus/src/test/java/org/vividus/runner/BddStepsCounterTests.java, vividus/src/test/resources/org/vividus/bdd/test-spring.xml
to avoid early initialization of configuration
=> Use org.jbehave.core.configuration.Configuration as a base 

vividus-plugin-rest-api/src/main/java/org/vividus/bdd/diff/JsonDiffMatcher.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/JsonResponseValidationStepsTests.java, vividus-plugin-rest-api/src/test/resources/org/vividus/bdd/steps/api/missmatches-actual-data.json, vividus-plugin-rest-api/src/test/resources/org/vividus/bdd/steps/api/missmatches-expected-data.json, vividus-tests/src/main/resources/known-issues.json, vividus-tests/src/main/resources/story/integration/KnownIssues.story
=> [plugin-rest-api] Separate assertions related to different json nodes

vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ComparisonRule.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/ComparisonRuleTests.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/validation/BaseValidations.java
=> Return human-readable description by ComparisonRule.toString()

vividus-plugin-html/src/main/java/org/vividus/bdd/steps/html/HtmlSteps.java, vividus-plugin-html/src/main/resources/steps/defaults/composite.steps, vividus-plugin-html/src/test/java/org/vividus/bdd/steps/html/HtmlStepsTests.java, vividus-tests/src/main/resources/story/integration/HtmlSteps.story
=> Add step to validate elements number using comparison rule

vividus-plugin-web-app/src/main/java/org/vividus/selenium/IWebDriverFactory.java, vividus-plugin-web-app/src/main/java/org/vividus/selenium/VividusWebDriverFactory.java, vividus-plugin-web-app/src/main/java/org/vividus/selenium/WebDriverFactory.java, vividus-plugin-web-app/src/main/java/org/vividus/selenium/screenshot/AshotFactory.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/VividusWebDriverFactoryTests.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/WebDriverFactoryTests.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/screenshot/AshotFactoryTests.java
=> [plugin-web-app] Add possibility to set capabilities for local run

vividus-plugin-web-app/src/main/java/org/vividus/selenium/WebDriverType.java, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/edge/chromium/profile.properties, vividus-plugin-web-app/src/test/java/org/vividus/selenium/WebDriverTypeTests.java
=> [plugin-web-app] Add Edge (Chromium) support

vividus-plugin-web-app/src/main/java/org/vividus/ui/web/configuration/WebApplicationConfiguration.java, vividus-plugin-web-app/src/main/resources/spring.xml, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/configuration/WebApplicationConfigurationTests.java
=> [plugin-web-app] Extract JavascriptActions to avoid circular dependency

vividus-bdd-engine/src/main/java/org/vividus/bdd/expression/StringsExpressionProcessor.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/expression/StringsExpressionProcessorTests.java, vividus-tests/src/main/resources/story/integration/Expressions.story
=> Add anyOf expression

build.gradle
Fixes #396 - JBehave 4.6.2-alpha.2 includes the fix allowing to use DOS/Windows line endings (\r\n) in composite steps files
=> Upgrade to JBehave 4.6.2-alpha.2

vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/HeadlessCrawlerTableTransformer.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/transformer/HeadlessCrawlerTableTransformerTests.java
=> [plugin-web-app-to-rest-api] Fix broken crawling when seed urls not set

vividus-bdd-engine/src/main/java/org/vividus/bdd/expression/StringsExpressionProcessor.java
Before change:
Investigation:
After change:
=> Cache Faker-s to avoid reloads of faker resources

vividus-tests/src/main/resources/story/system/MongodbStepsTests.story
=> Add example of how to compare data pulled from mongo with data pulled from relational db

vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/ResolvingExpressionsEagerlyTransformer.java, vividus-bdd-engine/src/main/resources/org/vividus/bdd/spring.xml, vividus-bdd-engine/src/test/java/org/vividus/bdd/transformer/ResolvingExpressionsEagerlyTransformerTests.java, vividus-tests/src/main/resources/data/with-eagerly-transformer.table, vividus-tests/src/main/resources/data/without-eagerly-transformer.table, vividus-tests/src/main/resources/story/integration/TableTransformers.story
=> Add RESOLVING_EXPRESSIONS_EAGERLY table transformer

vividus-plugin-web-app/src/main/java/org/vividus/selenium/manager/WebDriverManager.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/manager/WebDriverManagerTests.java
=> [vividus-plugin-web-app] Add an ability to open Chrome browser maximized

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/ActionSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/model/SequenceActionType.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/ActionStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/model/SequenceActionTypeTests.java, vividus-tests/src/main/resources/story/integration/ActionSteps.story
=> [plugin-web-app] Add MOVE_TO sequence action

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/ScrollSteps.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/ScrollStepsTests.java, vividus-tests/src/main/resources/story/integration/ScrollStepsTests.story
=> [plugin-web-app] Add step to scroll element into view

vividus-bdd-engine/src/main/java/org/vividus/bdd/spring/ExtendedConfiguration.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/ResolvingSelfReferencesEagerlyTransformer.java, vividus-bdd-engine/src/main/resources/org/vividus/bdd/spring.xml, vividus-bdd-engine/src/test/java/org/vividus/bdd/transformer/ResolvingSelfReferencesEagerlyTransformerTests.java, vividus-tests/src/main/resources/story/integration/TableTransformers.story
=> Add RESOLVING_SELF_REFERENCES_EAGERLY table transformer

vividus-plugin-rest-api/src/main/java/org/vividus/http/CookieStoreLevel.java, vividus-plugin-rest-api/src/main/java/org/vividus/http/CookieStoreLevelEditor.java, vividus-plugin-rest-api/src/main/java/org/vividus/http/CookieStoreProvider.java, vividus-plugin-rest-api/src/main/resources/properties/defaults/run.properties, vividus-plugin-rest-api/src/main/resources/spring.xml, vividus-plugin-rest-api/src/test/java/org/vividus/http/CookieStoreLevelEditorTests.java, vividus-plugin-rest-api/src/test/java/org/vividus/http/CookieStoreProviderTests.java, vividus-tests/src/main/resources/properties/suite/integration/suite.properties, vividus-tests/src/main/resources/story/integration/HttpRequest.story
=> [plugin-rest-api] Add ability to define cookie store level

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/WaitSteps.java
=> Add javadoc for step 'Then alert does not appear in '$timeout''

vividus-allure-adaptor/build.gradle, vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureReportGenerator.java, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/adapter/AllureReportGeneratorTests.java, vividus-util/src/main/java/org/vividus/util/property/IPropertyMapper.java, vividus-util/src/main/java/org/vividus/util/property/PropertyMapper.java, vividus-util/src/main/resources/org/vividus/util/spring.xml, vividus-util/src/test/java/org/vividus/util/property/PropertyMapperTests.java, vividus/src/main/resources/org/vividus/spring-configuration.xml
=> Add Executor info to Allure report

vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/AllureStoryReporterTests.java
Single given story may be used several times in different base stories, as result history ids were generated exactly the same and given stories were treated as retries. This change uses full stories execution chain as a part of history key.
Relates #406
=> [allure-adaptor] Use full stories execution chain in history key

vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/AllureStoryReporterTests.java
=> [allure-adaptor] Add index to history key for scenarios with same title

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/PageSteps.java, vividus-plugin-web-app/src/main/resources/steps/defaults/page.steps, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/PageStepsTests.java, vividus-tests/src/main/resources/story/integration/PageStepsTests.story
=> [plugin-web-app] Use locator for scroll validation

vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/ExtendedTableTransformer.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/RepeatingTableTranformer.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/transformer/RepeatingTableTranformerTests.java, vividus-tests/src/main/resources/story/integration/TableTransformers.story
=> Add REPEATING table transformer

vividus-plugin-datetime/src/main/java/org/vividus/bdd/expression/DiffDateExpressionProcessor.java, vividus-plugin-datetime/src/test/java/org/vividus/bdd/expression/DiffDateExpressionProcessorTests.java, vividus-tests/src/main/resources/story/integration/Expressions.story
=> [plugin-datetime] Add ability to define date diff output format

vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/FilteringTableTransformer.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/transformer/FilteringTableTransformerTests.java, vividus-tests/src/main/resources/story/integration/TableTransformers.story
=> [bdd-engine] Add ability to filter rows by regex in FILTERING transformer

vividus-plugin-datetime/src/main/java/org/vividus/bdd/expression/DiffDateExpressionProcessor.java, vividus-plugin-datetime/src/test/java/org/vividus/bdd/expression/DiffDateExpressionProcessorTests.java
=> [plugin-date-time] Extend returned diff types to all ChronoUnits

vividus-bdd-engine/src/main/java/org/vividus/bdd/expression/RoundExpressionProcessor.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/expression/RoundExpressionProcessorTests.java, vividus-tests/src/main/resources/story/integration/RoundExpressionProcessor.story
=> Add rounding modes

vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/JsonResponseValidationStepsTests.java
=> [plugin-rest-api] Fix to recognize empty array difference

vividus-bdd-engine/src/main/java/org/vividus/bdd/BatchedEmbedder.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/batch/BatchExecutionConfiguration.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/batch/BatchStorage.java, vividus-bdd-engine/src/main/resources/org/vividus/bdd/spring.xml, vividus-bdd-engine/src/test/java/org/vividus/bdd/BatchedEmbedderTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/batch/BatchStorageTests.java
=> [bdd-engine] Allow to set ignore failure per batch

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/CookieSteps.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/CookieStepsTests.java
=> [plugin-web-app] Fix NPE when cookies is set without navigation to the page

vividus-plugin-rest-api/src/main/resources/org/vividus/http/attachment/api-message.ftl, vividus-tests/src/main/resources/story/integration/RestApiStepsTests.story
=> [vividus-plugin-rest-api] Update Allure HTTP messages attachment template (#587)

vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/search/AbstractElementSearchAction.java, vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties, vividus-plugin-web-app/src/main/resources/spring.xml, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/search/ElementSearchActionTests.java
=> [vividus-plugin-web-app] Add WebElement research if element is stale

vividus-bdd-engine/src/main/java/org/vividus/bdd/context/BddVariableContext.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/context/BddVariableContextTests.java, vividus-tests/src/main/resources/story/integration/VariableTests.story
=> [bdd-engine] Fix variables with comma and default value processing

vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureReportGenerator.java, vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/model/AllureCategory.java, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/adapter/AllureReportGeneratorTests.java
=> Add known issues into categories in Allure report

vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpCookieSteps.java, vividus-plugin-rest-api/src/main/resources/spring.xml, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/HttpCookieStepsTests.java, vividus-tests/src/main/resources/story/integration/HttpCookieSteps.story
=> [vividus-plugin-rest-api] Add step to save cookie as variable

vividus-bdd-engine/src/main/java/org/vividus/bdd/converter/ComparisonRuleParameterConverter.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/converter/FluentTrimmedEnumConverter.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/converter/FluentTrimmedEnumConverterTests.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/converter/FluentEnumListConverter.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/converter/FluentEnumListConverterTests.java, vividus-tests/src/main/resources/story/integration/HttpRequest.story
=> Adding custom ENUM converter to trim spaces

vividus-http-client/src/main/java/org/vividus/http/HttpMethod.java, vividus-http-client/src/test/java/org/vividus/http/HttpMethodTests.java, vividus-http-client/src/test/java/org/vividus/http/HttpRequestBuilderTests.java, vividus-plugin-rest-api/src/main/java/org/vividus/http/HttpClientInterceptor.java, vividus-plugin-rest-api/src/test/java/org/vividus/http/HttpClientInterceptorTests.java, vividus-plugin-rest-api/src/test/java/org/vividus/http/HttpRequestExecutorTests.java, vividus-tests/src/main/resources/story/integration/HTTP.story
=> Add ability to execute HTTP POST requests without body

vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpCookieSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/HttpCookieStepsTests.java, vividus-tests/src/main/resources/story/integration/HttpCookieSteps.story
=> [plugin-rest-api] Add step to change cookie value

vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ParameterConvertersDecorator.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/ParameterConvertersDecoratorTests.java, vividus-tests/src/main/resources/story/integration/VariableTests.story
=> [bdd-engine] Resolve nested expressions/placeholders

vividus-bdd-engine/src/main/java/org/vividus/bdd/expression/EvalExpressionProcessor.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/expression/EvalExpressionProcessorTests.java, vividus-tests/src/main/resources/story/integration/Expressions.story
=> [bdd-engine] Allow resolution of context variables in eval expression

docs/modules/parameters/nav.adoc, docs/modules/parameters/pages/collection-comparison-rule.adoc, docs/modules/plugins/nav.adoc, docs/modules/plugins/pages/plugin-rest-api.adoc, vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/CollectionComparisonRule.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/CollectionComparisonRuleTests.java, vividus-http-client/src/main/java/org/vividus/http/client/ISslContextFactory.java, vividus-http-client/src/main/java/org/vividus/http/client/SslContextFactory.java, vividus-http-client/src/test/java/org/vividus/http/client/SslContextFactoryTests.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/ssl/SslSteps.java, vividus-plugin-rest-api/src/main/resources/spring.xml, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/ssl/SslStepsTests.java, vividus-plugin-rest-api/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, vividus-tests/src/main/resources/story/integration/SslSteps.story
=> Add step to check secure protocols supported by server

vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ParameterConvertersDecorator.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/ParameterConvertersDecoratorTests.java, vividus-tests/src/main/resources/story/integration/VariableTests.story
=> [bdd-engine] Fix placeholders resolving in empty ExamplesTable

vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/search/AbstractElementSearchAction.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/search/ButtonNameSearchTests.java, vividus-tests/src/main/resources/story/integration/ElementSearchTests.story
=> Exclude parent elements from caseInsensitiveText search

vividus-plugin-web-app/build.gradle
=> Remove standalone littleproxy dependency

docs/modules/ROOT/pages/tests-configuration.adoc
=> [docs] Document known issues

docs/modules/ROOT/pages/tests-configuration.adoc, vividus-soft-assert/src/main/java/org/vividus/softassert/issue/KnownIssueChecker.java, vividus-soft-assert/src/main/resources/org/vividus/softassert/spring.xml, vividus-soft-assert/src/test/java/org/vividus/softassert/issue/KnownIssueCheckerTests.java, vividus/src/main/resources/properties/defaults/default.properties
=> [soft-assert] Add possibility to disable potentially known issues

vividus-bdd-engine/src/main/java/org/vividus/bdd/batch/BatchStorage.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/variable/VariablesFactory.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/batch/BatchStorageTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/variable/VariablesFactoryTests.java, vividus-plugin-db/src/main/java/org/vividus/bdd/steps/db/DatabaseSteps.java, vividus-plugin-db/src/test/java/org/vividus/bdd/steps/db/DatabaseStepsTests.java, vividus-plugin-email/src/main/java/org/vividus/bdd/email/steps/EmailSteps.java, vividus-plugin-email/src/test/java/org/vividus/bdd/email/steps/EmailStepsTests.java, vividus-plugin-ssh/src/main/java/org/vividus/bdd/steps/ssh/SshSteps.java, vividus-plugin-ssh/src/test/java/org/vividus/bdd/steps/ssh/SshStepsTests.java, vividus-plugin-web-app/src/main/java/org/vividus/selenium/screenshot/ScreenshotTaker.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/screenshot/ScreenshotTakerTests.java, vividus-reporter/src/main/java/org/vividus/reporter/environment/EnvironmentConfigurer.java, vividus-reporter/src/test/java/org/vividus/reporter/environment/EnvironmentConfigurerTests.java, vividus-util/src/main/java/org/vividus/util/property/IPropertyMapper.java, vividus-util/src/main/java/org/vividus/util/property/PropertyMappedCollection.java, vividus-util/src/main/java/org/vividus/util/property/PropertyMapper.java, vividus-util/src/test/java/org/vividus/util/property/PropertyMappedCollectionTests.java, vividus-util/src/test/java/org/vividus/util/property/PropertyMapperTests.java
=> Improve error messages for missing configuration items

vividus-bdd-engine/src/main/java/org/vividus/bdd/batch/BatchStorage.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/variable/VariablesFactory.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/batch/BatchExecutionConfigurationTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/batch/BatchStorageTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/variable/VariablesFactoryTests.java, vividus-util/src/main/java/org/vividus/util/property/IPropertyMapper.java, vividus-util/src/main/java/org/vividus/util/property/PropertyMapper.java, vividus-util/src/test/java/org/vividus/util/property/PropertyMapperTests.java
Add PropertyMapper API:
- to change keys while collecting objects
- to sort collected objects by key
=> Expand PropertyMapper API

vividus-plugin-db/src/main/java/org/vividus/bdd/steps/db/DatabaseSteps.java, vividus-plugin-db/src/test/java/org/vividus/bdd/steps/db/DatabaseStepsTests.java, vividus-tests/src/main/resources/story/system/DatabaseStepsTests.story
=> [vividus-plugin-db] hash method is independent of key set order

vividus-soft-assert/src/test/java/org/vividus/softassert/model/KnownIssueTests.java, vividus-soft-assert/src/test/java/org/vividus/softassert/model/SoftAssertionErrorTests.java
Added unit tests for KnownIssueTests.java, SoftAssertionErrorTests.java
=> Add unit tests to org.vividus.softassert

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/CheckboxSteps.java, vividus-plugin-web-app/src/main/resources/steps/defaults/checkbox.steps, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/CheckboxStepsTests.java, vividus-tests/src/main/resources/story/integration/CheckboxStepsTests.story
=> [plugin-web-app] Use locators for checkbox steps

vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpCookieSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/HttpCookieStepsTests.java
=> [plugin-rest-api] Fix filtering of cookies by root path

docs/modules/ROOT/pages/index.adoc
In the current implementation, the page named untitled
=> [docs] Add title for an index page

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/ActionSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/model/SequenceActionType.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/model/SequenceActionTypeTests.java, vividus-tests/src/main/resources/story/integration/ActionSteps.story
=> [plugin-web-app] Add keys combination pressing functionality

docs/modules/plugins/pages/plugin-rest-api.adoc, vividus-plugin-db/src/main/java/org/vividus/bdd/steps/db/DatabaseSteps.java, vividus-plugin-email/src/main/java/org/vividus/bdd/email/service/ImapFetchService.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java, vividus-plugin-rest-api/src/main/java/org/vividus/http/HttpRequestExecutor.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/JsonResponseValidationStepsTests.java, vividus-util/src/main/java/org/vividus/util/wait/DurationBasedWaiter.java, vividus-util/src/main/java/org/vividus/util/wait/RetryTimesBasedWaiter.java, vividus-util/src/main/java/org/vividus/util/wait/Waiter.java, vividus-util/src/test/java/org/vividus/util/wait/DurationBasedWaiterTests.java, vividus-util/src/test/java/org/vividus/util/wait/RetryTimesBasedWaiterTests.java
…erval  retrying retryTimes times stepsToExecute
=> Add new step for waiting for presence of element by JSON path using polling interval

docs/modules/plugins/pages/plugin-rest-api.adoc, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java, vividus-plugin-rest-api/src/main/java/org/vividus/http/HttpTestContext.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/HttpRequestStepsTests.java, vividus-plugin-rest-api/src/test/java/org/vividus/http/HttpTestContextTests.java, vividus-tests/src/main/resources/story/integration/HTTP.story
=> Fixed 'Step to add single HTTP header to request #881'

docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/transformer/FetchingUrlsTableTransformerTests.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/PageSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/configuration/WebApplicationConfiguration.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/PageStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/configuration/WebApplicationConfigurationTests.java
=> [web-app] Throw user-friendly error when missing main application page URL is used

vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/validation/BaseValidations.java, vividus-extension-selenium/src/test/java/org/vividus/bdd/steps/ui/validation/BaseValidationsTests.java
=> [extension-selenium] Do not wait for elements in assert element number verifications

vividus-plugin-rest-api/src/main/java/org/vividus/bdd/transformer/JsonRestApiTableTransformer.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/transformer/JsonRestApiTableTransformerTests.java
https://github.com/google/guava/issues/1900
=> [plugin-rest-api] Fix handling of '=' sign in FROM_JSON transformer

vividus-allure-adaptor/build.gradle, vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureReportGenerator.java, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/adapter/AllureReportGeneratorTests.java
=> [allure-adaptor] Add test configuration info to report

vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/AbstractFilteringTableTransformer.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/DistinctingTableTransformer.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/FilteringTableTransformer.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/util/ExamplesTableProcessor.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/transformer/DistinctingTableTransformerTests.java, vividus-tests/src/main/resources/story/integration/TableTransformers.story
=> Add DISTINCTING table transformer

gradle.properties
https://docs.gradle.org/6.7/release-notes.html#file-system-watching
=> [Gradle] Enable file-system watching

docs/modules/plugins/pages/plugin-aws-s3.adoc, vividus-plugin-aws-s3/src/main/java/org/vividus/aws/s3/steps/S3BucketSteps.java, vividus-plugin-aws-s3/src/test/java/org/vividus/aws/s3/steps/S3BucketStepsTests.java
=> [plugin-aws-s3] Add step to download S3 object

vividus-plugin-saucelabs/src/main/resources/spring.xml
This is a workaround for the `saucerest-java` library issue. 
The actual fix is https://github.com/saucelabs/saucerest-java/pull/127
=> [plugin-saucelabs] Make SauceLabs DataCenter property case-insensitive

vividus-plugin-saucelabs/src/main/java/org/vividus/selenium/sauce/SauceConnectOptions.java, vividus-plugin-saucelabs/src/test/java/org/vividus/selenium/sauce/SauceConnectOptionsTests.java
=> [plugin-saucelabs] Trim SauceLabs REST API URL

vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/safari/profile.properties
=> Bump MacOS version from 10.13(High Sierra) to 10.14(Mojave)

vividus-bdd-engine/src/main/java/org/vividus/bdd/RunContextStoryReporter.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/model/RunningStory.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/RunContextStoryReporterTests.java, vividus-soft-assert/src/main/java/org/vividus/softassert/issue/KnownIssueChecker.java, vividus-soft-assert/src/main/java/org/vividus/softassert/issue/TestInfo.java, vividus-soft-assert/src/test/java/org/vividus/softassert/issue/KnownIssueCheckerTests.java, vividus-tests/src/main/resources/known-issues.json, vividus-tests/src/main/resources/steps/defaults/field.steps, vividus-tests/src/main/resources/story/integration/KnownIssues.story, vividus/src/main/java/org/vividus/bdd/issue/TestInfoProvider.java, vividus/src/test/java/org/vividus/bdd/issue/TestInfoProviderTests.java
=> Add ability to use composite steps in known-issues

vividus-tests/src/main/resources/properties/environment/integration/envinroment.properties
=> [tests] Make Path variable reference platform independent

vividus-plugin-web-app/src/main/java/org/vividus/selenium/VividusWebDriverFactory.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/VividusWebDriverFactoryTests.java
The browser is resized in `BrowserWindowSizeListener`:
https://github.com/vividus-framework/vividus/blob/9b681cfc4952f73022d6638cd79e99bbae9c3ca6/vividus-plugin-web-app/src/main/java/org/vividus/selenium/BrowserWindowSizeListener.java#L30-L34
=> [plugin-web-app] Avoid duplicate browser resizing

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/bdd/converter/HttpMethodSetConverter.java, vividus-plugin-web-app/src/main/java/org/vividus/proxy/steps/ProxySteps.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/converter/HttpMethodSetConverterTests.java, vividus-plugin-web-app/src/test/java/org/vividus/proxy/steps/ProxyStepsTests.java, vividus-tests/src/main/resources/story/integration/ProxyStepsTests.story
=> [plugin-web-app] Add ability to use set of HTTP methods in proxy steps

docs/modules/plugins/partials/generic-ui-steps.adoc, vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/GenericElementSteps.java, vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/model/StringSortingOrder.java, vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/validation/BaseValidations.java, vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/validation/IBaseValidations.java, vividus-extension-selenium/src/test/java/org/vividus/bdd/steps/ui/GenericElementStepsTests.java, vividus-extension-selenium/src/test/java/org/vividus/bdd/steps/ui/model/StringSortingOrderTests.java, vividus-extension-selenium/src/test/java/org/vividus/bdd/steps/ui/validation/BaseValidationsTests.java, vividus-tests/src/main/resources/story/integration/ElementStepsTests.story
=> [extension-selenium] Add ability to verify elements order

docs/modules/plugins/pages/plugin-rest-api.adoc, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/model/RequestPartType.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/model/RequestPartTypeTests.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/HttpRequestStepsTests.java, vividus-tests/src/main/resources/data/file.txt, vividus-tests/src/main/resources/story/integration/HTTP.story
=> [plugin-rest-api] Add ability to create multipart request with dynamic content

build.gradle
=> Bump JBehave from 4.8.0-alpha.5 to 4.8.0-alpha.6

vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureRunContext.java, vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java, vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/IAllureRunContext.java, vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/model/ScenarioExecutionStage.java, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/AllureRunContextTests.java, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/AllureStoryReporterTests.java
=> [allure-adaptor] Handle log messages produced between scenario steps

docs/modules/plugins/pages/plugin-rest-api.adoc, vividus-http-client/src/main/java/org/vividus/http/client/ConfigurableServiceUnavailableRetryStrategy.java, vividus-http-client/src/main/java/org/vividus/http/client/HttpClientConfig.java, vividus-http-client/src/main/java/org/vividus/http/client/HttpClientFactory.java, vividus-http-client/src/main/resources/org/vividus/http/client/spring.xml, vividus-http-client/src/main/resources/properties/defaults/run.properties, vividus-http-client/src/test/java/org/vividus/http/client/ConfigurableServiceUnavailableRetryStrategyTests.java, vividus-http-client/src/test/java/org/vividus/http/client/HttpClientFactoryTests.java, vividus-tests/src/main/resources/properties/environment/integration/envinroment.properties, vividus-tests/src/main/resources/story/integration/HTTP.story
Partially addresses https://github.com/vividus-framework/vividus/issues/214#issuecomment-725953128
=> [http-client] Support HTTP retry on service unavailability

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/SetContextSteps.java
=> [plugin-web-app] Fix NoUniqueBeanDefinitionException at steps instance creation

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-extension-selenium/src/main/java/org/vividus/proxy/Proxy.java, vividus-extension-selenium/src/main/java/org/vividus/proxy/ProxyFactory.java, vividus-extension-selenium/src/main/resources/properties/defaults/default.properties, vividus-extension-selenium/src/main/resources/spring.xml, vividus-extension-selenium/src/test/java/org/vividus/proxy/ProxyFactoryTests.java, vividus-extension-selenium/src/test/java/org/vividus/proxy/ProxyTests.java
=> [plugin-web-app] Add possibility to override browser's proxy host

build.gradle, vividus-tests/src/main/resources/steps/defaults/steps-for-integration-tests.steps, vividus-tests/src/main/resources/story/integration/VariableTests.story, vividus/src/main/java/org/vividus/bdd/converter/ExamplesTableToListOfMapsConverter.java, vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java, vividus/src/test/java/org/vividus/bdd/converter/ExamplesTableToListOfMapsConverterTests.java, vividus/src/test/java/org/vividus/bdd/steps/BddVariableStepsTests.java
=> [vividus] Pass ExamplesTable parameter as list of maps

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/proxy/steps/ProxySteps.java, vividus-plugin-web-app/src/test/java/org/vividus/proxy/steps/ProxyStepsTests.java, vividus-tests/src/main/resources/story/integration/ProxyStepsTests.story
=> [plugin-web-app] Add step to clear proxy mocks

vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ParameterAdaptor.java, vividus-bdd-engine/src/main/resources/org/vividus/bdd/spring.xml, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/ParameterAdaptorTests.java, vividus-tests/src/main/resources/story/integration/VariableTests.story
=> [bdd-engine] Resolve variables as part of names of another variables

docs/modules/plugins/pages/plugin-aws-s3.adoc, vividus-plugin-aws-s3/build.gradle, vividus-plugin-aws-s3/src/main/java/org/vividus/aws/s3/steps/S3BucketSteps.java, vividus-plugin-aws-s3/src/main/java/org/vividus/bdd/converter/CannedAccessControlListConverter.java, vividus-plugin-aws-s3/src/test/java/org/vividus/aws/s3/steps/S3BucketStepsTests.java, vividus-plugin-aws-s3/src/test/java/org/vividus/bdd/converter/CannedAccessControlListConverterTests.java, vividus-tests/build.gradle, vividus-tests/gradle.properties, vividus-tests/src/main/resources/story/system/AWS - S3.story
=> [plugin-aws-s3] Add step to set S3 object canned ACL

vividus-extension-selenium/src/main/java/org/vividus/selenium/AbstractVividusWebDriverFactory.java, vividus-extension-selenium/src/test/java/org/vividus/selenium/VividusWebDriverFactoryTests.java, vividus-plugin-web-app/src/main/java/org/vividus/selenium/WebDriverFactory.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/WebDriverFactoryTests.java
=> [plugin-web-app] Do not set acceptInsecureCerts for Safari and IE

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-bdd-engine/src/main/java/org/vividus/bdd/variable/Variables.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/variable/VariablesTests.java, vividus-plugin-web-app/src/main/java/org/vividus/proxy/steps/ProxySteps.java, vividus-plugin-web-app/src/test/java/org/vividus/proxy/steps/ProxyStepsTests.java, vividus-tests/src/main/resources/story/integration/ProxyStepsTests.story
=> [plugin-web-app] Allow duplicate URL query and form data parameters

vividus-plugin-web-app/src/main/resources/properties/profile/web/phone/android/v6_0/browser/landscape/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/phone/android/v6_0/browser/portrait/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/phone/android/v6_0/browser/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/phone/android/v6_0/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/phone/android/v7_0/chrome/landscape/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/phone/android/v7_0/chrome/portrait/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/phone/android/v7_0/chrome/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/phone/android/v7_0/profile.properties
=> [vividus-plugin-web-app] Remove Android 6 and 7 profiles

vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/GenericSetVariableSteps.java, vividus-extension-selenium/src/test/java/org/vividus/bdd/steps/ui/GenericSetVariableStepsTests.java, vividus-tests/src/main/resources/story/integration/SearchAttributes.story
Closes https://github.com/vividus-framework/vividus/issues/1032
=> [extension-selenium] Delete forcing visibility all for save attribute step

docs/modules/ROOT/pages/tests-configuration.adoc, vividus/src/main/resources/properties/defaults/default.properties
=> [vividus] Remove default configuration for batch-1

build.gradle, gradlew, gradlew.bat
=> Rename BUILD_SYSTEM_ROOT -> VIVIDUS_BUILD_SYSTEM_HOME

.github/workflows/gradle.yml, docs/modules/ROOT/pages/tests-configuration.adoc, vividus-tests/src/main/resources/properties/configuration.properties, vividus-tests/src/main/resources/properties/suite/additional/suite.properties, vividus-tests/src/main/resources/story/integration/additional/AdditionalSuiteStory.story, vividus/src/integrationTest/java/org/vividus/configuration/BeanFactoryIntegrationTests.java, vividus/src/integrationTest/resources/properties/configuration.properties, vividus/src/integrationTest/resources/properties/suite/additionalsuite/props/suite.properties, vividus/src/integrationTest/resources/properties/suite/additionalsuite/suite.properties, vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java, vividus/src/main/resources/properties/defaults/default.properties, vividus/src/main/resources/properties/deprecated/deprecated.properties, vividus/src/test/resources/properties/configuration.properties
- configuration.suites - new property used to set one or more suites separated by comma
- configuration.suite - property is deprecated
=> [vividus] Add multisuite support

vividus/src/integrationTest/java/org/vividus/configuration/BeanFactoryIntegrationTests.java, vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java
=> Fix bug with overriding properties on different levels

vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/VariableResolver.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/VariableResolverTests.java, vividus-tests/src/main/resources/story/integration/VariableTests.story
=> [bdd-engine] Fix resolving of same nested variables within single value

vividus-plugin-saucelabs/src/main/java/org/vividus/selenium/sauce/SauceConnectOptions.java, vividus-plugin-saucelabs/src/test/java/org/vividus/selenium/sauce/SauceConnectOptionsTests.java
https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy+Setup+with+Additional+Proxies#SauceConnectProxySetupwithAdditionalProxies-SettingUpSauceConnectProxywithThirdPartyProxies
=> [plugin-saucelabs] Do not use proxy to connect SL REST API by SauceConnect

vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ExpressionAdaptor.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/ExpressionAdapterTests.java, vividus-tests/src/main/resources/story/integration/Expressions.story
=> [bdd-engine] Process non-string expressions joined with string constants

docs/modules/plugins/pages/plugin-excel.adoc, vividus-plugin-excel/src/main/java/org/vividus/bdd/steps/ExcelFileSteps.java, vividus-plugin-excel/src/main/java/org/vividus/excel/ExcelSheetWriter.java, vividus-plugin-excel/src/main/resources/spring.xml, vividus-plugin-excel/src/test/java/org/vividus/bdd/steps/ExcelFileStepsTests.java, vividus-plugin-excel/src/test/java/org/vividus/excel/ExcelSheetWriterTests.java, vividus-tests/src/main/resources/story/integration/ExcelSteps.story
Supersedes #1190 
Closes #1028
=> [excel-plugin] Add step for creating of temporary excel file

docs/modules/plugins/pages/plugin-mobile-app.adoc, docs/modules/plugins/pages/plugin-web-app.adoc, docs/modules/plugins/partials/dynamic-variables-header.adoc, vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/VariableResolver.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/variable/RunningScenarioNameDynamicVariable.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/variable/RunningStoryNameDynamicVariable.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/VariableResolverTests.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/variable/ResponseCodeDynamicVariable.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/variable/ui/web/CurrentPageUrlDynamicVariable.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/variable/ui/web/PageSourceDynamicVariable.java, vividus-tests/src/main/resources/story/integration/HTTP.story
=> [bdd-engine] Support dynamic vars in lower camel and lower hyphen cases

vividus-plugin-aws-s3/src/main/java/org/vividus/aws/s3/steps/S3BucketSteps.java
https://bugs.openjdk.java.net/browse/JDK-8020619
=> [plugin-aws-s3] Do not use self-closing tags

vividus-extension-selenium/src/test/java/org/vividus/bdd/steps/ui/validation/BaseValidationsTests.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/validator/ResourceValidatorTests.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/CodeStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/ElementStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/NestedStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/screenshot/AdjustingViewportPastingDecoratorTests.java, vividus/src/test/java/org/vividus/bdd/transformer/ResolvingExpressionsEagerlyTransformerTests.java
SQ rule: https://sonarcloud.io/organizations/vividus/rules?open=java%3AS6068&rule_key=java%3AS6068
=> Clean up: simplify Mockito argument matching

docs/modules/integrations/pages/xray-exporter.adoc, vividus-to-xray-exporter/src/main/java/org/vividus/xray/configuration/XrayExporterOptions.java, vividus-to-xray-exporter/src/main/java/org/vividus/xray/exporter/XrayExporter.java, vividus-to-xray-exporter/src/main/java/org/vividus/xray/facade/XrayFacade.java, vividus-to-xray-exporter/src/main/java/org/vividus/xray/model/AddOperationRequest.java, vividus-to-xray-exporter/src/test/java/org/vividus/xray/exporter/XrayExporterTests.java, vividus-to-xray-exporter/src/test/java/org/vividus/xray/facade/XrayFacadeTests.java
=> [xray-exporter] Add ability to link test cases to test set

vividus-to-xray-exporter/src/main/java/org/vividus/xray/configuration/XrayExporterOptions.java, vividus-to-xray-exporter/src/main/java/org/vividus/xray/exporter/XrayExporter.java, vividus-to-xray-exporter/src/test/java/org/vividus/xray/exporter/XrayExporterTests.java
https://github.com/spring-projects/spring-boot/issues/21868
=> [xray-exporter] Delete usage of optional type in configuration

docs/modules/integrations/pages/xray-exporter.adoc, vividus-to-xray-exporter/src/main/java/org/vividus/xray/exporter/XrayExporter.java, vividus-to-xray-exporter/src/main/java/org/vividus/xray/facade/XrayFacade.java, vividus-to-xray-exporter/src/main/java/org/vividus/xray/factory/TestExecutionFactory.java, vividus-to-xray-exporter/src/main/java/org/vividus/xray/model/TestExecution.java, vividus-to-xray-exporter/src/main/java/org/vividus/xray/model/TestExecutionItem.java, vividus-to-xray-exporter/src/main/java/org/vividus/xray/model/TestExecutionItemStatus.java, vividus-to-xray-exporter/src/test/java/org/vividus/xray/exporter/XrayExporterTests.java, vividus-to-xray-exporter/src/test/java/org/vividus/xray/facade/XrayFacadeTests.java, vividus-to-xray-exporter/src/test/java/org/vividus/xray/factory/TestExecutionFactoryTests.java
Closes https://github.com/vividus-framework/vividus/issues/1390
=> [xray-exporter] Add statuses for test execution

vividus-bdd-engine/src/main/java/org/vividus/bdd/util/MapUtils.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/util/MapUtilsTests.java, vividus-tests/src/main/resources/story/integration/ProxyStepsTests.story, vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java, vividus/src/test/java/org/vividus/bdd/steps/BddVariableStepsTests.java
=> [vividus] Expand Lists with single element at comparison against table

vividus-bdd-engine/src/main/java/org/vividus/bdd/RunContextStoryReporter.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/converter/SubStepsConverter.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/model/RunningScenario.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/parser/IStepExamplesTableParser.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/parser/StepExamplesTableParser.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/RunContextStoryReporterTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/converter/SubStepsConverterTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/model/RunningScenarioTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/parser/StepExamplesTableParserTests.java, vividus-tests/src/main/resources/steps/defaults/steps-for-integration-tests.steps, vividus-tests/src/main/resources/story/integration/ExecutableStepsExamplesIntegration.story
=> [bdd-engine] Fix examples resolution for sub-steps

.github/workflows/gradle.yml, build.gradle, settings.gradle, vividus-docker-bundler/build.gradle
=> Add Docker bundler

.github/workflows/gradle.yml, vividus-docker-bundler/build.gradle
=> [CI] Push docker image to Docker Hub

vividus-bdd-engine/src/main/java/org/vividus/bdd/converter/SubStepsConverter.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/converter/SubStepsConverterTests.java, vividus-tests/src/main/resources/story/integration/LifecycleBeforeStorySubSteps.story
=> [bdd-engine] Use empty params for substep parsing if there is no running scenarios

docs/modules/ROOT/pages/tests-configuration.adoc
=> [docs] Document story prioritization feature

docs/modules/integrations/nav.adoc, docs/modules/integrations/pages/docker.adoc
=> [docs] Document Vividus Docker image

vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/GenericElementSteps.java, vividus-plugin-datetime/src/main/java/org/vividus/bdd/steps/DateValidationSteps.java, vividus-plugin-html/src/main/java/org/vividus/bdd/steps/html/HtmlSteps.java, vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpResponseValidationSteps.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/CodeSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/NestedSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/proxy/steps/ProxySteps.java, vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java, vividus/src/main/java/org/vividus/bdd/steps/ExecutableSteps.java
=> Update javadocs for comparison rule

docs/modules/ROOT/pages/tests-configuration.adoc, vividus-tests/src/main/resources/properties/suite/suite.properties, vividus/build.gradle, vividus/src/main/java/org/vividus/bdd/StatisticsStoryReporter.java, vividus/src/main/java/org/vividus/bdd/model/Failure.java, vividus/src/main/java/org/vividus/report/MetadataLogger.java, vividus/src/main/resources/org/vividus/spring-vividus.xml, vividus/src/main/resources/properties/defaults/default.properties, vividus/src/test/java/org/vividus/bdd/StatisticsStoryReporterTests.java, vividus/src/test/java/org/vividus/bdd/model/FailureTests.java, vividus/src/test/java/org/vividus/report/MetadataLoggerTests.java
=> [vividus] Add ability to print failures statistics after test execution

docs/modules/commons/pages/vividus-steps.adoc, vividus-tests/src/main/resources/known-issues.json, vividus-tests/src/main/resources/story/integration/DebugSteps.story, vividus/src/main/java/org/vividus/bdd/steps/DebugSteps.java, vividus/src/main/resources/org/vividus/spring-steps.xml, vividus/src/test/java/org/vividus/bdd/steps/DebugStepsTests.java
=> Add wait step for debug purposes

docs/modules/plugins/pages/plugin-aws-dynamodb.adoc, vividus-plugin-aws-dynamodb/build.gradle, vividus-plugin-aws-dynamodb/src/main/java/org/vividus/aws/dynamodb/steps/DynamoDbSteps.java, vividus-plugin-aws-dynamodb/src/main/resources/properties/defaults/default.properties, vividus-plugin-aws-dynamodb/src/main/resources/spring.xml, vividus-plugin-aws-dynamodb/src/test/java/org/vividus/aws/dynamodb/steps/DynamoDbStepsTests.java
=> [plugin-aws-dynamodb] Implement cross-account access via roles

vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/AllureStoryReporterTests.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/model/RunningStory.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/model/RunningStoryTests.java
=> [allure-adaptor] Fix reporting of scenarios with same name

docs/modules/commons/pages/vividus-steps.adoc, vividus-tests/src/main/resources/data/resolve-variables.ftl, vividus-tests/src/main/resources/properties/environment/integration/envinroment.properties, vividus-tests/src/main/resources/story/integration/VariableTests.story, vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java, vividus/src/test/java/org/vividus/bdd/steps/BddVariableStepsTests.java
=> [vividus] Add ability to use variables in templates

docs/modules/plugins/pages/plugin-kafka.adoc, vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java, vividus-plugin-kafka/src/main/resources/properties/deprecated/deprecated.properties, vividus-plugin-kafka/src/main/resources/steps/defaults/kafka.steps, vividus-plugin-kafka/src/test/java/org/vividus/bdd/steps/kafka/KafkaStepsIntegrationTests.java, vividus-plugin-kafka/src/test/java/org/vividus/bdd/steps/kafka/KafkaStepsTests.java
=> [plugin-kafka] Support multiple configurations

docs/modules/commons/pages/vividus-steps.adoc, vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ExpressionAdaptor.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ParameterConvertersDecorator.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/ExpressionAdapterTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/ParameterConvertersDecoratorTests.java, vividus-reporter/src/main/resources/org/vividus/reporter/spring.xml, vividus-tests/src/main/resources/data/expressions.ftl, vividus-tests/src/main/resources/story/integration/Expressions.story, vividus-util/src/main/java/org/vividus/util/freemarker/FreemarkerProcessor.java, vividus-util/src/main/resources/org/vividus/util/spring.xml, vividus-util/src/test/java/org/vividus/util/freemarker/FreemarkerProcessorTests.java, vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java, vividus/src/main/java/org/vividus/bdd/steps/FreemarkerSteps.java, vividus/src/main/java/org/vividus/bdd/transformer/ResolvingExpressionsEagerlyTransformer.java, vividus/src/main/resources/org/vividus/spring-steps.xml, vividus/src/test/java/org/vividus/bdd/steps/BddVariableStepsTests.java, vividus/src/test/java/org/vividus/bdd/steps/FreemarkerStepsTests.java, vividus/src/test/java/org/vividus/bdd/transformer/ResolvingExpressionsEagerlyTransformerTests.java, vividus/src/test/resources/org/vividus/bdd/steps/parameters.ftl, vividus/src/test/resources/org/vividus/bdd/steps/simple.ftl
=> [vividus] Add support for vividus expressions in templates

docs/modules/commons/pages/vividus-steps.adoc, vividus-tests/src/main/resources/properties/environment/integration/envinroment.properties, vividus/src/main/java/org/vividus/bdd/steps/FreemarkerSteps.java, vividus/src/main/resources/org/vividus/spring-steps.xml, vividus/src/main/resources/properties/defaults/default.properties, vividus/src/test/java/org/vividus/bdd/steps/FreemarkerStepsTests.java
=> [vividus] Make resolving of variable in templates optional

.github/workflows/gradle.yml, vividus-tests/build.gradle
=> [CI] Speed-up testing execution

vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/SubSteps.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/SubStepsTests.java
=> [bdd-engine] Fix invalid exceptions thrown from sub steps

docs/modules/plugins/pages/plugin-azure-storage-account.adoc, vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/DataWrapper.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ParameterConvertersDecorator.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/DataWrapperTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/ParameterConvertersDecoratorTests.java, vividus-plugin-azure-storage-account/src/main/java/org/vividus/azure/storage/blob/BlobStorageSteps.java, vividus-plugin-azure-storage-account/src/test/java/org/vividus/azure/storage/blob/BlobStorageStepsTests.java, vividus-plugin-web-app/src/main/java/org/vividus/proxy/steps/ProxySteps.java, vividus-plugin-web-app/src/test/java/org/vividus/proxy/steps/ProxyStepsTests.java
=> [plugin-azure-storage-account] Add ability to upload binary blobs

build.gradle
=> Bump JBehave from 5.0.0-alpha.9 to 5.0.0-alpha.10

docs/modules/plugins/pages/plugin-azure-storage-account.adoc, vividus-plugin-azure-storage-account/src/main/java/org/vividus/azure/storage/blob/BlobStorageSteps.java, vividus-plugin-azure-storage-account/src/test/java/org/vividus/azure/storage/blob/BlobStorageStepsTests.java, vividus-util/src/main/java/org/vividus/util/json/JsonUtils.java, vividus-util/src/test/java/org/vividus/util/json/JsonUtilsTests.java
=> [plugin-azure-storage-account] Add ability to retrieve blob properties

vividus/src/main/java/org/vividus/report/MetadataLogger.java
https://github.com/vdmeer/asciitable#text-alignment-1
=> [vividus] Avoid extra middle spaces in failures table

vividus-plugin-web-app/build.gradle
=> [plugin-web-app] Align versions of all netty dependencies

vividus-plugin-db/src/main/java/org/vividus/bdd/steps/db/DatabaseSteps.java
=> [plugin-db] Do not use self-closing tags

vividus/src/main/resources/log4j2.xml
Fixes regression issue caused by #1611
Relates #1593
=> [vividus] Restore logging of info assertion messages to allure report

vividus-agent-reportportal/src/main/resources/log4j2-vividus-reportportal-agent.xml, vividus/src/main/java/org/vividus/configuration/Vividus.java, vividus/src/main/java/org/vividus/runner/GenericRunner.java, vividus/src/test/java/org/vividus/configuration/VividusTests.java, vividus/src/test/java/org/vividus/runner/GenericRunnerTests.java
=> Report portal logs fix

vividus-agent-reportportal/build.gradle, vividus-agent-reportportal/src/main/java/org/vividus/reportportal/listener/AttachmentListener.java, vividus-agent-reportportal/src/main/resources/log4j2-vividus-reportportal-agent.xml, vividus-agent-reportportal/src/main/resources/spring.xml, vividus-agent-reportportal/src/test/java/org/vividus/reportportal/listener/AttachmentListenerTests.java
=> Attachments

docs/modules/commons/pages/expressions.adoc
=> [docs] Fix anchor links for expressions

docs/modules/ROOT/pages/tests-configuration.adoc, vividus-plugin-db/src/main/java/org/vividus/bdd/steps/db/DatabaseSteps.java, vividus-plugin-db/src/test/java/org/vividus/bdd/steps/db/DatabaseStepsTests.java, vividus-tests/src/main/resources/story/system/DatabaseStepsTests.story
=> Add ability to compare for `null` values in ExamplesTable

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/configuration/MobileApplicationConfiguration.java, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/model/SwipeDirection.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java, vividus-plugin-mobile-app/src/main/resources/properties/profile/mobile_app/profile.properties, vividus-plugin-mobile-app/src/main/resources/spring.xml, vividus-plugin-mobile-app/src/test/java/io/appium/java_client/TouchActionsTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/configuration/MobileApplicationConfigurationTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/model/SwipeDirectionTests.java
=> [plugin-mobile-app] Add ability to set vertical x position for swipe

.github/workflows/gradle.yml, docs/modules/plugins/partials/generic-ui-steps.adoc, vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/ScreenshotTakingSteps.java, vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/AbstractScreenshotTaker.java, vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/ScreenshotTakeEvent.java, vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/ScreenshotTaker.java, vividus-extension-selenium/src/main/resources/properties/defaults/default.properties, vividus-extension-selenium/src/main/resources/properties/deprecated/deprecated.properties, vividus-extension-selenium/src/main/resources/spring.xml, vividus-extension-selenium/src/main/resources/steps/defaults/screenshot.steps, vividus-extension-selenium/src/test/java/org/vividus/bdd/steps/ui/ScreenshotTakingStepsTests.java, vividus-extension-selenium/src/test/java/org/vividus/selenium/screenshot/AbstractScreenshotTakerTests.java, vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppScreenshotTaker.java, vividus-plugin-mobile-app/src/main/resources/spring.xml, vividus-plugin-mobile-app/src/test/java/org/vividus/selenium/mobileapp/MobileAppScreenshotTakerTests.java, vividus-plugin-web-app/src/main/java/org/vividus/selenium/screenshot/WebScreenshotTaker.java, vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties, vividus-plugin-web-app/src/main/resources/spring.xml, vividus-plugin-web-app/src/test/java/org/vividus/selenium/screenshot/WebScreenshotTakerTests.java, vividus-tests/src/main/resources/data/tables/mobile_app/start.table, vividus-tests/src/main/resources/data/tables/web/start.table, vividus-tests/src/main/resources/properties/configuration.properties, vividus-tests/src/main/resources/properties/environment/environment.properties, vividus-tests/src/main/resources/properties/environment/integration/envinroment.properties, vividus-tests/src/main/resources/properties/environment/system/saucelabs/mobile_app/environment.properties, vividus-tests/src/main/resources/properties/suite/ui/suite.properties, vividus-tests/src/main/resources/story/ui/ScreenshotTakingStepsTests.story
=> Take screenshots

vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java, vividus-plugin-mobile-app/src/test/java/io/appium/java_client/TouchActionsTests.java
=> [plugin-mobile-app] Add workaround to tap invisible elements using coordinates

vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/KeyboardActions.java, vividus-plugin-mobile-app/src/test/java/org/vividus/mobileapp/action/KeyboardActionsTests.java
Relates #1828
This PR fixes the issue from the ticket, but doesn't provide the ability to type text without keyboard hiding yet
=> [plugin-mobile-app] Apply keyboard dismissal workaround for both iOS real devices and simulators

vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/KeyboardActions.java, vividus-plugin-mobile-app/src/test/java/org/vividus/mobileapp/action/KeyboardActionsTests.java, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
=> [plugin-mobile-app] Skip keyboard dismissal on clearing of an empty field

docs/modules/commons/pages/table-transformers.adoc
=> [docs] Document usage of global variables in table transformers

docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc, vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java, vividus-plugin-html/src/test/java/org/vividus/util/HtmlUtilsTests.java, vividus-plugin-html/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java
=> [plugin-web-app-to-rest-api] Fix invalid relative url resolution in resource steps

vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java
=> [plugin-web-app-to-rest-api] Fix absent query parameters in resolved urls

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/configuration/MobileApplicationConfiguration.java, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/model/SwipeDirection.java, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/TouchSteps.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java, vividus-plugin-mobile-app/src/main/resources/properties/profile/mobile_app/profile.properties, vividus-plugin-mobile-app/src/main/resources/spring.xml, vividus-plugin-mobile-app/src/test/java/io/appium/java_client/TouchActionsTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/configuration/MobileApplicationConfigurationTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/model/SwipeDirectionTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/steps/TouchStepsTests.java, vividus-tests/src/main/resources/data/tables/system/mobile_app/locators/android.table, vividus-tests/src/main/resources/data/tables/system/mobile_app/locators/ios.table, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
=> [plugin-mobile-app] Add possibility to swipe in LEFT/RIGHT direction

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/KeyboardSteps.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/KeyboardActions.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/steps/KeyboardStepsTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/mobileapp/action/KeyboardActionsTests.java, vividus-tests/src/main/resources/data/tables/system/mobile_app/locators/android.table, vividus-tests/src/main/resources/data/tables/system/mobile_app/locators/ios.table, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
=> Mobile native apps add possibility not to hide keyboard after text input

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/KeyboardSteps.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/steps/KeyboardStepsTests.java, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
=> [plugin-mobile-app] Add possibility to fire long-press events on the keys for Android

vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java, vividus-plugin-mobile-app/src/test/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManagerTests.java
=> [plugin-native-app] Fix status bar calculation for android tv

vividus-plugin-rest-api/build.gradle
Fixes #2016
The root cause is: https://github.com/apache/tika/commit/6401ca084ac9409bf6b6c94b2fa4ff293e427133
=> [plugin-rest-api] Revert back to Tika 1

vividus-plugin-web-app/src/main/java/org/vividus/bdd/issue/CurrentPageUrlKnownIssueDataProvider.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/issue/CurrentPageUrlKnownIssueDataProviderTests.java, vividus-soft-assert/src/main/java/org/vividus/softassert/issue/IKnownIssueDataProvider.java, vividus-soft-assert/src/main/java/org/vividus/softassert/issue/KnownIssueIdentifier.java
=> Deprecate `dymanicPatterns` in known issues

docs/modules/commons/pages/vividus-steps.adoc, vividus/src/main/java/org/vividus/bdd/steps/FileSteps.java, vividus/src/main/resources/steps/defaults/temp-file.steps, vividus/src/test/java/org/vividus/bdd/steps/FileStepsTests.java
=> [vividus] Align wordings of file steps

vividus-tests/src/main/resources/story/integration/ExcelSteps.story
=> [tests] Enhance Excel steps validation to simplify issues triaging

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/resources/properties/profile/mobile_app/local/profile.properties, vividus-plugin-mobile-app/src/main/resources/properties/profile/mobile_app/tvos/profile.properties
=> Mobile app local profile

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/KeyboardSteps.java, vividus-plugin-mobile-app/src/main/resources/properties/profile/mobile_app/profile.properties, vividus-plugin-mobile-app/src/main/resources/spring.xml, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/steps/KeyboardStepsTests.java, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
=> [plugin-mobile-app] Add long press support for tvOS and iOS

docs/modules/commons/pages/vividus-steps.adoc, vividus-plugin-azure-storage-account/src/main/java/org/vividus/azure/storage/blob/BlobStorageSteps.java, vividus-tests/src/main/resources/story/integration/ExecutableSteps.story, vividus/src/main/java/org/vividus/bdd/steps/ExecutableSteps.java, vividus/src/test/java/org/vividus/bdd/steps/ExecutableStepsTests.java
Implement a new step executor with unconditional ExamplesTable run.
Closes #1800
=> [vividus] Create a new step executor for run ExamplesTable (#1800)

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/glossary.adoc, docs/modules/commons/pages/expressions.adoc, docs/modules/plugins/pages/plugin-rest-api.adoc, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/model/RequestPartType.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java, vividus-tests/src/main/resources/story/integration/HTTP.story, vividus-util/src/main/java/org/vividus/util/ResourceUtils.java, vividus-util/src/test/java/org/vividus/util/ResourceUtilsTests.java
=> [plugin-rest-api] Add ability to upload via HTTP file from file system

docs/modules/commons/pages/vividus-steps.adoc, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/WaitSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/selenium/TimeoutConfigurer.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/WaitStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/TimeoutConfigurerTests.java, vividus-tests/src/main/resources/story/integration/WaitStepsTests.story
Closes #2122
Implement ability to manually set the page load timeout in a stories.
=> [vividus-plugin-web-app] Add a feature to configure page load timeout

vividus-tests/src/main/resources/properties/environment/integration/envinroment.properties, vividus-tests/src/main/resources/story/integration/Encryption.story, vividus/src/main/java/org/vividus/configuration/PropertiesDecryptor.java, vividus/src/test/java/org/vividus/configuration/PropertiesDecryptorTests.java
=> [vividus] Possibility for use fragmented encryption in global variables

build.gradle, vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java, vividus-allure-adaptor/src/main/resources/org/vividus/bdd/report/allure/spring.xml, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/AllureStoryReporterTests.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/AbstractReportControlStoryReporter.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/ReportControlStoryReporter.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/RunContextStoryReporter.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/context/BddRunContext.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/context/ReportControlContext.java, vividus-bdd-engine/src/main/java/org/vividus/bdd/model/jbehave/AbstractStepsContainer.java, vividus-bdd-engine/src/main/resources/org/vividus/bdd/spring.xml, vividus-bdd-engine/src/test/java/org/vividus/bdd/AbstractReportControlStoryReporterTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/ReportControlStoryReporterTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/RunContextStoryReporterTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/context/BddRunContextTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/context/ReportControlContextTests.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/model/jbehave/StoryTests.java, vividus-extension-selenium/src/main/resources/spring.xml, vividus-to-azure-devops-exporter/src/test/resources/org/vividus/azure/devops/exporter/error/data.json, vividus-to-azure-devops-exporter/src/test/resources/org/vividus/azure/devops/exporter/export/data.json, vividus-to-xray-exporter/src/main/java/org/vividus/xray/factory/TestExecutionFactory.java, vividus-to-xray-exporter/src/test/java/org/vividus/xray/factory/TestExecutionFactoryTests.java, vividus/src/main/java/org/vividus/bdd/StatisticsStoryReporter.java, vividus/src/main/resources/org/vividus/spring-vividus.xml, vividus/src/test/java/org/vividus/bdd/StatisticsStoryReporterTests.java
=> Upgrade to jbehave 5.0.0-alpha.16

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/WaitSteps.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/WaitStepsTests.java
=> [plugin-web-app] Remove deprecated non-generic step checking existence of element by xpath for given duration

vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/edge/chromium/profile.properties
=> [plugin-web-app] Remove hardcoded version of Edge (Chromium) browser

docs/modules/commons/pages/expressions.adoc, vividus-tests/src/main/resources/story/integration/Expressions.story, vividus/src/main/java/org/vividus/bdd/expression/HashAlgorithmType.java, vividus/src/main/java/org/vividus/bdd/expression/HashExpressionProcessor.java, vividus/src/test/java/org/vividus/bdd/expression/HashExpressionProcessorTests.java
=> [vividus] Add expressions for hash calculation (#1647)

vividus-plugin-browserstack/src/main/resources/properties/profile/browserstack/web/profile.properties, vividus-plugin-lambdatest/src/main/resources/properties/profile/lambdatest/web/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/safari/profile.properties
=> [plugin-web-app] Bump default macOS version from Catalina to Big Sur

vividus-tests/src/main/resources/story/integration/Save filepath as next-batches variable.story, vividus/src/main/resources/steps/defaults/temp-file.steps
=> [vividus] Remove deprecated steps creating files

vividus-plugin-web-app-to-rest-api/src/main/resources/properties/defaults/default.properties, vividus-plugin-web-app-to-rest-api/src/main/resources/spring.xml
=> [plugin-web-app-to-rest-api] Drop support of deprecated property `http.redirects-provider.credentials`

.github/workflows/gradle.yml, vividus-plugin-web-app/src/main/java/org/vividus/selenium/WebDriverType.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/MouseActions.java, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/edge/chromium/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/edge/profile.properties, vividus-plugin-web-app/src/test/java/org/vividus/selenium/WebDriverTypeTests.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/manager/WebDriverManagerTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/MouseActionsTests.java
Selenium 4 doesn't support EdgeHTML: https://github.com/SeleniumHQ/selenium/issues/9166
=> [plugin-web-app] Drop support of EdgeHTML browser

docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc, vividus-tests/src/main/resources/properties/suite/integration/suite.properties, vividus-tests/src/main/resources/story/integration/Databases.story
=> [docs] Adding the guide on database initialization from tests (#2273)

build.gradle, vividus-tests/src/main/resources/story/integration/ExamplesTable.story
=> Upgrade to JBehave 5.0.0-alpha.17

docs/modules/plugins/partials/generic-ui-steps.adoc, vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/AbstractScreenshotTaker.java, vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/ScreenshotTaker.java, vividus-extension-selenium/src/main/java/org/vividus/steps/ui/ScreenshotTakingSteps.java, vividus-extension-selenium/src/main/resources/properties/defaults/default.properties, vividus-extension-selenium/src/main/resources/spring.xml, vividus-extension-selenium/src/test/java/org/vividus/selenium/screenshot/AbstractScreenshotTakerTests.java, vividus-extension-selenium/src/test/java/org/vividus/steps/ui/ScreenshotTakingStepsTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/selenium/mobileapp/MobileAppScreenshotTakerTests.java, vividus-plugin-web-app/src/test/java/org/vividus/selenium/screenshot/WebScreenshotTakerTests.java, vividus-tests/src/main/resources/properties/environment/environment.properties, vividus-tests/src/main/resources/story/ui/ScreenshotTakingStepsTests.story
Closes #1795.
- Update screenshot taking step (`When I take screenshot`) to publish screenshots in the report only.
=> [extension-selenium] Update screenshot taking step (#1795)

vividus-extension-selenium/src/main/java/org/vividus/selenium/manager/GenericWebDriverManager.java, vividus-extension-selenium/src/test/java/org/vividus/selenium/manager/GenericWebDriverManagerTests.java
Closes https://github.com/vividus-framework/vividus/issues/1985
=> [extension-selenium] Rely on dimensions provided by appium

vividus-allure-adaptor/src/main/java/org/vividus/report/allure/event/StatusProvider.java, vividus/src/test/java/org/vividus/StatisticsStoryReporterTests.java
=> [vividus-allure-adaptor] Return status only for unwrapped exceptions

vividus/build.gradle
https://groovy.apache.org/download.html#requirements
=> [vividus] Use non-indy Groovy dependency

docs/modules/commons/pages/variables.adoc, vividus-tests/src/main/resources/properties/environment/integration/envinroment.properties, vividus-tests/src/main/resources/story/integration/Expressions.story, vividus/src/integrationTest/java/org/vividus/configuration/BeanFactoryIntegrationTests.java, vividus/src/integrationTest/resources/overriding.properties, vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java, vividus/src/main/java/org/vividus/spring/SpelExpressionResolver.java, vividus/src/test/java/org/vividus/spring/SpelExpressionResolverTests.java
=> [vividus] Allow VIVIDUS expressions in the properties files

docs/modules/plugins/pages/plugin-json.adoc, vividus-plugin-json/build.gradle, vividus-plugin-json/src/main/java/org/vividus/json/JsonContext.java, vividus-plugin-json/src/main/java/org/vividus/json/softassert/JsonSoftAssert.java, vividus-plugin-json/src/main/java/org/vividus/json/steps/JsonPatchSteps.java, vividus-plugin-json/src/main/java/org/vividus/json/steps/JsonSteps.java, vividus-plugin-json/src/main/resources/spring.xml, vividus-plugin-json/src/test/java/org/vividus/json/softassert/JsonSoftAssertTests.java, vividus-plugin-json/src/test/java/org/vividus/json/steps/JsonPatchStepsTests.java, vividus-plugin-json/src/test/java/org/vividus/json/steps/JsonStepsTests.java, vividus-plugin-rest-api/build.gradle, vividus-plugin-rest-api/src/main/java/org/vividus/steps/api/JsonResponseValidationSteps.java, vividus-plugin-rest-api/src/main/resources/spring.xml, vividus-plugin-rest-api/src/test/java/org/vividus/steps/api/JsonResponseValidationStepsTests.java, vividus-tests/src/main/resources/story/integration/JSON.story, vividus-tests/src/main/resources/story/integration/JsonPatchStepsTests.story
=> [plugin-json] Add steps to manipulate JSON element values

.github/workflows/gradle.yml, vividus-tests/src/main/resources/data/tables/system/mobile_app/locators/android.table, vividus-tests/src/main/resources/data/tables/system/mobile_app/locators/ios.table, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story, vividus-tests/src/main/resources/story/system/mobile_app/ProxyMobileStepsTests.story, vividus-tests/src/main/resources/story/system/mobile_app/VisualTesting.story
https://github.com/vividus-framework/vividus-test-app/releases/tag/0.2.0
=> [tests] Use vividus test app version 0.2.0

build.gradle, vividus-tests/src/main/resources/known-issues.json, vividus-tests/src/main/resources/properties/suite/integration/suite.properties, vividus-tests/src/main/resources/story/integration/This Story should not run because GivenStory is failed.story, vividus-tests/src/main/resources/story/integration/knownissue/Known issues.story, vividus-tests/src/main/resources/story/integration/knownissue/Next known issues.story, vividus-tests/src/main/resources/story/integration/knownissue/Validate known issues.story
=> Upgrade to JBehave 5.0.0-alpha.18

docs/modules/plugins/pages/plugin-azure-data-factory.adoc, vividus-plugin-azure-data-factory/src/main/java/org/vividus/azure/datafactory/steps/DataFactorySteps.java, vividus-plugin-azure-data-factory/src/test/java/org/vividus/azure/datafactory/steps/DataFactoryStepsTests.java
=> [plugin-azure-data-factory] Add step to run pipeline with parameters

build.gradle
=> Upgrade to JBehave 5.0.0-alpha.19

docs/modules/user-guides/pages/execute-sql-against-csv.adoc
=> [docs] Document execution of SQL against CSV dataset

build.gradle, vividus-tests/src/main/resources/story/integration/TableTransformers.story, vividus/src/main/java/org/vividus/transformer/AbstractTableLoadingTransformer.java, vividus/src/test/java/org/vividus/transformer/TableLoadingTransformerTests.java
=> Fix transformers chain applied to ExamplesTable from file

build.gradle, docs/modules/commons/pages/expressions.adoc, vividus-engine/src/main/java/org/vividus/steps/ParameterConvertersDecorator.java, vividus-engine/src/test/java/org/vividus/steps/ParameterConvertersDecoratorTests.java, vividus-tests/src/main/resources/story/integration/Expressions.story, vividus-tests/src/main/resources/story/integration/JSON.story, vividus/src/main/java/org/vividus/transformer/ResolvingSelfReferencesEagerlyTransformer.java
=> [vividus-engine] Add expression for generating null

vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/HeadlessCrawlerTableTransformer.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/transformer/HeadlessCrawlerTableTransformerTests.java, vividus-plugin-web-app/build.gradle, vividus-plugin-web-app/src/main/java/org/vividus/crawler/CrawlControllerFactory.java, vividus-plugin-web-app/src/test/java/org/vividus/crawler/CrawlControllerFactoryTests.java, vividus-plugin-web-app/src/test/java/org/vividus/crawler/LinkCrawlerFactoryTests.java, vividus-plugin-web-app/src/test/java/org/vividus/crawler/LinkCrawlerTests.java, vividus-tests/src/main/resources/story/integration/TableTransformers.story
Fixes https://github.com/vividus-framework/vividus/issues/2451
=> Migrate to crawler4j by de.hs-heilbronn.mi

vividus/src/main/java/org/vividus/StatusStoryReporter.java, vividus/src/test/java/org/vividus/StatusStoryReporterTests.java
=> [vividus] Consider system hooks status at exit code calculation

docs/modules/plugins/pages/plugin-html.adoc, vividus-plugin-html/src/main/java/org/vividus/html/LocatorType.java, vividus-plugin-html/src/main/java/org/vividus/steps/html/HtmlSteps.java, vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java, vividus-plugin-html/src/main/resources/steps/defaults/html.steps, vividus-plugin-html/src/test/java/org/vividus/html/LocatorTypeTests.java, vividus-plugin-html/src/test/java/org/vividus/steps/html/HtmlStepsTests.java, vividus-plugin-html/src/test/java/org/vividus/util/HtmlUtilsTests.java, vividus-plugin-html/src/test/resources/org/vividus/steps/html/index.html, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java, vividus-tests/src/main/resources/story/integration/HtmlSteps.story
=> [plugin-html] Allow to use XPath in HTML steps

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/WebJavascriptActions.java, vividus-plugin-web-app/src/main/resources/org/vividus/ui/web/action/scroll-element-into-viewport-center.js, vividus-plugin-web-app/src/main/resources/properties/defaults/default.properties, vividus-plugin-web-app/src/main/resources/spring.xml, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/WebJavascriptActionsTests.java
=> [plugin-web-app] Add ability to specify sticky header size

docs/modules/plugins/pages/plugin-azure-sql-db.adoc, vividus-plugin-azure-sql-db/build.gradle, vividus-plugin-azure-sql-db/src/main/java/org/vividus/azure/sql/SqlDatabaseManagementSteps.java, vividus-plugin-azure-sql-db/src/test/java/org/vividus/azure/sql/SqlDatabaseManagementStepsTests.java
Fixes https://github.com/Azure/azure-sdk-for-java/issues/27268
=> [plugin-azure-sql-db] Use latest Azure API version to retrieve SQL DB properties

docs/modules/plugins/pages/plugin-json.adoc, vividus-plugin-json/src/main/java/org/vividus/json/steps/JsonSteps.java, vividus-plugin-json/src/test/java/org/vividus/json/steps/JsonStepsTests.java, vividus-plugin-rest-api/src/test/java/org/vividus/steps/api/JsonResponseValidationStepsTests.java, vividus-tests/src/main/resources/story/integration/JSON.story
=> [plugin-json] Allow to save JSON as variable

vividus/build.gradle
Blocking issue: https://github.com/datafaker-net/datafaker/issues/87
=> [vividus] Downgrade to Data Faker `1.1.0`

vividus-tests/src/main/resources/story/system/Azure - Functions.story
This reverts commit 473c9d606fe953be38f36ca497b08193db720613.
=> Revert "[tests] Temporarily skip Azure function system test"

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/PageSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/WindowSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/WebJavascriptActions.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/PageStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/WindowStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/WebJavascriptActionsTests.java, vividus-tests/src/main/resources/story/integration/SetContextStepsTests.story
=> [plugin-web-app] Add step closes current window with alerts handling

docs/modules/commons/pages/variables.adoc
=> [docs] Describe regular variables resolution process

docs/modules/plugins/partials/generic-ui-steps.adoc, vividus-extension-selenium/src/main/java/org/vividus/steps/ui/GenericElementSteps.java, vividus-extension-selenium/src/test/java/org/vividus/steps/ui/GenericElementStepsTests.java
=> [vividus-extension-selenium] Add validate for visibility parameters in step checking state of elements

docs/modules/commons/pages/expressions.adoc
=> [docs] Document regex-based expressions

docs/modules/ROOT/pages/tests-configuration.adoc, vividus/src/integrationTest/java/org/vividus/configuration/BeanFactoryIntegrationTests.java, vividus/src/integrationTest/resources/properties/profile/invalid/profile.properties, vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java, vividus/src/main/java/org/vividus/configuration/PropertiesLoader.java, vividus/src/test/java/org/vividus/configuration/ConfigurationResolverTests.java, vividus/src/test/java/org/vividus/configuration/PropertiesLoaderTests.java
=> [vividus] Fail if properties prefixed with `configuration.` loaded from incorrect location

docs/modules/plugins/pages/plugin-rest-api.adoc, vividus-plugin-rest-api/src/main/java/org/vividus/model/NamedEntry.java, vividus-plugin-rest-api/src/main/java/org/vividus/steps/api/HttpResponseValidationSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/steps/api/HttpResponseValidationStepsTests.java, vividus-tests/src/main/resources/story/integration/HTTP.story
=> [vividus-plugin-rest-api] Add possibility to validate response archive with comparison rule

docs/modules/ROOT/pages/tests-configuration.adoc, vividus-engine/src/main/java/org/vividus/batch/BatchResourceConfiguration.java, vividus-engine/src/test/java/org/vividus/batch/BatchResourceConfigurationTests.java, vividus-tests/src/main/resources/properties/suite/failFast/suite.properties
=> [engine] Trim whitespaces in the resource patterns

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/KeyboardActions.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/KeyboardSteps.java, vividus-plugin-mobile-app/src/test/java/org/vividus/mobileapp/action/KeyboardActionsTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/mobileapp/steps/KeyboardStepsTests.java, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
Closes https://github.com/vividus-framework/vividus/issues/2617
=> [plugin-mobile-app] Add step to clear a field and keep keyboard open

docs/modules/plugins/pages/plugin-rest-api.adoc, vividus-plugin-rest-api/src/main/java/org/vividus/steps/api/HttpResponseValidationSteps.java, vividus-plugin-rest-api/src/main/resources/steps/defaults/composite.steps, vividus-tests/src/main/resources/story/integration/HTTP.story
=> [plugin-rest-api] Refactor archive validation step wording

vividus-allure-adaptor/src/main/resources/allure-customization/plugins/vividus-step-formatting/styles.css, vividus-allure-adaptor/src/main/resources/org/vividus/report/allure/spring.xml
=> [allure-adaptor] Improve formatting of steps in the report

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/CodeSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetVariableSteps.java, vividus-plugin-web-app/src/main/resources/steps/defaults/code.steps, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/CodeStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/SetVariableStepsTests.java, vividus-tests/src/main/resources/story/integration/CodeSteps.story
=> [plugin-web-app] Align JS executing steps wording

docs/modules/plugins/pages/plugin-rest-api.adoc
Add response-code dynamic variable info into documentation
=> Add response-code dynamic variable info into documentation

docs/modules/plugins/partials/locator-header.adoc, vividus-extension-selenium/src/main/java/org/vividus/ui/action/search/LocatorPattern.java, vividus-extension-selenium/src/main/java/org/vividus/ui/util/LocatorConversionUtils.java, vividus-extension-selenium/src/test/java/org/vividus/ui/action/search/LocatorPatternTests.java, vividus-extension-selenium/src/test/java/org/vividus/ui/util/LocatorConversionUtilsTests.java
=> [extension-selenium] Fix reusable locator parameters processing

docs/modules/plugins/pages/plugin-web-app.adoc
Duplicated words deletion in Video section description
=> Update plugin-web-app.adoc with duplicated words deletion

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/ApplicationSteps.java, vividus-plugin-mobile-app/src/test/java/org/vividus/mobileapp/steps/ApplicationStepsTests.java, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
=> [plugin-mobile-app] Add step to send application to the background

vividus-extension-selenium/src/main/resources/properties/defaults/default.properties, vividus-extension-visual-testing/src/main/resources/properties/defaults/default.properties
Failures:
- https://github.com/vividus-framework/vividus-sample-tests/runs/7352508934?check_suite_focus=true
- https://github.com/vividus-framework/vividus-sample-tests/runs/7352509045?check_suite_focus=true
=> [visual] Fix location of default properties

docs/modules/plugins/pages/plugin-excel.adoc, vividus-plugin-excel/src/main/java/org/vividus/excel/ExcelSheetsExtractor.java, vividus-plugin-excel/src/main/java/org/vividus/excel/transformer/ExcelTableTransformer.java, vividus-plugin-excel/src/test/java/org/vividus/excel/ExcelSheetParserTests.java, vividus-plugin-excel/src/test/java/org/vividus/excel/ExcelSheetsExtractorTests.java, vividus-plugin-excel/src/test/java/org/vividus/excel/transformer/ExcelTableTransformerTests.java, vividus-tests/src/main/resources/story/integration/ExcelSteps.story
=> [plugin-excel] Enable loading of Excel files by `FROM_EXCEL` transformer

docs/modules/commons/pages/expressions.adoc, docs/modules/commons/partials/data-generating.adoc
Closes #2940
Documents `generate` expression:
1. Adds examples for various data providers;
2. Adds usage examples for:
- Letterify
- Numerify
- Bothify
- Templatify
- Examplify
- Regexify
- Options
- Csv
- Json
=> Add docs for data generating expressions

build.gradle, vividus-tests/src/main/resources/story/integration/Precondition4.story, vividus-tests/src/main/resources/story/integration/Use GivenStories.story
Bump JBehave from `5.0.1-alpha` to `5.0.1-alpha.2`. 
Add integration tests for fixed issues:
https://jbehave.atlassian.net/browse/JBEHAVE-1550
https://jbehave.atlassian.net/browse/JBEHAVE-1551
=> Bump JBehave from `5.0.1-alpha` to `5.0.1-alpha.2`. Add integration tests

docs/modules/plugins/pages/plugin-excel.adoc, vividus-plugin-excel/src/main/java/org/vividus/excel/ExcelSheetWriter.java, vividus-plugin-excel/src/main/java/org/vividus/steps/ExcelFileSteps.java, vividus-plugin-excel/src/test/java/org/vividus/excel/ExcelSheetWriterTests.java, vividus-plugin-excel/src/test/java/org/vividus/steps/ExcelFileStepsTests.java, vividus-tests/src/main/resources/story/integration/ExcelSteps.story
=> [plugin-excel] Add ability to add sheet to excel file

docs/modules/ROOT/pages/tests-configuration.adoc
Closes #2968
Adds paragraphs for profiles and environment configuration.
=> Add profiles and environment configuration description

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/ActionSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/model/SequenceActionType.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/ActionStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/model/SequenceActionTypeTests.java, vividus-tests/src/main/resources/story/integration/ActionSteps.story
=> [plugin-web-app] Add ability to press and release sequences of char keys

vividus-analytics/src/main/java/org/vividus/analytics/GoogleAnalyticsFacade.java, vividus-analytics/src/test/java/org/vividus/analytics/GoogleAnalyticsFacadeTests.java
=> [vividus-analytics] Add root directory handling for Unix and Unix-like systems

docs/modules/plugins/pages/plugin-db.adoc, docs/modules/user-guides/pages/use-in-memory-db-to-manage-test-data.adoc
Closes #2977,  Closes #1806
Adds JDBC introduction and provides setup examples.
=> Add JDBC setup documentation

vividus-plugin-excel/src/main/java/org/vividus/excel/ExcelSheetWriter.java, vividus-plugin-excel/src/test/java/org/vividus/excel/ExcelSheetWriterTests.java
=> [plugin-excel] Add ability to create Excel files with non-distinct columns

docs/modules/commons/pages/variables.adoc
=> Document batch level variables

vividus-engine/src/main/java/org/vividus/model/jbehave/AbstractStepsContainer.java, vividus-engine/src/test/java/org/vividus/model/jbehave/StepsContainerTests.java, vividus-to-azure-devops-exporter/src/test/java/org/vividus/azure/devops/facade/AzureDevOpsFacadeTests.java, vividus-to-xray-exporter/src/test/java/org/vividus/xray/factory/TestExecutionFactoryTests.java
Assertion failures go into system steps
Brokens go into user steps
=> [exporter] Consider assertion failures for test status calculation

docs/modules/ROOT/pages/tests-configuration.adoc, docs/modules/plugins/pages/plugin-web-app.adoc
=> Add web-app profiles description

vividus-plugin-web-app/src/main/resources/steps/defaults/composite.steps
=> [vividus-plugin-web-app] Deprecated step was deleted

docs/modules/plugins/pages/plugin-mobile-app.adoc
=> [docs] Remove docs for removed step switching to web view by index

vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/ApplicationSteps.java, vividus-plugin-mobile-app/src/test/java/org/vividus/mobileapp/steps/ApplicationStepsTests.java
BrowserStack doesn't return `app` capability.
=> [plugin-mobile-app] Do not log `app` capability if it's not available

docs/modules/commons/pages/vividus-steps.adoc, vividus-tests/src/main/resources/story/integration/ExecutableSteps.story, vividus/src/main/java/org/vividus/steps/ExecutableSteps.java, vividus/src/test/java/org/vividus/steps/ExecutableStepsTests.java
=> [vividus] Make conditional step accept predefined conditions only

vividus-tests/src/main/resources/story/integration/YAML.story
=> [tests] Remove invalid requirement reference

vividus-extension-selenium/src/main/java/org/vividus/ui/action/search/AbstractElementAction.java, vividus-extension-selenium/src/test/java/org/vividus/ui/action/search/AbstractElementSearchActionTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/search/ElementSearchActionTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/search/LinkUrlSearchTests.java
=> [extension-selenium] Take into account `visibility` parameter at wait on search

docs/modules/plugins/partials/generic-ui-steps.adoc, vividus-extension-selenium/src/main/java/org/vividus/steps/ui/GenericWaitSteps.java, vividus-extension-selenium/src/main/java/org/vividus/steps/ui/validation/BaseValidations.java, vividus-extension-selenium/src/main/java/org/vividus/steps/ui/validation/IBaseValidations.java, vividus-extension-selenium/src/main/java/org/vividus/ui/action/AbstractExpectedConditions.java, vividus-extension-selenium/src/main/java/org/vividus/ui/action/IExpectedConditions.java, vividus-extension-selenium/src/test/java/org/vividus/steps/ui/GenericWaitStepsTests.java, vividus-extension-selenium/src/test/java/org/vividus/steps/ui/validation/BaseValidationsTests.java, vividus-extension-selenium/src/test/java/org/vividus/ui/action/ExpectedSearchActionsConditionsTests.java, vividus-extension-selenium/src/test/java/org/vividus/ui/action/ExpectedSearchContextConditionsTests.java, vividus-tests/src/main/resources/properties/environment/integration/envinroment.properties, vividus-tests/src/main/resources/story/integration/WaitStepsTests.story
=> [extension-selenium] Search for element at first in step validating element existence

docs/modules/user-guides/pages/pipeline-with-proxy.adoc
=> [docs] Update docker guide for Selenium 4

docs/modules/plugins/pages/plugin-rest-api.adoc
=> [docs] Document FROM_JSON transformer

vividus-tests/src/main/resources/properties/environment/integration/environment.properties
=> [tests] Change main page url for regression environment

docs/modules/commons/pages/vividus-steps.adoc, docs/modules/integrations/pages/zephyr-exporter.adoc, docs/modules/plugins/pages/plugin-web-app.adoc, docs/modules/plugins/partials/generic-ui-steps.adoc, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/ElementSteps.java, vividus-plugin-web-app/src/main/resources/steps/defaults/composite.steps, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/ElementStepsTests.java, vividus-tests/src/main/resources/story/integration/ActionSteps.story, vividus-tests/src/main/resources/story/integration/BarcodeStepsTests.story, vividus-tests/src/main/resources/story/integration/ElementStepsTests.story, vividus-tests/src/main/resources/story/integration/GenericNestedSteps.story, vividus-tests/src/main/resources/story/integration/PageStepsTests.story, vividus-tests/src/main/resources/story/integration/ProxyStepsTests.story, vividus-tests/src/main/resources/story/integration/SetContextStepsTests.story, vividus-tests/src/main/resources/story/integration/VideoSteps.story, vividus-tests/src/main/resources/story/integration/WaitStepsTests.story, vividus-tests/src/main/resources/story/integration/WebStorageSteps.story, vividus/src/main/java/org/vividus/steps/ExecutableSteps.java
=> [plugin-web-app] Add click step with retry on stale element exception

vividus-plugin-web-app/build.gradle
Opera browser is managed by Chrome driver.
=> [plugin-web-app] Remove unused `selenium-opera-driver` dependency

docs/modules/commons/pages/expressions.adoc, vividus-tests/src/main/resources/story/integration/Expressions.story, vividus/src/main/java/org/vividus/expression/StringsExpressionProcessor.java, vividus/src/test/java/org/vividus/expression/StringsExpressionProcessorTests.java
Closes https://github.com/vividus-framework/vividus/issues/3118
=> [vividus] Introduce substringBefore/After expressions

.github/workflows/gradle.yml, vividus-tests/src/main/resources/properties/suite/system/mobile_app/healthcheck/mobitru/android/suite.properties, vividus-tests/src/main/resources/properties/suite/system/mobile_app/healthcheck/mobitru/ios/suite.properties, vividus-tests/src/main/resources/story/system/mobile_app/MobitruHealthCheckMobileApp.story
=> [tests] Accept iOS alerts in Mobitru healthcheck tests

docs/modules/plugins/pages/plugin-accessibility.adoc, docs/modules/plugins/pages/plugin-json.adoc, docs/modules/plugins/pages/plugin-rest-api.adoc, docs/modules/plugins/pages/plugin-web-app.adoc, docs/modules/plugins/partials/generic-ui-steps.adoc
https://blog.heroku.com/next-chapter:
"Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services."
=> [docs] Replace all Heroku references

docs/modules/commons/pages/table-transformers.adoc, vividus-tests/src/main/resources/story/integration/TableTransformers.story, vividus/src/main/java/org/vividus/transformer/CartesianProductTableTransformer.java, vividus/src/test/java/org/vividus/transformer/CartesianProductTableTransformerTests.java
[Cartesian Product of Empty Set](https://www.storyofmathematics.com/empty-set/#:~:text=The%20Cartesian%20Product%20of%20any,empty%20set%20contains%20no%20elements.)
=> [vividus] Allow handling of empty tables to CARTESIAN_PRODUCT transformer according to mathematical logic

docs/modules/integrations/partials/export.adoc
=> [docs] Improve exporter execution steps

vividus/src/main/java/org/vividus/steps/SpringStepFactoryBeanPostProcessor.java, vividus/src/test/java/org/vividus/steps/SpringStepFactoryBeanPostProcessorTests.java
=> [vividus] Add duplicate step bean name validation

docs/modules/plugins/pages/plugin-datetime.adoc, vividus-plugin-datetime/src/main/java/org/vividus/expression/DateExpression.java, vividus-plugin-datetime/src/main/java/org/vividus/expression/DateExpressionProcessor.java, vividus-plugin-datetime/src/main/java/org/vividus/expression/DiffDateExpressionProcessor.java, vividus-plugin-datetime/src/main/java/org/vividus/expression/FormatDateExpressionProcessor.java, vividus-plugin-datetime/src/main/java/org/vividus/expression/FormatDateToExpressionProcessor.java, vividus-plugin-datetime/src/main/java/org/vividus/expression/NormalizingArguments.java, vividus-plugin-datetime/src/main/java/org/vividus/expression/ShiftDateExpressionProcessor.java, vividus-plugin-datetime/src/test/java/org/vividus/expression/DateExpressionProcessorTests.java, vividus-plugin-datetime/src/test/java/org/vividus/expression/DiffDateExpressionProcessorTests.java, vividus-plugin-datetime/src/test/java/org/vividus/expression/FormatDateExpressionProcessorTests.java, vividus-plugin-datetime/src/test/java/org/vividus/expression/FormatDateToExpressionProcessorTests.java
=> [plugin-datetime] Refactor expression processors

docs/modules/plugins/pages/plugin-datetime.adoc
=> [docs] Document `fromEpochSecond` expression

vividus-plugin-json/src/test/java/org/vividus/json/steps/JsonStepsTests.java, vividus-tests/src/main/resources/story/integration/JSON.story, vividus-util/src/main/java/org/vividus/util/json/JsonPathUtils.java, vividus-util/src/test/java/org/vividus/util/json/JsonPathUtilsTests.java
=> Fix validation of long float numbers in JSON-s

vividus-engine/src/main/java/org/vividus/steps/ExpressionAdaptor.java, vividus-engine/src/test/java/org/vividus/steps/ExpressionAdapterTests.java, vividus-tests/src/main/resources/story/integration/Expressions.story
=> [engine] Fix expressions evaluation in multiline strings

docs/modules/commons/pages/expressions.adoc
=> [docs] Document anyOf expression

vividus-plugin-web-app-to-rest-api/src/main/resources/resources-validation-result.ftl
=> [plugin-web-app-to-rest-api] Make links clickable in resource validation results attachment

.github/workflows/gradle.yml, docs/modules/ROOT/pages/tests-configuration.adoc, vividus-tests/src/main/resources/properties/configuration.properties, vividus/src/integrationTest/java/org/vividus/configuration/BeanFactoryIntegrationTests.java, vividus/src/integrationTest/resources/properties/profile/invalid/profile.properties, vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java, vividus/src/main/java/org/vividus/configuration/PropertiesLoader.java, vividus/src/main/java/org/vividus/log/TestInfoLogger.java, vividus/src/main/resources/properties/defaults/default.properties, vividus/src/test/java/org/vividus/configuration/ConfigurationResolverTests.java, vividus/src/test/java/org/vividus/configuration/PropertiesLoaderTests.java, vividus/src/test/java/org/vividus/log/TestInfoLoggerTests.java
=> [vividus] Introduce configuration sets

vividus-extension-selenium/src/main/java/org/vividus/ui/util/XpathLocatorUtils.java, vividus-extension-selenium/src/test/java/org/vividus/ui/util/XpathLocatorUtilsTests.java
=> [extension-selenium] Fix XPath space normalization for sequence of functions

.github/workflows/gradle.yml
Relates https://github.com/codecov/codecov-action/issues/837
=> Add codecov token to avoid not_found error when publishing data

docs/modules/plugins/pages/plugin-kafka.adoc, vividus-plugin-kafka/build.gradle, vividus-plugin-kafka/src/main/java/org/vividus/steps/kafka/KafkaSteps.java, vividus-plugin-kafka/src/test/java/org/vividus/steps/kafka/KafkaStepsIntegrationTests.java, vividus-tests/src/main/resources/story/system/Kafka.story
=> [plugin-kafka] Add ability to send Kafka event with specifying a key

vividus/src/main/resources/templates/udiff.ftl
=> [vividus] Handle special chars in template generating text visual diff

vividus-tests/src/main/resources/steps/composite.steps
Relates: https://jbehave.atlassian.net/browse/JBEHAVE-1578
=> [tests] Add test for relaxed composite steps parsing

docs/modules/ROOT/pages/tests-configuration.adoc, vividus-http-client/build.gradle, vividus-http-client/src/main/java/org/vividus/http/client/HttpClientFactory.java, vividus-http-client/src/test/java/org/vividus/http/client/HttpClientFactoryTests.java
=> [http-client] Add support of Integrated Windows authentication

vividus-tests/src/main/resources/story/integration/ResourceCheckSteps.story
[documentation](https://docs.vividus.dev/vividus/latest/plugins/plugin-web-app.html#_source_code)
=> [tests] Use correct variable to receive web page sources for ResourceCheckSteps.story

docs/modules/plugins/partials/selenium-properties.adoc, vividus-extension-selenium/src/main/java/org/vividus/selenium/RemoteWebDriverFactory.java, vividus-extension-selenium/src/main/resources/properties/defaults/default.properties, vividus-extension-selenium/src/main/resources/vividus-extension/spring.xml, vividus-extension-selenium/src/test/java/org/vividus/selenium/RemoteWebDriverFactoryTests.java
=> [extension-selenium] Add ability to retry session creation on HTTP connect timeout

vividus-plugin-rest-api/src/main/java/org/vividus/steps/http/HttpResourceValidationSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/steps/http/HttpResourceValidationStepsTests.java, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/steps/integration/ResourceCheckStepsTests.java, vividus-soft-assert/src/main/java/org/vividus/softassert/FailableRunnable.java, vividus-soft-assert/src/main/java/org/vividus/softassert/ISoftAssert.java, vividus-soft-assert/src/main/java/org/vividus/softassert/SoftAssert.java, vividus-soft-assert/src/test/java/org/vividus/softassert/SoftAssertTests.java, vividus/src/main/java/org/vividus/softassert/JBehaveFailTestFastManager.java, vividus/src/test/java/org/vividus/softassert/JBehaveFailTestFastManagerTests.java
=> Make resource validation fail-fast safety

vividus-plugin-rest-api/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-web-app-to-rest-api/src/main/resources/vividus-plugin/spring.xml, vividus-tests/src/main/resources/story/integration/ResourceCheckSteps.story, vividus-tests/src/main/resources/story/integration/RestApiStepsTests.story
=> [plugin-rest-api] Split resource validator for different types of validation

vividus-plugin-rest-api/src/main/java/org/vividus/steps/api/HttpRequestSteps.java, vividus-tests/src/main/resources/story/integration/HTTP.story
Fix regression introduced by #3923
=> [plugin-rest-api] Restore request body step syntax

vividus-engine/src/main/java/org/vividus/annotation/Replacement.java, vividus-engine/src/main/java/org/vividus/annotation/ReplacementMonitor.java, vividus-engine/src/main/resources/org/vividus/engine/spring.xml, vividus-engine/src/test/java/org/vividus/annotation/ReplacementMonitorTests.java, vividus-extension-selenium/src/main/java/org/vividus/steps/ui/GenericSetContextSteps.java, vividus-extension-selenium/src/test/java/org/vividus/steps/ui/GenericSetContextStepsTests.java, vividus-plugin-kafka/src/main/java/org/vividus/steps/kafka/KafkaSteps.java, vividus-plugin-kafka/src/test/java/org/vividus/steps/kafka/KafkaStepsIntegrationTests.java, vividus-plugin-rest-api/src/main/java/org/vividus/steps/api/HttpResponseValidationSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/steps/api/HttpResponseValidationStepsTests.java, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/ElementSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/FieldSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/PageSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetVariableSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/TextValidationSteps.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/ElementStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/PageStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/SetVariableStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/TextValidationStepsTests.java
=> [engine] Add annotation for logging and replacing deprecated steps

docs/modules/plugins/pages/plugin-azure-storage-account.adoc
=> [docs] Improve docs for step filtering blobs

docs/modules/developer-guides/pages/deprecating-steps.adoc, vividus-engine/src/main/java/org/vividus/replacement/DeprecatedCompositeStepsReporter.java, vividus-engine/src/test/java/org/vividus/replacement/DeprecatedCompositeStepsReporterTests.java, vividus-extension-selenium/src/main/resources/steps/defaults/deprecated.steps, vividus-plugin-accessibility/src/main/resources/steps/defaults/deprecated.steps, vividus-plugin-azure-event-grid/src/main/resources/steps/defaults/composite.steps, vividus-plugin-azure-key-vault/src/main/resources/steps/defaults/composite.steps, vividus-plugin-azure-sql-db/src/main/resources/steps/defaults/composite.steps, vividus-plugin-azure-storage-account/src/main/resources/steps/defaults/composite.steps, vividus-plugin-json/src/main/resources/steps/defaults/deprecated.steps, vividus-plugin-kafka/src/main/resources/steps/defaults/deprecated.steps, vividus-plugin-mobile-app/src/main/resources/steps/defaults/composite.steps, vividus-plugin-rest-api/src/main/resources/steps/defaults/composite.steps, vividus-plugin-web-app/src/main/resources/steps/defaults/composite.steps, vividus-tests/src/main/resources/steps/deprecated.steps, vividus/src/main/java/org/vividus/runner/DeprecatedStepsReplacer.java, vividus/src/main/java/org/vividus/runner/StepsPrinter.java, vividus/src/main/resources/steps/defaults/composite.steps, vividus/src/test/java/org/vividus/runner/DeprecatedStepsReplacerTests.java, vividus/src/test/java/org/vividus/runner/StepsPrinterTests.java
=> [vividus] Mark deprecated composite steps in printing steps task

vividus/src/main/java/org/vividus/configuration/EncryptedPropertiesProcessor.java, vividus/src/test/java/org/vividus/configuration/EncryptedAbstractPropertiesProcessorTests.java
=> [vividus] Deprecate default encryption password

vividus-allure-adaptor/src/main/resources/allure-customization/plugins/vividus-step-formatting/styles.css
Relates: https://github.com/allure-framework/allure2/pull/2015
=> [allure-adaptor] Fix broken step formatting in allure

vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/MouseActions.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/MouseActionsTests.java
1) https://github.com/SeleniumHQ/selenium/issues/10468#issuecomment-1075734592:
> This is expected behavior per the specification. Mouse movements should not scroll the page
2) https://github.com/SeleniumHQ/selenium/issues/10180#issuecomment-1000900445
=> [plugin-web-app] Always scroll element into view before hovering mouse over it

vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/PageSteps.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/PageStepsTests.java
=> [plugin-web-app] Move credentials from user info to http context in page steps

build.gradle, vividus-allure-adaptor/build.gradle, vividus-allure-adaptor/src/main/resources/allure-customization/plugins/vividus-step-formatting/styles.css, vividus-plugin-json/build.gradle
=> Bump Allure from `2.23.0` to `2.23.1`

docs/modules/plugins/pages/plugin-visual.adoc, vividus-plugin-mobile-app/build.gradle, vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/MobileAppAshotFactory.java, vividus-plugin-mobile-app/src/test/java/org/vividus/selenium/mobileapp/screenshot/MobileAppAshotFactoryTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/ui/mobileapp/screenshot/MobileAppScreenshotParametersFactoryTests.java, vividus-tests/src/main/resources/story/system/mobile_app/VisualTesting.story
The replacement is `VIEWPORT` strategy
=> [plugin-mobile-app] Remove deprecated shooting strategy named `SIMPLE`

vividus/src/main/java/org/vividus/configuration/EncryptedPropertiesProcessor.java, vividus/src/test/java/org/vividus/configuration/ConfigurationResolverTests.java, vividus/src/test/java/org/vividus/configuration/EncryptedPropertiesProcessorTests.java
=> [vividus] Drop default encryptor password

docs/modules/plugins/pages/plugin-datetime.adoc, vividus-plugin-datetime/src/main/java/org/vividus/datetime/expression/FormatDateExpressionProcessor.java, vividus-plugin-datetime/src/main/resources/properties/defaults/default.properties, vividus-plugin-datetime/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-datetime/src/test/java/org/vividus/datetime/expression/FormatDateExpressionProcessorTests.java
=> [plugin-datetime] Add ability to configure locale for `formatDate` expression

docs/modules/ROOT/pages/reporting.adoc, docs/modules/ROOT/pages/tests-configuration.adoc, vividus-allure-adaptor/src/main/java/org/vividus/report/allure/VividusLabel.java, vividus-allure-adaptor/src/test/java/org/vividus/report/allure/VividusLabelTests.java
=> [allure-adaptor] Deprecate `@severity` meta tag in favor of `@priority` meta tag

vividus-docker-bundler/build.gradle, vividus-plugin-parquet/build.gradle
https://docs.gradle.org/current/userguide/upgrading_version_8.html#project_builddir
=> Replace usages of deprecated Gradle property `$buildDir`

docs/modules/ROOT/pages/getting-started.adoc
=> [docs] Add info on how to open report using VSCode

docs/modules/plugins/pages/plugin-mobile-app.adoc, docs/modules/user-guides/pages/appium-setup.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/DeviceActions.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/ApplicationSteps.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/DeviceSteps.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/KeyboardSteps.java
=> Fix links to Appium docs

vividus/src/systemTest/java/org/vividus/configuration/VaultTests.java
See https://github.com/testcontainers/testcontainers-java/pull/7576
=> [vividus] Use non-deprecated way to init secrets in Vault for system tests

vividus-plugin-lighthouse/src/main/java/org/vividus/lighthouse/LighthouseSteps.java, vividus-plugin-lighthouse/src/test/java/org/vividus/lighthouse/LighthouseStepsTests.java
updated for improving readability of lighthouse comparison results
=> [plugin-lighthouse] Update LighthouseSteps results text

vividus-allure-adaptor/src/main/java/org/vividus/report/allure/AllureReportGenerator.java, vividus-allure-adaptor/src/test/java/org/vividus/report/allure/AllureReportGeneratorTests.java, vividus-engine/src/main/java/org/vividus/batch/BatchStorage.java, vividus-engine/src/main/java/org/vividus/context/DynamicConfigurationManager.java, vividus-extension-selenium/src/main/java/org/vividus/proxy/ThreadedProxy.java, vividus-plugin-applitools/src/main/java/org/vividus/visual/eyes/model/AccessibilityCheckResult.java, vividus-plugin-browserstack/src/main/java/org/vividus/selenium/browserstack/BrowserStackLocalManager.java, vividus-plugin-csv/src/test/java/org/vividus/csv/CsvFileCreatorTests.java, vividus-plugin-email/src/main/java/org/vividus/email/service/ImapFetchService.java, vividus-plugin-excel/src/main/java/org/vividus/excel/ExcelSheetsExtractor.java, vividus-plugin-lighthouse/src/main/java/org/vividus/lighthouse/LighthouseSteps.java, vividus-plugin-saucelabs/src/main/java/org/vividus/selenium/sauce/SauceConnectManager.java, vividus-plugin-web-app/src/main/java/org/vividus/converter/ui/web/StringToDimensionParameterConverter.java, vividus-util/src/test/java/org/vividus/util/ResourceUtilsTests.java, vividus/src/main/java/org/vividus/expression/Base64ExpressionProcessors.java, vividus/src/main/java/org/vividus/expression/HashExpressionProcessors.java, vividus/src/main/java/org/vividus/results/CollectingStatisticsStoryReporter.java, vividus/src/test/java/org/vividus/results/CollectingStatisticsStoryReporterTests.java
Address new SpotBugs violations detected at migration from v4.7.3 to v4.8.0
=> Fix SpotBugs violations

vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/crawler/transformer/AbstractFetchingUrlsTableTransformer.java, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/http/HttpRedirectsProvider.java, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/RedirectValidationSteps.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/crawler/transformer/HeadlessCrawlerTableTransformerTests.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/crawler/transformer/SiteMapTableTransformerTests.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/http/HttpRedirectsProviderTests.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/steps/integration/RedirectValidationStepsTests.java
=> [plugin-web-app-to-rest-api] Remove `IllegalStateException` from http redirects provider

vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java, vividus-plugin-mobile-app/src/test/java/io/appium/java_client/TouchActionsTests.java
The reason to change:
```
2023-10-19 07:36:11,065 [batch-1-thread-1] INFO  org.vividus.log.LoggingStoryReporter - When I swipe up to element located by `accessibilityId(menu item log in)` with duration PT3S (FAILED)
(org.openqa.selenium.UnsupportedCommandException: {"value":{"error":"unknown method","message":"Not implemented","stacktrace":"NotImplementedError: Not implemented\n    at AndroidUiautomator2Driver.swipe (/Users/runner/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/actions.js:48:11)\n    at AndroidUiautomator2Driver.performTouch (/Users/runner/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/touch.js:226:25)\n    at processTicksAndRejections …
```
=> [plugin-mobile-app] Use W3C actions to perform swipe action

.lift.toml
Sonatype Lift is sunset: https://community.sonatype.com/t/sunset-notice-sonatype-lift/10940
=> Remove Sonatype Lift config

vividus-exporter-commons/build.gradle, vividus-to-azure-devops-exporter/build.gradle, vividus-to-xray-exporter/build.gradle, vividus-to-zephyr-exporter/build.gradle
=> Force to use Log4J2 as logging framework by all exporters

docs/modules/plugins/pages/plugin-mobile-app.adoc, docs/modules/plugins/pages/plugin-web-app.adoc, docs/modules/plugins/partials/selenium-properties.adoc, vividus-extension-selenium/src/main/java/org/vividus/selenium/RemoteWebDriverFactory.java, vividus-extension-selenium/src/main/resources/vividus-extension/spring.xml, vividus-extension-selenium/src/test/java/org/vividus/selenium/RemoteWebDriverFactoryTests.java, vividus-plugin-mobile-app/src/main/resources/properties/profile/mobile_app/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/phone/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/tablet/profile.properties
=> [extension-selenium] Add ability to configure HTTP read timeout for Selenium Grid

docs/modules/ROOT/pages/reporting.adoc, vividus-allure-adaptor/src/main/java/org/vividus/report/allure/AllureStoryReporter.java, vividus-allure-adaptor/src/test/java/org/vividus/report/allure/AllureStoryReporterTests.java, vividus/src/main/resources/org/vividus/spring-vividus.xml, vividus/src/main/resources/properties/defaults/default.properties
=> [allure-adaptor] Add ability to hide Parameters section in report

docs/modules/integrations/partials/authentication.adoc
Closes https://github.com/vividus-framework/vividus/issues/4502
=> [docs] Update xray docs with token authentication

build.gradle
=> Bump JBehave from `5.1.2-alpha.2` to `6.0.0-alpha`

build.gradle
=> Bump JBehave from `6.0.0-alpha.2` to `6.0.0-alpha.3`

vividus/src/main/resources/org/vividus/spring.xml
All expression beans are registered explicitly
=> [vividus] Remove scan for VIVIDUS expression beans

vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/validator/model/ResourceValidationError.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/steps/integration/ResourceCheckStepsTests.java, vividus-tests/src/main/resources/known-issues.json, vividus-tests/src/main/resources/story/integration/GenericSetVariableSteps.story, vividus-tests/src/main/resources/story/integration/ResourceCheckSteps.story, vividus-tests/src/main/resources/story/integration/TableTransformers.story
=> [plugin-web-app-to-rest-api] Add support for jump links to named anchors in steps validating resources

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/WebStorageSteps.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/WebStorageStepsTests.java, vividus-tests/src/main/resources/story/integration/WebStorageSteps.story
=> Add ability to remove items from web storage

docs/modules/plugins/partials/plugin-web-app-profiles.adoc, vividus-plugin-web-app/src/main/resources/properties/profile/web/headless/chrome/profile.properties
=> [plugin-web-app] Add shortcut property to set window size for Headless Chrome

vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java, vividus-plugin-mobile-app/src/test/java/io/appium/java_client/TouchActionsTests.java, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
Appium driver for Android UIAutomator2 removed obsolete MJSONWP touch route handlers: https://github.com/appium/appium-uiautomator2-driver/releases/tag/v3.0.0
=> [plugin-mobile-app] Use W3C actions to perform tap action

docs/modules/plugins/pages/plugin-datetime.adoc, vividus-plugin-datetime/src/main/java/org/vividus/datetime/expression/EpochExpressionProcessors.java, vividus-plugin-datetime/src/test/java/org/vividus/datetime/expression/EpochExpressionProcessorsTests.java, vividus-tests/src/main/resources/story/integration/Expressions.story, vividus-util/src/main/java/org/vividus/util/DateUtils.java, vividus-util/src/test/java/org/vividus/util/DateUtilsTests.java
=> [plugin-datetime] Add `fromEpochMilli`/`toEpochMilli` expressions

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/selenium/WebDriverFactory.java, vividus-plugin-web-app/src/main/java/org/vividus/selenium/authentication/BasicAuthCredentials.java, vividus-plugin-web-app/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-web-app/src/test/java/org/vividus/selenium/WebDriverFactoryTests.java, vividus-tests/src/main/resources/properties/environment/system/web/environment.properties, vividus-tests/src/main/resources/story/system/BasicAuthentication.story
=> [plugin-web-app] Add ability to configure basic authentication

docs/modules/plugins/pages/plugin-azure-cosmos-db.adoc, vividus-plugin-azure-cosmos-db/src/main/java/org/vividus/azure/cosmos/CosmosDbService.java, vividus-plugin-azure-cosmos-db/src/main/java/org/vividus/azure/cosmos/model/CosmosDbAccount.java, vividus-plugin-azure-cosmos-db/src/test/java/org/vividus/azure/cosmos/CosmosDbServiceTests.java
Details: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/tune-connection-configurations-java-sdk-v4?tabs=api-sync#connection-configuration
=> [azure-cosmos-db] Add ability to configure connection mode

docs/modules/plugins/pages/plugin-web-app-playwright.adoc, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/BrowserContextConfiguration.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/BrowserContextProvider.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/WaitSteps.java, vividus-plugin-web-app-playwright/src/main/resources/properties/profile/web_pw/profile.properties, vividus-plugin-web-app-playwright/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/BrowserContextProviderTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/steps/WaitStepsTests.java
…disappearance and number of elements
=> [plugin-web-app-playwright] Add steps to wait for element appearance/disappearance and number of elements

vividus-plugin-web-app-to-rest-api/build.gradle, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/crawler/CrawlControllerFactory.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/crawler/CrawlControllerFactoryTests.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/crawler/LinkCrawlerFactoryTests.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/crawler/LinkCrawlerTests.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/crawler/transformer/HeadlessCrawlerTableTransformerTests.java
=> [plugin-web-app-to-rest-api] Migrate crawler storage from Sleepycat to HSQLDB

docs/modules/plugins/pages/plugin-web-app-playwright.adoc, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/DropdownSteps.java, vividus-plugin-web-app-playwright/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/steps/DropdownStepsTests.java
Report: 
[allure.zip](https://github.com/user-attachments/files/16126890/allure.zip)
=> [plugin-web-app-playwright] Add step to select option in dropdown

docs/modules/plugins/pages/plugin-web-app-playwright.adoc, docs/modules/plugins/partials/common-web-app-wait-steps.adoc, docs/modules/plugins/partials/ui-context-management-steps.adoc, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/action/WaitActions.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/SetContextSteps.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/WaitSteps.java, vividus-plugin-web-app-playwright/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/action/WaitActionsTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/steps/SetContextStepsTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/steps/WaitStepsTests.java
Report: [allure.zip](https://github.com/user-attachments/files/16158414/allure.zip)
=> [plugin-web-app-playwright] Add tab title waiting steps

docs/modules/plugins/pages/plugin-web-app-playwright.adoc, docs/modules/plugins/partials/proxy-steps.adoc, vividus-extension-selenium/src/main/java/org/vividus/proxy/steps/ProxySteps.java, vividus-extension-selenium/src/main/resources/steps/defaults/deprecated.steps, vividus-extension-selenium/src/test/java/org/vividus/proxy/steps/ProxyStepsTests.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/BrowserContextProvider.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/model/HttpMessagePart.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/network/NetworkContext.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/NetworkValidationSteps.java, vividus-plugin-web-app-playwright/src/main/resources/properties/profile/web_pw/profile.properties, vividus-plugin-web-app-playwright/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/BrowserContextProviderTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/model/HttpMessagePartTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/network/NetworkContextTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/steps/NetworkValidationStepsTests.java, vividus-tests/src/main/resources/story/integration/ProxyStepsTests.story
Report: 
[allure.zip](https://github.com/user-attachments/files/16238767/allure.zip)
=> [plugin-web-app-playwright] Add steps to validate network requests

docs/modules/plugins/pages/plugin-web-app-playwright.adoc, vividus-extension-selenium/src/main/resources/vividus-extension/spring.xml, vividus-extension-ui/build.gradle, vividus-extension-ui/src/main/java/org/vividus/ui/converter/PointConverter.java, vividus-extension-ui/src/main/java/org/vividus/ui/model/Point.java, vividus-extension-ui/src/main/resources/vividus-extension/spring.xml, vividus-extension-ui/src/test/java/org/vividus/ui/converter/PointConverterTests.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/action/AbstractPlaywrightActions.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/action/PlaywrightActions.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/converter/ParametersToPlaywrightActionConverter.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/ActionsSequenceSteps.java, vividus-plugin-web-app-playwright/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/action/PlaywrightActionsTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/converter/ParametersToPlaywrightActionConverterTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/steps/ActionsSequenceStepsTests.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/WebAtomicActionFactories.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/ActionsSequenceStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/WebAtomicActionFactoriesTests.java
Report 
[allure.zip](https://github.com/user-attachments/files/16337030/allure.zip)
=> [plugin-web-app-playwright] Add step to execute actions

docs/modules/plugins/pages/plugin-web-app-playwright.adoc, docs/modules/plugins/partials/common-web-app-browser-steps.adoc, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/BrowserContextProvider.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/UiContext.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/BrowserSteps.java, vividus-plugin-web-app-playwright/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/BrowserContextProviderTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/UiContextTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/steps/BrowserStepsTests.java
Report: 
[allure.zip](https://github.com/user-attachments/files/16377636/allure.zip)
=> [plugin-web-app-playwright] Add step to close browser

vividus-tests/src/main/resources/story/integration/VideoSteps.story
YouTube has started blocking video playback from tests with the message "Sign in to prove you're not a bot". VIVIDUS test site was updated to use custom video, the tests are updated accordingly.
=> [tests] Fix video player tests

vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/MouseActions.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/MouseActionsTests.java
- `waitActions.waitForPageLoad()` already performs check for alert
- `resetContextIfNeeded()` waits for alert as well
=> [plugin-web-app] Remove duplicate check for alert presence

vividus-tests/src/main/resources/data/tables/with-transformer-1.table, vividus-tests/src/main/resources/data/tables/with-transformer-2.table, vividus-tests/src/main/resources/story/integration/TableTransformers.story
=> [tests] Add test to verify order of applying transformers from external tables

vividus-tests/src/main/resources/properties/profile/saucelabs/web/phone/android/profile.properties
This is a removal of leftover from #5520.
=> [tests] Remove redundant capability configuration

vividus-tests/src/main/resources/known-issues.json, vividus-tests/src/main/resources/steps/composite.steps, vividus-tests/src/main/resources/story/integration/LifecycleAfterStoryCompositeSteps.story, vividus-tests/src/main/resources/story/integration/knownissue/Known issues.story
Commits:
[tests] Add test to verify composite steps in After Lifecycle steps block after failed story
JBehave issue - https://jbehave.atlassian.net/browse/JBEHAVE-1605
[tests] Add test to verify known issue status preservation after `GivenStories`
JBehave issue - https://jbehave.atlassian.net/browse/JBEHAVE-1608
=> Add jbehave tests

.github/workflows/gradle.yml, vividus-tests/src/main/resources/properties/environment/system/api/environment.properties, vividus-tests/src/main/resources/story/system/kafka/Kafka.story
CloudKarafka reached End of Life on January 27, 2025: https://www.cloudkarafka.com/blog/end-of-life-announcement.html
=> [tests] Migrate to Kafka broker spin up by GH action
