vividus-http-client/src/main/resources/org/vividus/http/client/spring.xml, vividus-util/src/main/resources/org/vividus/util/spring.xml, vividus/src/main/resources/org/vividus/spring-configuration.xml
Change the separating character between the placeholder variable
and the associated default value from the custom '=' to the default ':'
=> Use default value separator for Spring default values

vividus-plugin-parquet/src/main/java/org/vividus/bdd/expression/ConvertCsvToParquetFileExpressionProcessor.java, vividus-plugin-parquet/src/main/resources/properties/defaults/run.properties, vividus-plugin-parquet/src/main/resources/spring.xml, vividus-plugin-parquet/src/test/java/org/vividus/bdd/expression/ConvertCsvToParquetFileExpressionProcessorTests.java
Configurable with property in Spring expression way:
expression.csv-to-parquet.csv-format=T(org.apache.commons.csv.CSVFormat).DEFAULT
=> Add possibility to use custom CSVFormat in expression processor

build.gradle
Bumps `powermock` from 2.0.2 to 2.0.4.
Updates `powermock` from 2.0.2 to 2.0.4
- [Release notes](https://github.com/powermock/powermock/releases)
- [Changelog](https://github.com/powermock/powermock/blob/release/2.x/docs/changelog.txt)
- [Commits](powermock/powermock@powermock-2.0.2...powermock-2.0.4)
=> Bump powermock from 2.0.2 to 2.0.4

vividus-agent-reportportal/src/main/java/org/vividus/reportportal/config/ReportPortalConfiguration.java, vividus-agent-reportportal/src/main/java/org/vividus/reportportal/listener/AssertionFailureListener.java, vividus-agent-reportportal/src/test/java/org/vividus/reportportal/config/ReportPortalConfigurationTests.java, vividus-agent-reportportal/src/test/java/org/vividus/reportportal/listener/AssertionFailureListenerTests.java, vividus/src/main/java/org/vividus/softassert/AssertionManager.java, vividus/src/test/java/org/vividus/softassert/AssertionManagerTests.java
All EventBus subscribers created as Spring beans are registered automatically via SubscriberRegisteringBeanPostProcessor
=> Remove self-registration of event subscribers

vividus-plugin-db/src/main/java/org/vividus/bdd/steps/db/DatabaseSteps.java, vividus-plugin-db/src/test/java/org/vividus/bdd/steps/db/DatabaseStepsTests.java, vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java, vividus-plugin-rest-api/src/main/java/org/vividus/http/HttpRequestExecutor.java, vividus-plugin-rest-api/src/test/java/org/vividus/http/HttpRequestExecutorTests.java, vividus-util/src/main/java/org/vividus/util/CheckedSupplier.java, vividus-util/src/main/java/org/vividus/util/wait/WaitMode.java, vividus-util/src/main/java/org/vividus/util/wait/Waiter.java, vividus-util/src/test/java/org/vividus/util/wait/WaiterTests.java
Step wording:
When I wait for '$duration' duration retrying $retryTimes times while
data from `$sqlQuery` executed against `$dbKey` matching rows using
`$keys` is equal to data from:$table
=> [plugin-db] Add step to wait until data received from SQL request is equal to data from table

vividus-plugin-rest-api/src/main/java/org/vividus/http/HttpClientInterceptor.java, vividus-plugin-rest-api/src/test/java/org/vividus/http/HttpClientInterceptorTests.java
https://github.com/apache/httpcomponents-client/commit/09cefc2b8970eea56d81b1a886d9bb769a48daf3
=> Fix to use org.apache.http.HttpEntity.writeTo(OutputStream) to avoid issues with data size limitation

.travis.yml
*.lock files are created by Gradle workers for synchronized access to the caches
=> [Travis CI] Delete all *.lock files before caching

vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/JsonResponseValidationStepsTests.java, vividus-tests/src/main/resources/story/integration/JsonResponseValidationSteps.story, vividus-util/src/main/java/org/vividus/util/function/CheckedRunnable.java, vividus-util/src/main/java/org/vividus/util/wait/Waiter.java, vividus-util/src/test/java/org/vividus/util/wait/WaiterTests.java
The step exeutes sub-steps and waits for a specified amount of time
until HTTP response body contains an element by the specified JSON path.
=> [plugin-rest-api] Add generic step to wait for JSON element presence

.travis.yml, vividus-tests/src/main/resources/properties/configuration.properties
Gradle task `testVividusInitialization` uses default test project configuration
(configuration.properties) to check that Spring context can start successfully.
`integration` environment declared in `vividus-tests` requires `PATH` and `JAVA_HOME`
environment variables to be set. But `PATH` variable may have different case on
Windows OS which may lead to build failures. This CL changes default environment
to empty and sets environment for integration tests in CI config.
Fixes #276
=> [tests] Ensure build is not affected by integration tests configuration

vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/PageStepsTests.java
Java 9 API `Set.of` returns `Set` which doesn't guarantee the iteration order.
To ensure the order of elements `LinkedHashSet` is used now.
=> [plugin-web-app] Unit tests: fix flaky test coverage

vividus-bdd-engine/src/main/java/org/vividus/bdd/context/BddRunContext.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/context/BddRunContextTests.java
jbehave-junit-runner builds JUnit execution tree before the actual
execution. Also it knows nothing about Vividus batches. As result
when BDD stories are run NPE is thrown, because no batch is running.
This is a fix for regression bug introduced in e083434 (see
EmbedderControlsProvider.getDefault()).
=> Fix NPE when stories are run using JUnit runner

vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/IJavascriptActions.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/JavascriptActions.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/MouseActions.java, vividus-plugin-web-app/src/main/resources/org/vividus/ui/web/action/scroll-element-into-viewport-center.js, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/JavascriptActionsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/MouseActionsTests.java
Sticky headers and footers may overlap elements to click and as result
unexpected exceptions may be thrown (e.g. "Other element would receive the click").
Scroll of the element into the viewport center eliminates this issue
and guarantees that the expected element will receive the click.
Fixes #330
=> [plugin-web-app] Scroll element into viewport center before click

vividus-plugin-csv/src/main/java/org/vividus/bdd/steps/csv/CsvSteps.java, vividus-plugin-csv/src/main/java/org/vividus/bdd/transformer/CsvTableTransformer.java, vividus-plugin-csv/src/main/java/org/vividus/csv/CsvReader.java, vividus-plugin-csv/src/main/resources/spring.xml, vividus-plugin-csv/src/test/java/org/vividus/bdd/transformer/CsvTableTransformerTest.java, vividus-plugin-csv/src/test/java/org/vividus/csv/CsvReaderTests.java, vividus-plugin-csv/src/test/resources/org/vividus/csv/unittest-escaped.csv, vividus-tests/src/main/resources/data/csv.csv, vividus-tests/src/main/resources/properties/suite/integration/suite.properties, vividus-tests/src/main/resources/story/integration/TableTransformers.story
The char is used to escape special characters in values, may be `#{null}` to disable.
New property: `csv.escape-char`. Default value is `#{null}`
=> [plugin-csv] Add ability to configure CSV escape char

vividus-bdd-engine/src/main/java/org/vividus/bdd/BatchedEmbedder.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/BatchedEmbedderTests.java
JBehaveJUnitRunner may initialize story manager with default PerformableTree and
EmebedderControls, so story manager should be re-created before actual batch execution
Issues fixed by this change:
- Fixes #376 (root cause: batch embedder controls are ignored by story manager)
- Warnings like
```
2020-03-13 18:06:25,876 SpringContextShutdownHook WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
```
The root cause of this warning is skipped reporting of `AfterStories` when single batch is used. (Allure report is generated in `AfterStories` by default or in JVM shutdown hook in case of premature end of test execution. When Allure JVM shutdown hook is triggered, Log4j JVM hook is already finished and Log4j is shutdown, as result Allure reporter can't …
=> Recreate story manager right before batch execution

vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties
The default value of 10 s timeout brings into the picture "10s wait after a click" by default
=> Do not wait for alert by default

vividus-plugin-rest-api/build.gradle, vividus-util/build.gradle
We can't completely exclude `json-smart` library, because it's
explicitly referenced in internal API of `json-path` library:
https://github.com/json-path/JsonPath/blob/master/json-path/src/main/java/com/jayway/jsonpath/internal/filter/ValueNodes.java#L150-L151
The exclusion causes the errors like:
`java.lang.ClassNotFoundException: net.minidev.json.parser.ParseException`
=> Remove exclusion of json-smart library

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/WebUiVividusSetupSteps.java, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/WebUiVividusSetupStepsTests.java
The browser is resized on WebDriverCreate event (see BrowserWindowSizeListener).
Resizing before each scenario doesn't make much sense, since it could be managed
by users and cases when browser window size is changed during test execution are
very rare.
=> [plugin-web-app] Stop resizing browser before each scenario

vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java, vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/JsonResponseValidationStepsTests.java, vividus-tests/src/main/resources/known-issues.json, vividus-tests/src/main/resources/story/integration/JsonResponseValidationSteps.story
JSON wait steps throwed exception
"java.lang.IllegalArgumentException: json string can not be null or empty"
in case of empty HTTP response body (HTTP "204 NO CONTENT"). This exception
stooped scenario execution and marked it as broken. The changes from this
commit add graceful handling of such cases and record failed asssertion
(which also can be marked as knownn issue if it's required)
=> [plugin-rest-api] Fix wait steps to fail assertion instead of exception

vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java, vividus-tests/src/main/resources/story/integration/JsonResponseValidationSteps.story
JSON standard doesn't specify int and float types, there is just a number: https://tools.ietf.org/html/rfc8259#section-6.
However JsonUnit follows another approach during [JSON numbers comparison](https://github.com/lukas-krecan/JsonUnit#numbers):
> If the type differs, the number is different. So 1 and 1.0 are different (int vs. float)
However the ignorance of number type can be achieved by setting the numerical comparison tolerance to `0` (it's `null` by default)
=> [plugin-rest-api] Ignore number types at JSON comparison

.github/workflows/gradle.yml
Previously the run for each platform published the results to SonarQube, but it's redundant, since each publishing overrode the results from another platforms. Now the results are published from Ubuntu only.
=> [Github Actions] Publish results to SonarQube once

.github/workflows/gradle.yml
*.w3schools.com certificate is expired, need to ignore the error
to make integration tests passed
=> [GithubActions] Ignore certificate errors for Integration tests

vividus-plugin-web-app/src/main/resources/org/vividus/ui/web/action/scroll-element-into-viewport-center.js
There are use-cases when it's required to check browser console log
to verify the application works as expected. The console errors from
vividus brings unexpected useless noise here.
=> [plugin-web-app] Swallow error quietly in case of unsuccessful scroll

vividus-plugin-web-app/src/main/resources/org/vividus/ui/web/action/scroll-to-end-of-page.js
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY
`window.scrollY` is a double-precision floating-point value. When display scale on Windows OS is different from 100%, then the returned value may contain a decimal component.
Fixes #486
=> [plugin-web-app] Round window.scrollY at page scroll

.github/workflows/gradle.yml
*.w3schools.com certificate was renewed, no need to ignore certificate errors in  the integration tests
=> [GithubActions] Stop accepting insecure certificates

vividus-util/src/main/java/org/vividus/util/UriUtils.java, vividus-util/src/test/java/org/vividus/util/UriUtilsTests.java
https://bugs.openjdk.java.net/browse/JDK-8179507
https://stackoverflow.com/questions/43375916/urldecoder-is-converting-into-space:
"According to HTML URL Encoding Reference:
URLs cannot contain spaces. URL encoding normally replaces a space with a plus (+) sign or with %20."
=> Fix handling of plus character in URL

vividus/src/integrationTest/java/org/vividus/configuration/BeanFactoryIntegrationTests.java, vividus/src/integrationTest/resources/overriding.properties, vividus/src/integrationTest/resources/properties/configuration.properties, vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java
The values for properties:
- configuration.profile
- configuration.profiles
- configuration.environments
- configuration.suite
can include placeholders for another properties now.
The properties used as placeholders may be declared in:
- configuration.properties
- overriding.properties
Closes #550
=> Add ability to use placeholders in configuration properties

vividus-plugin-web-app/src/main/resources/org/vividus/ui/web/action/scroll-element-into-viewport-center.js
Script scrolling element into viewport center was executed endlessly with timeout 500 seconds;
The strategy brokes the tests for example in the case when the user clicked anchor link, the page has never scrolled to the anchor because of the script;
New approach: Add scroll waiting listener -> Wait for the scroll end -> remove listener -> call selenium exit callback
=> [plugin-web-app] Fix scrolling script

vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/CookieManager.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/CookieManagerTests.java
If the cookie domain does not equal the exact host,
`org.apache.http.cookie.ClientCookie.DOMAIN_ATTR` must be set.
For example: previously cookies with domain '.imdb.com' were
not passed if URL was 'https://www.imdb.com/', only cookies
with domain 'www.imdb.com' were passed.
See implementation details:
`org.apache.http.impl.cookie.BasicDomainHandler#domainMatch`
More information:
- https://hc.apache.org/httpcomponents-client-ga/tutorial/html/statemgmt.html
- https://stackoverflow.com/a/31428811/2067574
- https://stackoverflow.com/a/31428794/2067574
=> [plugin-web-app] Enable cookie subdomain matching to host

.github/workflows/gradle.yml
Checkout action introduced number of improvements simplifying checkout of submodules and fetch of all history for all tags and branches:
- https://github.com/actions/checkout/pull/258
- https://github.com/actions/checkout/pull/173
=> [GithubActions] Simplify checkout action

vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureReportGenerator.java, vividus-allure-adaptor/src/test/java/org/vividus/bdd/report/allure/adapter/AllureReportGeneratorTests.java
If no test is run, then allure results directory is not created.
That leads to exception like:
```
java.nio.file.NoSuchFileException: .../allure-results/categories.json
```
These changes aim to fix this issue by ensuring that allure results directory exists before the report generation start.
=> [allure-adaptor] Fix report generation when no test was run

vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ParameterConvertersDecorator.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/ParameterConvertersDecoratorTests.java, vividus-tests/src/main/resources/story/integration/VariableTests.story
The previous fix #700 was not good-enough, since it wasn't able to handle circular variable references in complex expressions when the value to process had prefix/postfix before/after the actual variable. Since there is no way to parse and detect circular variables, this solution introduces max nested level of variables (value is 16), if max level is reached, then result is a one cycle of resolutions.
=> [bdd-engine] Fix resolving of circular variable references

docs/modules/plugins/pages/plugin-datetime.adoc, vividus-plugin-datetime/src/main/java/org/vividus/bdd/expression/DateExpressionProcessor.java, vividus-plugin-datetime/src/test/java/org/vividus/bdd/expression/DateExpressionProcessorTests.java, vividus-tests/src/main/resources/story/integration/JsonResponseValidationSteps.story
See for examples: https://stackoverflow.com/questions/51141995/why-does-formatting-a-date-using-datetimeformatter-with-a-yyyy-pattern-give-the
=> Use year-of-era instead of week-based-year in datetime formats

vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ParameterConvertersDecorator.java
The fix for #732 provided in #733 included the check for ExamplesTable emptiness.
The issue was caused by bug in JBEHAVE: https://jbehave.atlassian.net/browse/JBEHAVE-1412.
JBehave bug was fixed and Vividus was updated to use a new version in #746.
Thus the check for ExamplesTable emptiness became redundant.
=> [bdd-engine] Remove redundant ExamplesTable emptiness check

docs/modules/plugins/nav.adoc, docs/modules/plugins/pages/plugin-ssh.adoc, vividus-plugin-ssh/src/main/java/org/vividus/ssh/ServerConfiguration.java, vividus-plugin-ssh/src/main/java/org/vividus/ssh/exec/SshExecutor.java, vividus-plugin-ssh/src/main/java/org/vividus/ssh/sftp/SftpExecutor.java, vividus-plugin-ssh/src/test/java/org/vividus/ssh/exec/SshExecutorTests.java, vividus-plugin-ssh/src/test/java/org/vividus/ssh/sftp/SftpExecutorTests.java
Closes #998 
New property:
```properties
ssh.server.<key>.pseudo-terminal-enabled
```
Values: 
- `true`
- `false` (default)
=> [plugin-ssh] Add option to enable pseudo-terminal

vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties
When custom Selenium Grid is used, the empty `browserVersion` capability blocks search of the requested browser node
=> [plugin-web-app] Remove empty 'browserVersion' capability

docs/modules/plugins/partials/generic-ui-steps.adoc, vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/GenericSetVariableSteps.java, vividus-extension-selenium/src/main/java/org/vividus/ui/action/ElementActions.java, vividus-extension-selenium/src/main/resources/spring.xml, vividus-extension-selenium/src/test/java/org/vividus/bdd/steps/ui/GenericSetVariableStepsTests.java, vividus-plugin-mobile-app/src/main/java/org/vividus/ui/mobile/action/MobileAppElementActions.java, vividus-plugin-mobile-app/src/main/resources/spring.xml, vividus-plugin-mobile-app/src/test/java/org/vividus/ui/mobile/action/MobileAppElementActionsTests.java, vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/SetVariableSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/IWebElementActions.java, vividus-plugin-web-app/src/main/resources/steps/defaults/setcontext.steps, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/SetVariableStepsTests.java, vividus-tests/src/main/resources/story/integration/SetVariableSteps.story
Needs be fixed for 0.3.0 https://github.com/vividus-framework/vividus/issues/1032
=> [extension-selenium] Add set variable steps

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java, vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/TakeScreenshotOnFailure.java, vividus-extension-selenium/src/main/resources/properties/defaults/run.properties, vividus-extension-selenium/src/main/resources/spring.xml, vividus-extension-selenium/src/test/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitorTests.java, vividus-plugin-web-app/src/main/java/org/vividus/proxy/steps/ProxySteps.java, vividus-plugin-web-app/src/main/resources/spring.xml
Closes #915 
Provide possibility to debug API scenarios (show screenshot in Allure report when step fails)
Use 
screenshot.on-failure.debug-modes=proxy
=> Fix915 : Provide possibility to debug API scenarios

vividus-tests/src/main/resources/story/integration/ResourceCheckSteps.story
The URL from https://www.example.com/ may behave differently, so we need to use something more stable: Vividus test site
=> [tests] Use Vividus test site for ResourceCheckSteps tests

vividus-tests/src/main/resources/properties/suite/grid/suite.properties
The default number of threads per batch is `1`
=> [tests] Remove redundant property

vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/chrome/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/edge/chromium/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/edge/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/firefox/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/iexplore/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/opera/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/safari/profile.properties
The previous default value of screen-resolution capability (1920x1080) is not universal, e.g. it's not applicable for MacOS platform on SauceLabs.
The 'screen-resolution' fix includes:
- setting of the default value (1920x1080) for Chrome, Edge, Firefox, IE profiles
- setting of the empty value for Safari profile (the empty value will result in default value for the concrete Selenium Grid implementation, e.g. it's 1024x768 for SauceLabs now)
=> [plugin-web-app] Fix configuration of 'screen-resolution' capability

vividus-extension-selenium/src/main/java/org/vividus/proxy/Proxy.java, vividus-extension-selenium/src/test/java/org/vividus/proxy/ProxyTests.java
=> [extension-selenium] Gracefully handle interactions with non-started proxy

vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/VariableResolver.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/VariableResolverTests.java, vividus-tests/src/main/resources/story/integration/VariableTests.story
=> [bdd-engine] Fix variables resolution for the values with preceding `}`

docs/modules/commons/pages/vividus-steps.adoc, vividus-tests/src/main/resources/story/integration/ExecutableSteps.story, vividus-tests/src/main/resources/story/system/AWS - DynamoDB.story, vividus-util/src/main/java/org/vividus/util/wait/MaxTimesBasedWaiter.java, vividus-util/src/test/java/org/vividus/util/wait/MaxTimesBasedWaiterTests.java, vividus/src/main/java/org/vividus/bdd/steps/ExecutableSteps.java, vividus/src/test/java/org/vividus/bdd/steps/ExecutableStepsTests.java
=> [vividus] Add generic while-like step with iteration delays

vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/ScrollSteps.java, vividus-plugin-web-app/src/main/resources/steps/defaults/scroll.steps, vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/ScrollStepsTests.java, vividus-tests/src/main/resources/story/integration/ScrollStepsTests.story
Removed steps (deprecated in 0.2.1):
- `When I scroll to the start of the context`
- `When I scroll to the end of the context`
- `When I scroll to the start of the page`
- `When I scroll to the end of the page`
Replacement:
- `When I scroll context to $scrollDirection edge`
=> [plugin-web-app] Remove deprecated non-generic steps scrolling vertically

vividus-plugin-html/src/main/resources/steps/defaults/composite.steps, vividus-tests/src/main/resources/story/integration/HtmlSteps.story
Removed step (deprecated in 0.2.1): Then HTML `$html` contains element by CSS selector `$cssSelector`
Replacement: Then number of elements found by CSS selector `$cssSelector` in HTML `$html` is $comparisonRule `$quantity`
=> [plugin-html] Remove deprecated step verifying if HTML contains element

vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/safari/profile.properties
The pre-run executable can only be used for Safari versions up to and including 10.x.
=> [plugin-web-app] Remove not working prerun from web safari profile

vividus-plugin-web-app/src/main/resources/steps/defaults/window.steps, vividus-tests/src/main/resources/story/integration/SetContextStepsTests.story
Removed steps (deprecated in `0.2.2`):
```
- When I switch to a window with the name '$windowName'
- When I switch to a window with the name containing '$windowPartName'
```
Replacement:
```
- When I switch to window with title that $stringComparisonRule `$title`
```
=> [plugin-web-app] Remove deprecated steps switching to window

vividus-plugin-web-app/src/main/resources/steps/defaults/composite.steps, vividus-tests/src/main/resources/story/integration/ElementStepsTests.story
Removed step (deprecated in 0.2.2):
```gherkin
When I select an element with the '$attributeType'='$attributeValue' and upload the file '$filePath'
```
Replacement:
```gherkin
When I select element located `$locator` and upload file `$filePath`
```
=> [plugin-web-app] Remove deprecated step uploading file

vividus-plugin-web-app/src/main/resources/steps/defaults/frames.steps, vividus-tests/src/main/resources/story/integration/ElementStepsTests.story, vividus-tests/src/main/resources/story/integration/ImageStepsTests.story, vividus-tests/src/main/resources/story/integration/LinkStepsTests.story, vividus-tests/src/main/resources/story/integration/SetContextStepsTests.story
Removed steps (deprecated in `0.2.3`):
```gherkin
When I switch to a frame by the xpath '$xpath'
When I switch to a frame with the attribute '$attributeType'='$attributeValue'
When I switch to a frame number '$numberValue' with the attribute '$attributeType'='$attributeValue'
```
Replacement:
```gherkin
When I switch to frame located `$locator`
```
=> [plugin-web-app] Remove deprecated steps switching to frame

vividus-plugin-web-app/src/main/resources/steps/defaults/page.steps, vividus-tests/src/main/resources/story/integration/PageStepsTests.story
Removed step (deprecated in `0.2.3`):
```gherkin
Then the page is scrolled to an element with the attribute '$attributeType'='$attributeValue'
```
Replacement:
```gherkin
Then page is scrolled to element located `$locator`
```
=> [plugin-web-app] Remove deprecated step checking page scroll position

vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java
Error:
```
2021-01-05 09:59:04,620 [batch-1-thread-1] ERROR com.google.common.eventbus.EventBus.default - Exception thrown by subscriber method onLinkPublish(org.vividus.reporter.event.LinkPublishEvent) on subscriber AllureStoryReporter[allureReportGenerator=org.vividus.bdd.report.allure.AllureReportGenerator@21848c8d,allureRunContext=org.vividus.bdd.report.allure.AllureRunContext@25c0aaf3,batchStorage=org.vividus.bdd.batch.BatchStorage@40b14c8f,bddRunContext=org.vividus.bdd.context.BddRunContext@5bfd43df,lifecycle=io.qameta.allure.AllureLifecycle@5e184cc9,testContext=org.vividus.testcontext.ThreadedTestContext@7e2fe2cb,verificationErrorAdapter=org.vividus.bdd.report.allure.adapter.VerificationErrorAdapter@34301cb5,delegates={VariableStoryReporter[bddVariableContext=org.vividus.bdd.context …
```
=> [allure-adaptor] Make Allure link comparison null-safe

vividus-plugin-web-app/src/main/resources/steps/defaults/composite.steps, vividus-tests/src/main/resources/story/integration/ActionSteps.story, vividus-tests/src/main/resources/story/integration/DragAndDropSteps.story, vividus-tests/src/main/resources/story/integration/ElementStepsTests.story, vividus-tests/src/main/resources/story/integration/ImageStepsTests.story, vividus-tests/src/main/resources/story/integration/LinkStepsTests.story, vividus-tests/src/main/resources/story/integration/ScrollStepsTests.story, vividus-tests/src/main/resources/story/system/ApplitoolsVisualStepsTests.story, vividus-tests/src/main/resources/story/system/VisualStepsTests.story
Removed step (deprecated in `0.2.3`):
```gherkin
When I change context to an element by $locator
```
Replacement:
```gherkin
When I change context to element located `$locator`
```
=> [plugin-web-app] Remove deprecated step changing context to element

vividus-tests/src/main/resources/story/integration/LinkStepsTests.story
The test is failed due to changes on the 3-rd party web site.
=> [tests] Fix failing integration test for links steps

docs/modules/commons/pages/expressions.adoc, vividus-tests/src/main/resources/story/integration/Expressions.story, vividus/src/main/java/org/vividus/bdd/expression/StringsExpressionProcessor.java, vividus/src/test/java/org/vividus/bdd/expression/StringsExpressionProcessorTests.java
=> [vividus] Add Vividus expression: toBase64Gzip

vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java
The cloud test links are published using event-driven approach: #1216, #1249, #1263, #1265
The outdated placeholder is not used.
=> [allure-adaptor] Remove outdated placeholder for cloud test links

vividus-analytics/src/main/resources/properties/defaults/default.properties
The default properties encrypted with the default password can't be decrypted when the custom encryption password is used, in other words it completely blocks usage of the custom password
=> [analytics] Use non-encrypted tracking ID

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/DeviceSteps.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/steps/DeviceStepsTests.java, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
=> [plugin-mobile-app] Add press key step

vividus-extension-visual-testing/src/main/java/org/vividus/visual/bdd/AbstractVisualSteps.java, vividus-extension-visual-testing/src/test/java/org/vividus/visual/bdd/VisualStepsTests.java, vividus-plugin-accessibility/src/main/java/org/vividus/accessibility/AccessibilitySteps.java, vividus-plugin-accessibility/src/test/java/org/vividus/accessibility/AccessibilityStepsTests.java, vividus-plugin-applitools/src/main/java/org/vividus/visual/eyes/VisualTestingSteps.java, vividus-plugin-visual/src/main/java/org/vividus/visual/VisualSteps.java, vividus-plugin-visual/src/test/java/org/vividus/visual/VisualStepsTests.java
=> Fix visual

vividus/src/main/resources/log4j2.xml
=> [vividus] Stop logging debug messages from soft assert into allure appender

docs/antora.yml, docs/modules/guides/nav.adoc, docs/modules/guides/pages/execute-sql-against-csv.adoc, vividus-tests/build.gradle, vividus-tests/src/main/resources/properties/environment/integration/envinroment.properties, vividus-tests/src/main/resources/story/integration/CSV.story
=> [tests][docs] Execute SQL against CSV resources

.github/workflows/gradle.yml
This is a workaround for https://github.com/codecov/codecov-action/issues/330 (https://community.codecov.com/t/intermittent-unable-to-locate-build-via-github-actions-api/2936).
The error is:
```
->  Pinging Codecov
https://codecov.io/upload/v4?package=github-action-1.0.2&token=secret&branch=execute-sql-against-csv&commit=d6906de616f61371400cda154be88c4a61d45be2&build=914910056&build_url=http%3A%2F%2Fgithub.com%2Fvividus-framework%2Fvividus%2Factions%2Fruns%2F914910056&name=&tag=&slug=vividus-framework%2Fvividus&service=github-actions&flags=&pr=1697&job=Vividus%20CI&cmd_args=n,F,Q,Z,C
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
404
==> Uploading to Codecov
% Total …
```
=> [CI] Configure Codecov action to use token 

vividus-plugin-rest-api/src/main/java/org/vividus/http/HttpClientInterceptor.java, vividus-plugin-rest-api/src/test/java/org/vividus/http/HttpClientInterceptorTests.java
=> [plugin-rest-api] Fix MIME-type detection for HTTP requests

vividus-plugin-db/src/main/java/org/vividus/bdd/steps/db/DatabaseSteps.java, vividus-plugin-db/src/test/java/org/vividus/bdd/steps/db/DatabaseStepsTests.java
Affected steps:
```gherkin
Then `$data` matching rows using `$keys` from `$dbKey` is equal to data from:$table
When I wait for '$duration' duration retrying $retryTimes times while data from `$sqlQuery` executed against `$dbKey` is equal to data from:$table
```
Before:
After:
=> [plugin-db] Fix source JDBC url in queries statistic

vividus-reporter/src/main/resources/org/vividus/reporter/spring.xml
https://freemarker.apache.org/docs/dgui_misc_autoescaping.html
Before:
After:
=> [reporter] Configure Freemarker output as HTML

.github/workflows/gradle.yml
codecov/codecov-action#330
https://docs.codecov.io/docs/about-the-codecov-bash-uploader#upload-token:
> If you have a public project on TravisCI, CircleCI, AppVeyor, Azure Pipelines, or GitHub Actions an upload token is not required.
=> [CI] Remove workaround for Codecov action issue

vividus-plugin-db/src/main/resources/data-sources-statistics.ftl, vividus-reporter/src/main/resources/org/vividus/reporter/spring.xml, vividus-reporter/src/main/resources/templates/maps-comparison-table.ftl
HTML attachements for report may contain also: JS, CSS. Also they may include logic of constructing HTML using Freemarker functions. Moreover there are templates which are out of our control: `allure-jsonunit-2.14.0.jar!/tpl/diff.ftl`.
As result the default output format (HTML) can't be applied and should be disabled.
=> Do not consider Freemarker output as HTML for all attachments by default

vividus/src/main/java/org/vividus/bdd/steps/ExecutableSteps.java, vividus/src/test/java/org/vividus/bdd/steps/ExecutableStepsTests.java
The threshold is still required to ensure users will not be able to run an infinite loop. However 50 is too low threshold for backend/data tests, so it's increased to 1000.
=> [vividus] Increase exectuion number threshold from 50 to 1000

vividus-bdd-engine/src/main/java/org/vividus/bdd/log/LoggingEmbedderMonitor.java, vividus-bdd-engine/src/test/java/org/vividus/bdd/log/LoggingEmbedderMonitorTests.java
Skip logging of messages like the following one:
```
2021-08-16 18:13:58,998 [main] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - Using executor service java.util.concurrent.ThreadPoolExecutor@774c5e5c[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
```
since they don't bring any value
=> [bdd-engine] Skip logging of used executor service

vividus-tests/src/main/resources/properties/suite/integration/suite.properties, vividus-tests/src/main/resources/story/integration/VariableTests.story, vividus-util/src/main/java/org/vividus/util/property/PropertyParser.java, vividus-util/src/test/java/org/vividus/util/property/PropertyParserTests.java
```
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
at org.vividus.util.property.PropertyParser.lambda$filterProperties$8(PropertyParser.java:113)
at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484 …
```
=> [util] Consider vividus config properties as strings

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/model/SwipeDirection.java, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/TouchSteps.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java, vividus-plugin-mobile-app/src/test/java/io/appium/java_client/TouchActionsTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/model/SwipeDirectionTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/steps/TouchStepsTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/selenium/mobileapp/screenshot/NativeHeaderAwareCoordsProviderTests.java, vividus-tests/src/main/resources/data/tables/system/mobile_app/locators/android.table, vividus-tests/src/main/resources/data/tables/system/mobile_app/locators/ios.table, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
=> [plugin-mobile-app] Add possibility to swipe the context

.github/workflows/gradle.yml
https://changelog.saucelabs.com/en/sauce-connect-proxy-version-30JTvzO0F:
Sauce Connect Proxy Version 4.7.0
> “--proxy-localhost” boolean flag is added to support proxying upstream requests to localhost. This is no longer the default behavior
=> [CI] Fix system tests broken by new SauceConnect

.github/workflows/gradle.yml
Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from `adopt` to `temurin` to keep receiving software and security updates. More details in the Good-bye AdoptOpenJDK post: https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/.
=> [CI] Use `temurin` instead of deprecated `adopt`

docs/modules/commons/pages/vividus-steps.adoc, vividus-tests/src/main/resources/story/integration/VariableTests.story, vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java, vividus/src/test/java/org/vividus/bdd/steps/BddVariableStepsTests.java
=> [vividus] Enable dotall mode for step asserting against regex

docs/modules/ROOT/pages/tests-configuration.adoc, vividus-soft-assert/build.gradle, vividus-soft-assert/src/main/java/org/vividus/softassert/formatter/AssertionFormatter.java, vividus-soft-assert/src/main/java/org/vividus/softassert/issue/KnownIssueIdentifier.java, vividus-soft-assert/src/main/java/org/vividus/softassert/model/KnownIssue.java, vividus-soft-assert/src/test/java/org/vividus/softassert/formatter/AssertionFormatterTests.java, vividus-soft-assert/src/test/java/org/vividus/softassert/issue/KnownIssueCheckerTests.java, vividus-soft-assert/src/test/java/org/vividus/softassert/model/KnownIssueTests.java, vividus-tests/src/main/resources/known-issues.json
=> [soft-assert] Add ability to set description for known issue

vividus-extension-selenium/src/main/java/org/vividus/ui/util/LocatorConversionUtils.java, vividus-extension-selenium/src/test/java/org/vividus/ui/util/LocatorConversionUtilsTests.java
=> [vividus-extension-selenium] Fix regex for locator converter

vividus/src/main/java/org/vividus/runner/BddStepsCounter.java, vividus/src/test/java/org/vividus/runner/BddStepsCounterTests.java
Also this change will help to avoid problems happened in PR like #2015: https://github.com/vividus-framework/vividus/pull/2015/checks?check_run_id=3768388013:
```
> Task :vividus-tests:countSteps
2021-10-01 14:51:37,548 [main] INFO  org.vividus.report.MetadataLogger - 
_   _______   _________  __  ______
| | / /  _/ | / /  _/ _ \/ / / / __/
| |/ // / | |/ // // // / /_/ /\ \  
|___/___/ |___/___/____/\____/___/  
2021-10-01 14:51:37,639 [main] INFO  org.vividus.configuration.ConfigurationResolver - Loading properties from /defaults
2021-10-01 14:51:37,652 [main] INFO  org.vividus.configuration.ConfigurationResolver - Loading properties from /
2021-10-01 14:51:37,692 [main] INFO  org.vividus.configuration.ConfigurationResolver - Loading properties from /profile/web/headless/chrome …
```
=> [vividus] Skip `ExamplesTable`-s loading while counting used steps

build.gradle
Fixes #2016
This reverts commit 1c0657f0f7dca7ef46a0e1d95b783d1995ad03c8.
Allure 2.15.0 relies on Tika 2.X which is incompatible with ReportPortal client 4.X.
=> Revert "Bump Allure from 2.14.0 to 2.15.0 (#1968)"

vividus-plugin-rest-api/src/main/resources/spring.xml
=> [plugin-rest-api] Do not publish request/response details for resource validation

vividus-plugin-web-app/src/main/java/org/vividus/proxy/steps/ProxySteps.java, vividus-plugin-web-app/src/test/java/org/vividus/proxy/steps/ProxyStepsTests.java
The comment attribute from [(spec)](http://www.softwareishard.com/blog/har-12-spec/#content) in HarPostData is not used anywhere
=> [plugin-web-app] Delete comment attribute from proxy request body

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/proxy/model/HttpMessagePart.java, vividus-plugin-web-app/src/main/java/org/vividus/proxy/steps/ProxySteps.java, vividus-plugin-web-app/src/test/java/org/vividus/proxy/model/HttpMessagePartTests.java, vividus-plugin-web-app/src/test/java/org/vividus/proxy/steps/ProxyStepsTests.java, vividus-tests/src/main/resources/story/integration/ProxyStepsTests.story
=> [plugin-web-app] Add ability to capture http response in proxy

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/ApplicationSteps.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/ApplicationActions.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/steps/ApplicationStepsTests.java, vividus-plugin-mobile-app/src/test/java/org/vividus/mobileapp/action/ApplicationActionsTests.java, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
Closes https://github.com/vividus-framework/vividus/issues/2073
=> [plugin-mobile-app] Add steps to terminate and reinstall application

vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
The test fackiness is caused by different order of web view names returned by appium server
=> [tests] Fix flacky web view test

vividus-plugin-web-app/src/main/java/org/vividus/ui/web/listener/WebSourceCodePublishingOnFailureListener.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/listener/WebSourceCodePublishingOnFailureListenerTests.java
The NPE is thrwon when search context is `null`:
```
java.lang.NullPointerException: null
at org.vividus.ui.web.listener.WebSourceCodePublishingOnFailureListener.getSourceCode(WebSourceCodePublishingOnFailureListener.java:56) ~[vividus-plugin-web-app-0.3.11.jar:0.3.11]
at org.vividus.ui.listener.AbstractSourceCodePublishingOnFailureListener.onAssertionFailure(AbstractSourceCodePublishingOnFailureListener.java:49) ~[vividus-extension-selenium-0.3.11.jar:0.3.11]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) …
```
=> [plugin-web-app] Fix NPE in web source code on-failure publisher

docs/modules/plugins/pages/plugin-mobile-app.adoc, vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/SetContextSteps.java, vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/steps/SetContextStepsTests.java
The order of web views returned by Appium is not reliable.
- For Android platform the web views are retrieved by parsing UNIX socket names from /proc/net/unix.
- For iOS platform the web views are considered as separate processes within the active application.
Sorting the web view by Inode number for android or PID for iOS doesn't seem logical for end users and as practice shows the order is not guaranteed.
=> [plugin-mobile-app] Deprecate web view switching by index

docs/modules/plugins/pages/plugin-web-app.adoc, docs/modules/plugins/partials/proxy-steps.adoc
Fixed warnings:
```
asciidoctor: WARNING: skipping reference to missing attribute: har-attached
asciidoctor: WARNING: skipping reference to missing attribute: har-attached
asciidoctor: WARNING: skipping reference to missing attribute: url
asciidoctor: WARNING: skipping reference to missing attribute: query
asciidoctor: WARNING: skipping reference to missing attribute: response
asciidoctor: WARNING: skipping reference to missing attribute: url
asciidoctor: WARNING: skipping reference to missing attribute: query
asciidoctor: WARNING: skipping reference to missing attribute: response
```
=> [docs] Fix warnings in substitutions

vividus-http-client/src/main/java/org/vividus/http/keystore/KeyStoreFactory.java, vividus-http-client/src/test/java/org/vividus/http/keystore/KeyStoreFactoryTests.java
```
Exception in thread "main" org.vividus.jira.JiraConfigurationException: java.lang.IllegalStateException: java.io.EOFException
at org.vividus.jira.JiraClientProvider.getClient(JiraClientProvider.java:169)
at org.vividus.jira.JiraClientProvider.getByFirst(JiraClientProvider.java:157)
at org.vividus.jira.JiraClientProvider.getClientByProjectKey(JiraClientProvider.java:131)
at org.vividus.jira.JiraClientProvider.getByProjectKey(JiraClientProvider.java:120)
at org.vividus.jira.JiraFacade.lambda$getProject$0(JiraFacade.java:77)
at org.vividus.jira.JiraFacade.getJiraEntity(JiraFacade.java:96)
at org.vividus.jira.JiraFacade.getProject(JiraFacade.java:77)
at org.vividus.zephyr.facade.ZephyrFacade.prepareConfiguration(ZephyrFacade.java:81)
at …
```
=> [http-client] Restore default key factory behaviour

vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java, vividus-plugin-mobile-app/src/test/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManagerTests.java
Received exception in [CI example](https://github.com/vividus-framework/vividus/runs/4689829224?check_suite_focus=true#step:21:2124)
=> [plugin-mobile-app] Handle the exception if status bar height from session details is null

vividus-tests/src/main/resources/data/tables/system/mobile_app/locators/android.table, vividus-tests/src/main/resources/data/tables/system/mobile_app/locators/ios.table, vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
[Error example ](https://github.com/vividus-framework/vividus/runs/4700109279?check_suite_focus=true#step:25:1973)
Reason - sometimes QR scan is started before menu is disappeared
=> [tests] Add wait step in MobileApp QR code scan step integration test

vividus-tests/src/main/resources/story/ui/ScreenshotTakingStepsTests.story
Paths on Windows contain backslash \ which is an escape character for Groovy single-quoted strings, it causes errors like:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 1: Unexpected character: '\'' @ line 1, column 35.
def files = java.nio.file.Path.of('D:\a\vividus\vividus\vividus-tests\output/screenshots').toFile()?.listFiles(); return files?.length?:0
^
1 error
```
The solution is to use dollar slashy string to avoid the necessity to escape backslashes and/or forward slashes
=> [tests] Fix execution of integration tests on Windows

vividus/build.gradle, vividus/src/main/java/org/vividus/expression/StringsExpressionProcessor.java
It seems [`Java Faker`](https://github.com/DiUS/java-faker) project is not actively maintained, while [`Data Faker`](https://github.com/datafaker-net/datafaker) project demonstrates a good start, see https://github.com/DiUS/java-faker/issues/681#issuecomment-1003178496.
=> [vividus] Switch from `Java Faker` to its fork `Data Faker`

vividus/src/main/java/org/vividus/StatusStoryReporter.java, vividus/src/test/java/org/vividus/StatusStoryReporterTests.java
Fixes https://github.com/vividus-framework/vividus/issues/2411
=> [vividus] Report run status depending on run completeness

.github/workflows/gradle.yml
BrowserStack reports the issue is fixed:
> I would like to share that our engineering team has deployed a fix and you should no longer be facing this issue.
=> [CI] Remove workaround for BrowserStack desktop system tests

vividus-extension-selenium/src/main/java/org/vividus/selenium/RemoteWebDriverFactory.java, vividus-extension-selenium/src/main/resources/properties/defaults/default.properties, vividus-extension-selenium/src/main/resources/spring.xml, vividus-extension-selenium/src/test/java/org/vividus/selenium/RemoteWebDriverFactoryTests.java, vividus-plugin-crossbrowsertesting/src/main/resources/properties/profile/crossbrowsertesting/web/profile.properties, vividus-plugin-web-app/src/main/resources/spring.xml
=> Add workaround for CBT integration

docs/modules/plugins/partials/azure-profile-and-subscription.adoc
There are actually 4 different, hosted clouds called Microsoft Azure. There’s the Public Azure Cloud and there are also separate Azure clouds for US Government, Germany, and China. There is no reason to use different types of clouds within one eco-system, thus there is no reason to provide the ability to use plugins for different clouds within single test execution (https://docs.microsoft.com/en-us/graph/deployments).
=> Deprecate plugin-specific properties configuring Azure environment

vividus-plugin-web-app-to-rest-api/build.gradle
https://logging.apache.org/log4j/2.x/log4j-slf4j-impl/index.html:
1. log4j-slf4j-impl should be used with SLF4J 1.7.x releases or older.
2. log4j-slf4j18-impl should be used with SLF4J 1.8.x releases or newer.
Fixes #2803
=> Fix logging libraries conflict

docs/modules/ROOT/pages/tests-configuration.adoc
=> [docs] Fix formatting of configuration properties usage warning

vividus-tests/src/main/resources/properties/environment/system/api/environment.properties
Heroku rotated DB connection URL: https://help.heroku.com/SMVK5PMS/why-have-my-heroku-postgres-credentials-changed
=> [test] Update PostgreSQL properties according to updates

vividus-plugin-rest-api/src/main/java/org/vividus/archive/steps/ArchiveSteps.java, vividus-plugin-rest-api/src/main/resources/archive-entries-result-table.ftl, vividus-plugin-rest-api/src/test/java/org/vividus/archive/steps/ArchiveStepsTests.java
` @Then("$archiveData archive contains entries with names:$parameters")`
* Add attachment with archive entries in case step failure
* Add  verification for empty archive
=> [vividus-plugin-rest-api] Add attachment with archive entries in case step failure

docs/modules/plugins/pages/plugin-web-app.adoc
Closes #2944
// 0 = allow third party 
// 1 = block third party
// 2 = block third party in incognito
```
Requested capabilities:
{
"browserName" : "chrome",
"browserVersion" : "103.0",
"goog:chromeOptions" : {
"args" : [ ],
"extensions" : [ ],
"prefs" : {
"profile" : {
"cookie_controls_mode" : 2
}
}
},
"platformName" : "LINUX"
}
```
=> [docs] Add example for cookies settings in Chrome

vividus-plugin-azure-data-factory/src/main/java/org/vividus/azure/datafactory/steps/DataFactorySteps.java, vividus-plugin-azure-data-factory/src/test/java/org/vividus/azure/datafactory/steps/DataFactoryStepsTests.java
Fixes https://github.com/Azure/azure-sdk-for-java/issues/30171
Exception stack-trace:
```
java.lang.NullPointerException: 'from' cannot be null.
at java.base/java.util.Objects.requireNonNull(Objects.java:246)
at com.azure.core.util.CoreUtils.mergeContexts(CoreUtils.java:367)
at com.azure.resourcemanager.datafactory.implementation.DataFactoryManagementClientImpl.mergeContext(DataFactoryManagementClientImpl.java:445)
at com.azure.resourcemanager.datafactory.implementation.PipelinesClientImpl.createRunWithResponseAsync(PipelinesClientImpl.java:1036)
at com.azure.resourcemanager.datafactory.implementation.PipelinesClientImpl.createRunWithResponse(PipelinesClientImpl.java:1191)
at com.azure.resourcemanager.datafactory.implementation.PipelinesImpl.createRunWithResponse(PipelinesImpl.java:100) …
```
=> [plugin-azure-data-factory] Fix NPE introduced by changes in Azure SDK

vividus-allure-adaptor/build.gradle
This PR is a cleanup of leftovers: allure dependencies of `api` scope are not needed after this refactoring: https://github.com/vividus-framework/vividus/pull/2626
=> [allure-adaptor] Reduce scope of used Allure dependencies

vividus-plugin-saucelabs/src/main/java/org/vividus/selenium/sauce/SauceConnectManager.java, vividus-plugin-saucelabs/src/main/resources/spring.xml, vividus-plugin-saucelabs/src/test/java/org/vividus/selenium/sauce/SauceConnectManagerTests.java
This change is possible because of update in `ci-sauce:1.161`: https://github.com/saucelabs/ci-sauce/pull/128
=> [plugin-saucelabs] Rely on `SauceTunnelManager` internals managing `SauceREST` client

vividus-to-zephyr-exporter/src/main/java/org/vividus/zephyr/configuration/ZephyrExporterProperties.java
=> [vividus-to-zephyr-exporter] Fix validation for zephyr.exporter.source-directory

docs/modules/commons/pages/expressions.adoc, vividus-tests/src/main/resources/story/integration/Expressions.story, vividus/src/main/java/org/vividus/expression/StringsExpressionProcessor.java, vividus/src/test/java/org/vividus/expression/StringsExpressionProcessorTests.java
=> [vividus] Introduce `escapeJSON` expression

docs/modules/integrations/pages/azure-devops-exporter.adoc, vividus-to-azure-devops-exporter/src/main/java/org/vividus/azure/devops/facade/AzureDevOpsFacade.java, vividus-to-azure-devops-exporter/src/test/java/org/vividus/azure/devops/facade/AzureDevOpsFacadeTests.java
=> [azure-devops-exporter] Allow to build area path from project name only

vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties
https://bonigarcia.dev/webdrivermanager/#known-issues: 
As of WebDriverManager 5.3.0, this issue should not happen anymore (even without a GitHub token). To avoid the 403 error, an automated job in GitHub Actions mirrors the GitHub API responses twice a day. This mirror is used internally by WebDriverManager instead of querying the GitHub API.
=> [plugin-web-app] Remove GitHub token used to download Firefox binaries

vividus-plugin-web-app/src/main/java/org/vividus/ui/web/listener/WebSourceCodePublishingOnFailureListener.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/listener/WebSourceCodePublishingOnFailureListenerTests.java
1) need to use `outerHTML` instead of `innerHTML` in order to attach the full source code of the search context (including search context root element),
2) must to use Javascript to get HTML element property (neither `outerHTML` nor `innerHTML` are attributes, and not all drivers/browsers try to search for property if the requested attribute is not found).
=> [plugin-web-app] Fix retrieval of web element source code

vividus-tests/src/main/resources/story/integration/JSON - Wait for data in HTTP response.story, vividus-tests/src/main/resources/story/integration/JSON.story
https://blog.heroku.com/next-chapter:
"Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services."
=> [tests] Make sure JSON tests do not use JsonPath Heroku app

vividus-tests/src/main/resources/properties/environment/environment.properties, vividus-tests/src/main/resources/story/integration/JSON - Wait for data in HTTP response.story, vividus-tests/src/main/resources/story/integration/ScrollStepsTests.story, vividus-tests/src/main/resources/story/integration/SslSteps.story, vividus-tests/src/main/resources/story/system/ApplitoolsVisualStepsTests.story
https://blog.heroku.com/next-chapter:
"Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services."
=> [tests] Use new endpoint of VIVIDUS test site

docs/modules/plugins/pages/plugin-azure-resource-manager.adoc, vividus-plugin-azure-resource-manager/src/main/java/org/vividus/azure/resourcemanager/ResourceManagementSteps.java, vividus-plugin-azure-resource-manager/src/test/java/org/vividus/azure/resourcemanager/ResourceManagementStepsTests.java
=> Implement step to get Azure resource with its URL

vividus-plugin-visual/src/main/java/org/vividus/visual/engine/DiffMarkupPolicyFactory.java, vividus-plugin-visual/src/test/java/org/vividus/visual/engine/DiffMarkupPolicyFactoryTests.java
**No diff**
**99.863% diff**
**CPU**
**MEM**
**Set -> List**
=> [plugin-visual] Decrease memory consumption and increase performance

.github/workflows/gradle.yml
It seems https://render.com/ stops the test website after some period of inactivity. The goal of the new step is to start (warm up) the test website to use it integration tests.
=> [CI] Add step warming up the test website

.github/workflows/gradle.yml
Mobitru devices are not stable, application installation always fails for Redmi devices. Since Redmi devices are on Android 10 and lower, but majority of other devices use Android 12, it makes sense to limit the list of devices available for system tests in sake of stability.
=> [CI] Require Android 12 for Mobitru system tests

.github/workflows/gradle.yml
If you are re-running a single job it is necessary to warm-up the test site
=> [ci] Warm-up test site always

vividus-extension-selenium/src/main/java/org/vividus/selenium/tunnel/AbstractTunnellingCapabilitiesConfigurer.java, vividus-extension-selenium/src/test/java/org/vividus/selenium/tunnel/AbstractTunnellingCapabilitiesConfigurerTests.java, vividus-plugin-saucelabs/src/main/java/org/vividus/selenium/sauce/SauceConnectManager.java, vividus-plugin-saucelabs/src/main/java/org/vividus/selenium/sauce/SauceConnectOptions.java, vividus-plugin-saucelabs/src/main/java/org/vividus/selenium/sauce/SauceLabsCapabilitiesConfigurer.java, vividus-plugin-saucelabs/src/test/java/org/vividus/selenium/sauce/SauceConnectManagerTests.java, vividus-plugin-saucelabs/src/test/java/org/vividus/selenium/sauce/SauceConnectOptionsTests.java, vividus-plugin-saucelabs/src/test/java/org/vividus/selenium/sauce/SauceLabsCapabilitiesConfigurerTests.java
https://docs.saucelabs.com/dev/test-configuration-options/#tunnelidentifier: `tunnelIdentifier` is being deprecated in favor of `tunnelName`.
=> [plugin-saucelabs] Use `tunnelName` instead of deprecated `tunnelIdentifier`

docs/modules/commons/partials/data-generating.adoc, vividus/build.gradle
The root cause of the fixed issue: https://github.com/datafaker-net/datafaker/issues/574. It's needed to use JitPack build, because new `datafaker` release is not plublished and timeline is unknown (see more: https://github.com/datafaker-net/datafaker/issues/574#issuecomment-1365076807). `datafaker` SNAPSHOT builds may introduce unexpected breaking changes e.g. https://github.com/datafaker-net/datafaker/commit/e44736d5e5cd65929175fbe6a73071d544903f63, that's why they are not acceptable.
=> [vividus] Fix `generate` expression to be thread-safe again

vividus-plugin-json/src/main/java/org/vividus/json/steps/JsonSteps.java, vividus-plugin-json/src/test/java/org/vividus/json/steps/JsonStepsTests.java
Fix broken JSON comparison step with extra elements in expected JSON and using `IGNORING_EXTRA_ARRAY_ITEMS` option
=> [plugin-json] Fix broken JSON assert with `IGNORING_EXTRA_ARRAY_ITEMS` option

docs/modules/ROOT/pages/tests-configuration.adoc, vividus-engine/src/main/java/org/vividus/batch/BatchConfiguration.java, vividus-engine/src/main/java/org/vividus/batch/BatchStorage.java, vividus-engine/src/main/resources/org/vividus/engine/spring.xml, vividus-engine/src/test/java/org/vividus/BatchedEmbedderTests.java, vividus-engine/src/test/java/org/vividus/batch/BatchStorageTests.java, vividus/src/main/resources/properties/defaults/default.properties, vividus/src/main/resources/properties/deprecated/deprecated.properties
=> [engine] Align story execution timeout properties naming

vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/edge/profile.properties, vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/profile.properties
SauceLabs has started using MacOS as a default platform when `platformName` capability is equal to single whitespace, while empty `platformName` capability defaults to Windows by Selenium client.
=> [plugin-web-app] Fix execution of desktop web tests on SauceLabs

vividus-engine/src/main/java/org/vividus/steps/ExpressionAdaptor.java, vividus-engine/src/test/java/org/vividus/steps/ExpressionAdapterTests.java
The previous RELUCTANT_EXPRESSION_PATTERN didn't correctly process expressions the number of characters in which was not a multiple of 3
=> [engine] Fix parsing of nested expressions without parameters

vividus-extension-selenium/src/main/java/org/vividus/ui/util/XpathLocatorUtils.java, vividus-extension-selenium/src/test/java/org/vividus/ui/util/XpathLocatorUtilsTests.java
Closes [#3535](https://github.com/vividus-framework/vividus/issues/3535)
=> [vividus-extension-selenium] Update space normalization for xpaths with contains function

vividus-engine/src/main/java/org/vividus/BatchedPerformableTree.java, vividus-engine/src/main/java/org/vividus/IdenticalStoryNamesResolver.java, vividus-engine/src/main/java/org/vividus/ResolveToUniqueSimpleName.java, vividus-engine/src/main/resources/org/vividus/engine/spring.xml, vividus-engine/src/test/java/org/vividus/BatchedPerformableTreeTests.java, vividus-engine/src/test/java/org/vividus/IdenticalStoryNamesResolverTests.java, vividus-engine/src/test/java/org/vividus/ResolveToUniqueSimpleNameTests.java, vividus-tests/src/main/resources/properties/suite/integration/suite.properties, vividus-tests/src/main/resources/story/integration/storiesIdenticalNames/Simple.story, vividus-tests/src/main/resources/story/integration/storiesIdenticalNames/anotherDirectory/Simple.story
=> [engine] Resolve identical Jbehave story names

vividus-plugin-web-app/build.gradle, vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties
Root cause is the changes in Chrome behavior: https://bugs.chromium.org/p/chromium/issues/detail?id=1422444
Discussion: https://groups.google.com/g/chromedriver-users/c/xL5-13_qGaA?pli=1
Selenium issue: https://github.com/SeleniumHQ/selenium/issues/11750
Solution details: following Selenium team recommendation and switching to JDK 11 Http client for Selenium
=> [plugin-web-app] Add workaround for Chrome 111

vividus-extension-selenium/src/main/java/org/vividus/selenium/manager/GenericWebDriverManager.java, vividus-extension-selenium/src/main/java/org/vividus/selenium/manager/IGenericWebDriverManager.java, vividus-extension-selenium/src/test/java/org/vividus/selenium/manager/GenericWebDriverManagerTests.java, vividus-plugin-excel/src/test/java/org/vividus/excel/ExcelSheetWriterTests.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/FieldActions.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/FieldActionsTests.java
=> [plugin-web-app] Fix field clearing using keyboard on MacOS

docs/modules/plugins/pages/plugin-rest-api.adoc, vividus-plugin-rest-api/src/main/java/org/vividus/http/transformer/JsonRestApiTableTransformer.java, vividus-plugin-rest-api/src/test/java/org/vividus/http/transformer/JsonRestApiTableTransformerTests.java
=> [plugin-rest-api] Introduce variableName parameter for FROM_JSON transformer

docs/modules/commons/pages/table-transformers.adoc, vividus-tests/src/main/resources/data/for-inner-join-transformer.table, vividus-tests/src/main/resources/story/integration/TableTransformers.story, vividus/src/main/java/org/vividus/transformer/InnerJoinTableTransformer.java, vividus/src/main/resources/org/vividus/spring-vividus.xml, vividus/src/test/java/org/vividus/transformer/InnerJoinTableTransformerTests.java
=> [vividus] Add INNER_JOIN table transformer

vividus/build.gradle, vividus/src/main/resources/log4j2.xml
Loading of Log4J2 plugins using package scanning is [deprecated]( https://logging.apache.org/log4j/2.x/release-notes/2.20.0.html#deprecated).
The only available option is [serialized plugin listing files](https://logging.apache.org/log4j/2.x/manual/plugins.html) on the classpath.
More details on deprecation: https://issues.apache.org/jira/browse/LOG4J2-3644.
=> [vividus] Load Allure Log4J2 plugin from plugin listing file on classpath

vividus-extension-selenium/src/main/java/org/vividus/selenium/WebDriverProvider.java, vividus-extension-selenium/src/main/java/org/vividus/selenium/cloud/AbstractCloudTestLinkPublisher.java, vividus-extension-selenium/src/main/java/org/vividus/selenium/cloud/AbstractCloudTestStatusManager.java, vividus-extension-selenium/src/main/java/org/vividus/selenium/event/BeforeWebDriverQuitEvent.java, vividus-extension-selenium/src/test/java/org/vividus/selenium/WebDriverProviderTests.java, vividus-extension-selenium/src/test/java/org/vividus/selenium/cloud/AbstractCloudTestLinkPublisherTests.java, vividus-extension-selenium/src/test/java/org/vividus/selenium/cloud/AbstractCloudTestStatusManagerTests.java, vividus-plugin-browserstack/src/main/java/org/vividus/browserstack/BrowserStackTestStatusManager.java, vividus-plugin-browserstack/src/test/java/org/vividus/browserstack/BrowserStackTestStatusManagerTests.java, vividus-plugin-crossbrowsertesting/src/main/java/org/vividus/crossbrowsertesting/CbtTestStatusManager.java, vividus-plugin-crossbrowsertesting/src/test/java/org/vividus/crossbrowsertesting/CbtTestStatusManagerTests.java, vividus-plugin-lambdatest/src/main/java/org/vividus/lambdatest/LambdaTestTestStatusManager.java, vividus-plugin-lambdatest/src/test/java/org/vividus/lambdatest/LambdaTestTestStatusManagerTests.java, vividus-plugin-saucelabs/src/main/java/org/vividus/saucelabs/SauceLabsTestStatusManager.java, vividus-plugin-saucelabs/src/test/java/org/vividus/saucelabs/SauceLabsTestStatusManagerTests.java
The capabilities attempted to get by SauceLabs plugin after WebDriver quit are unavailable, such attempts leads to start of invalid sessions.
=> [extension-selenium] Add ability to check WebDriver capabilities at cloud session link publishing

vividus-plugin-saucelabs/build.gradle, vividus-plugin-saucelabs/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
As of Mockito 5.0.0 the default mockmaker was switched to `mockito-inline`: https://github.com/mockito/mockito/releases/tag/v5.0.0
=> [plugin-saucelabs] Remove usage of `mockito-inline` dependency

vividus-plugin-web-app/build.gradle, vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties
Reason: mobile web tests (e.g. iPad) fail on SauceLabs.
Assumption: regression issue was introduced in Selenium 4.9.0 (possible root cause: https://github.com/SeleniumHQ/selenium/pull/11816)
=> [plugin-web-app] Switch back to default HTTP client for Selenium

vividus-util/src/main/java/org/vividus/util/json/JsonPathUtils.java
See: https://github.com/FasterXML/jackson-databind/issues/3651
=> [util] Switch to use non-deprecated Jackson API for exact `BigDecimal`-s

vividus-docker-bundler/build.gradle
Applitools issue: https://github.com/applitools/eyes.sdk.java3/issues/591
=> [docker-bundler] Skip packing of Applitools plugin due to its huge size

docs/modules/plugins/pages/plugin-sauce-labs.adoc
It seems SauceLabs silently decommissioned APAC data center: https://docs.saucelabs.com/basics/data-center-endpoints/
=> [docs] Remove SauceLabs Data center `APAC_SOUTHEAST`

vividus-extension-selenium/src/main/java/org/vividus/selenium/tunnel/TunnelOptions.java, vividus-plugin-saucelabs/build.gradle, vividus-plugin-saucelabs/src/main/java/org/vividus/selenium/sauce/SauceConnectOptions.java, vividus-plugin-saucelabs/src/main/java/org/vividus/selenium/sauce/SauceLabsCapabilitiesConfigurer.java, vividus-plugin-saucelabs/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-saucelabs/src/test/java/org/vividus/selenium/sauce/SauceConnectOptionsTests.java, vividus-plugin-saucelabs/src/test/java/org/vividus/selenium/sauce/SauceLabsCapabilitiesConfigurerTests.java, vividus-tests/src/main/resources/properties/environment/system/saucelabs/environment.properties
SauceConnect 4.9.1 is released with fixes of SSL bugs (https://changelog.saucelabs.com/en/sauce-connect-proxy-release-version-491):
Bug Fixes
- Fixed a bug to allow https access when SSL bumping is disabled
- Fixed a bug to allow self-signed certificates when SSL bumping is enabled
=> [plugin-saucelabs] Enable back support of the latest SauceConnect 

.github/workflows/gradle.yml, docs/modules/plugins/pages/plugin-accessibility.adoc, docs/modules/plugins/pages/plugin-rest-api.adoc, docs/modules/plugins/pages/plugin-web-app.adoc, docs/modules/plugins/partials/generic-ui-steps.adoc, docs/modules/plugins/partials/plugin-web-app-steps.adoc, vividus-tests/src/main/resources/properties/environment/environment.properties
VIVIDUS test site service was moved from Team to Invidiual account, thus new subdomain was generated. It's not possible to define own subdomain: https://community.render.com/t/can-i-change-my-existing-subdomain-onrender-com-to-a-new-one/9999/2. Full notification from Render:
> Hi there,
> 
> We're reaching out to remind you of upcoming changes to your Render bill. Single-user teams created before January 2023 received a 6-month grace period during which they did not have to pay $19 per user per month.
> 
> Starting July 1, 2023, your team VIVIDUS will be charged $19 per user per month starting July 2023. Active Render teams will be charged $19 per user per month in addition to compute costs.
> 
> If you do not need the additional features in the Team plan, you can recreate your services …
=> Migrate to new instance of VIVIDUS test site

vividus-docker-bundler/build.gradle
https://support.saucelabs.com/hc/en-us/articles/10075350509079-Using-Alpine-OS-with-Sauce-Connect:
Sauce Connect requires glibc, a library of tools available in most GNU/Linux systems. Alpine is not one of those and requires extra configuration to ensure your Sauce Connect tunnel can be used.
=> [docker-bundler] Add `glibc` library to Docker image

docs/modules/plugins/pages/plugin-visual.adoc, vividus-extension-selenium/src/main/java/org/vividus/ui/screenshot/ScreenshotConfiguration.java, vividus-extension-selenium/src/test/java/org/vividus/converter/ui/AbstractExamplesTableToScreenshotConfigurationConverterTests.java, vividus-extension-selenium/src/test/java/org/vividus/ui/screenshot/AbstractScreenshotParametersFactoryTests.java, vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/converter/ExamplesTableToScreenshotConfigurationConverter.java, vividus-plugin-mobile-app/src/main/resources/properties/deprecated/deprecated.properties, vividus-plugin-mobile-app/src/test/java/org/vividus/mobileapp/converter/ExamplesTableToScreenshotConfigurationConverterTests.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/screenshot/WebScreenshotConfiguration.java
- Deprecated screenshot configuration parameter `nativeFooterToCut` is remove, use `cutBottom` parameter for mobile applications.
- Deprecated property `mobile.screenshot.strategy.<YOUR_STRATEGY_NAME>.native-footer-to-cut` is removed, use `mobile.screenshot.strategy.<YOUR_STRATEGY_NAME>.cut-bottom`
=> [plugin-visual] Remove deprecated non-unified definitions of cut strategies for mobile apps

vividus/src/main/resources/properties/deprecated/deprecated.properties
Previously property `bdd.configuration.all-composite-paths` was internal (it's not expected to be used by end-users) and it's used to configure composite files paths: both internal and external. But it's turned out users misused the property and overrode default VIVIDUS composite steps, the decision was taken to drop the property and it was implemented in #3436. The property was deprecated in favour of `engine.composite-paths` to do not break backward compatibility.
=> [vividus] Remove deprecated internal property for all composite files

vividus-plugin-accessibility/src/main/java/org/vividus/accessibility/deserializer/TargetDeserializer.java, vividus-plugin-accessibility/src/main/java/org/vividus/accessibility/model/axe/Node.java, vividus-plugin-accessibility/src/main/java/org/vividus/accessibility/model/axe/Target.java, vividus-plugin-accessibility/src/main/resources/org/vividus/accessibility/axe-accessibility-report.ftl, vividus-plugin-accessibility/src/test/java/org/vividus/accessibility/deserializer/TargetDeserializerTests.java, vividus-plugin-accessibility/src/test/java/org/vividus/accessibility/executor/AccessibilityTestExecutorTests.java, vividus-plugin-accessibility/src/test/resources/org/vividus/accessibility/executor/axe-core.json
Accessibility check is broken on listerine.com and tyenol.com sites because target field deserialization doesn't cover all output forms of target field described here: https://www.deque.com/axe/core-documentation/api-documentation/
```
target - Array of either strings or Arrays of strings. If the item in the array is a string, then it is a CSS selector. 
If there are multiple items in the array each item corresponds to one level of iframe or frame. If there is one iframe or frame, there should be two entries in target. 
If there are three iframe levels, there should be four entries in target. 
If the item in the Array is an Array of strings, then it points to an element in a shadow DOM and each item (except the n-1th) in this array is a selector to a DOM element with a shadow DOM. 
The …
```
=> [plugin-accessibility] Align target field deserialization with axe core rules

.github/workflows/gradle.yml
There are OS-specific tests, in order to get the full picture of code coverage it's needed to upload results generated at all platforms. Codecov will do reports merging automatically: https://docs.codecov.com/docs/merging-reports
=> [CI] Upload code coverage results from all platforms

docs/modules/ROOT/pages/secrets-management.adoc, docs/modules/commons/pages/expressions.adoc, vividus-tests/src/main/resources/story/integration/Encryption.story, vividus/src/main/java/org/vividus/configuration/EncryptedPropertiesProcessor.java, vividus/src/main/java/org/vividus/encryption/DecryptionFailedException.java, vividus/src/main/java/org/vividus/encryption/Decryptor.java, vividus/src/main/java/org/vividus/encryption/NoDecryptionPasswordException.java, vividus/src/main/java/org/vividus/expression/DecryptExpressionProcessor.java, vividus/src/main/resources/org/vividus/spring-configuration.xml, vividus/src/main/resources/org/vividus/spring-vividus.xml, vividus/src/test/java/org/vividus/configuration/EncryptedPropertiesProcessorTests.java, vividus/src/test/java/org/vividus/encryption/DecryptorTests.java, vividus/src/test/java/org/vividus/expression/DecryptExpressionProcessorTests.java
=> [vividus] Introduce `decrypt` expression

docs/modules/plugins/pages/plugin-rest-api.adoc, vividus-plugin-rest-api/src/main/java/org/vividus/http/ExtendedHttpLoggingInterceptor.java, vividus-plugin-rest-api/src/main/java/org/vividus/http/MimeTypeUtils.java, vividus-plugin-rest-api/src/main/java/org/vividus/http/PublishingAttachmentInterceptor.java, vividus-plugin-rest-api/src/main/resources/log4j2-vividus-plugin-rest-api.xml, vividus-plugin-rest-api/src/main/resources/properties/defaults/default.properties, vividus-plugin-rest-api/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-rest-api/src/test/java/org/vividus/http/ExtendedHttpLoggingInterceptorTests.java, vividus-plugin-rest-api/src/test/java/org/vividus/http/MimeTypeUtilsTests.java, vividus-tests/src/main/resources/properties/environment/integration/environment.properties
=> [plugin-rest-api] Add extended logging for HTTP requests and responses

.github/workflows/gradle.yml
The `platformVersion` is not required; however, Mobitru is currently facing some issues with device allocation. To address this issue, the iOS version is being forced to `16` in the CI.
=> [CI] Fix execution of web-tests on Mobitru

docs/modules/plugins/pages/plugin-mobitru.adoc, vividus-plugin-mobitru/src/main/java/org/vividus/mobitru/client/MobitruClient.java, vividus-plugin-mobitru/src/main/java/org/vividus/mobitru/client/MobitruFacade.java, vividus-plugin-mobitru/src/main/java/org/vividus/mobitru/client/MobitruFacadeImpl.java, vividus-plugin-mobitru/src/main/java/org/vividus/mobitru/selenium/MobitruCapabilitiesAdjuster.java, vividus-plugin-mobitru/src/main/resources/properties/profile/mobitru/mobile_app/profile.properties, vividus-plugin-mobitru/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-mobitru/src/test/java/org/vividus/mobitru/client/MobitruClientTests.java, vividus-plugin-mobitru/src/test/java/org/vividus/mobitru/client/MobitruFacadeImplTests.java, vividus-plugin-mobitru/src/test/java/org/vividus/mobitru/selenium/MobitruCapabilitiesAdjusterTests.java
Mobitru API for app installation has separate parameter, which is noResign, and it allows to avoid the ipa resign with Mobitru profile.
For now, this parameter is not specifying in the MobitruClient class, which means that resign is always enabled.
It causes critical issues for some people, who want to use the vividus and mobitru.
=> [plugin-mobitru] Add ability to disable iOS app resigning with Mobitru profile

vividus-engine/src/main/java/org/vividus/replacement/DeprecatedStepNotificationFactory.java, vividus-engine/src/test/java/org/vividus/replacement/DeprecatedStepNotificationFactoryTests.java
=> [vividus-engine] Fix logging of deprecated steps without parameters inside composite steps

vividus-plugin-websocket/build.gradle
Also fixes error:
```
(java.lang.NoSuchMethodError: 'jakarta.websocket.ClientEndpointConfig$Builder jakarta.websocket.ClientEndpointConfig$Builder.sslContext(javax.net.ssl.SSLContext)') 2024-01-12 16:06:56,606 [batch-1-thread-1] ERROR org.vividus.log.LoggingStoryReporter - Step is failed with exception
org.jbehave.core.failures.UUIDExceptionWrapper: When I connect to `echo` websocket
at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:914) ~[jbehave-core-6.0.0-alpha.3.jar:?]
at org.jbehave.core.steps.StepCreator$ReportingAbstractStep.perform(StepCreator.java:639) ~[jbehave-core-6.0.0-alpha.3.jar:?]
at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:379) ~[jbehave-core-6.0.0-alpha.3.jar:?]
at …
```
=> [plugin-websocket] Bump Jetty websocket client from 11 to 12

docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc, vividus-plugin-html/src/main/java/org/vividus/html/JsoupUtils.java, vividus-plugin-html/src/main/java/org/vividus/steps/html/HtmlSteps.java, vividus-plugin-html/src/test/java/org/vividus/html/HtmlLocatorTypeTests.java, vividus-plugin-html/src/test/java/org/vividus/html/JsoupUtilsTests.java, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/steps/integration/ResourceCheckStepsTests.java, vividus-tests/src/main/resources/story/integration/ResourceCheckSteps.story
=> [plugin-web-app-to-rest-api] Filter invalid jump links from context resource validation

docs/modules/plugins/partials/plugin-web-app-steps.adoc, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/ScrollSteps.java, vividus-plugin-web-app/src/main/resources/org/vividus/ui/web/action/scroll-element-into-viewport-center.js, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/ScrollStepsTests.java
=> Consider sticky header size when scrolling element into view

docs/modules/ROOT/pages/tests-configuration.adoc, vividus-engine/src/main/resources/org/vividus/engine/spring.xml, vividus/src/main/resources/properties/defaults/default.properties
=> Add ability to define format for indices of story-level Examples

docs/modules/plugins/pages/plugin-web-app.adoc, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/WaitSteps.java, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/WaitStepsTests.java, vividus-tests/src/main/resources/known-issues.json, vividus-tests/src/main/resources/story/integration/WaitStepsTests.story
=> [plugin-web-app] Add step to wait for element appearance with desired timeout

docs/modules/commons/pages/table-transformers.adoc, vividus/src/main/java/org/vividus/transformer/FilteringTableTransformer.java, vividus/src/test/java/org/vividus/transformer/FilteringTableTransformerTests.java
If the number of rows in the original table is less than the value specified in 'byRandomRows' parameter, then all the original table rows are kept.
=> [vividus] Do not fail when total table rows number is less than random rows transformer parameter

vividus-allure-adaptor/src/main/java/org/vividus/report/allure/AllureReportGenerator.java, vividus-allure-adaptor/src/test/java/org/vividus/report/allure/adapter/AllureReportPatchingConsistencyTests.java
=> [allure-adaptor] Include know-issues in pass rate

.github/workflows/gradle.yml
There is a connectivity issue from GitHub MacOS runner, the video does not start in 20 seconds:
=> [CI] Disable video player integration tests in MacOS

.github/workflows/gradle.yml
```
cmp: invalid option -- c
usage: cmp [-l | -s | -x] [-bhz] [-i num1[:num2] | --ignore-initial=num1[:num2]] [-n num | --bytes=num] file1 file2 [skip1 [skip2]]
Error: Process completed with exit code 2.
```
=> [CI] Remove invalid option of `cmp` utility

vividus-plugin-web-app/src/main/resources/org/vividus/ui/web/action/scroll-element-into-viewport-center.js, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/WebJavascriptActionsTests.java, vividus-tests/src/main/resources/properties/environment/integration/environment.properties
This partially reverts 213f1c65b4. The root cause of the issue was a wrong size of sticky header: it was more than 50% of window height.
=> [plugin-web-app] Revert invalid fix of scroll script

docs/modules/plugins/pages/plugin-lighthouse.adoc, vividus-plugin-lighthouse/src/main/java/org/vividus/lighthouse/LighthouseSteps.java, vividus-plugin-lighthouse/src/main/resources/properties/defaults/default.properties, vividus-plugin-lighthouse/src/test/java/org/vividus/lighthouse/LighthouseStepsTests.java, vividus-tests/src/main/resources/story/integration/LighthouseSteps.story
https://github.com/GoogleChrome/lighthouse/releases/tag/v12.0.0: 
"As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse [has removed the PWA category](https://github.com/GoogleChrome/lighthouse/pull/15455). For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/)."
=> [plugin-lighthouse] Remove PWA category

vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/crawler/transformer/AbstractFetchingUrlsTableTransformer.java, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/crawler/transformer/HeadlessCrawlerTableTransformer.java, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/crawler/transformer/SiteMapTableTransformer.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/crawler/transformer/FetchingUrlsTableTransformerTests.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/crawler/transformer/SiteMapTableTransformerTests.java
According to standard all Sitemap URLs must be URL-escaped and encoded (https://www.sitemaps.org/protocol.html#escaping), but there could be cases when production contains invalid URLs and it's needed to crawl websites, so FROM_SITEMAP transformer must be able to handle such invalid URLs.
=> [plugin-web-app-to-rest-api] Quietly handle non-encoded Sitemap URLs by `FROM_SITEMAP` transformer

docs/modules/plugins/pages/plugin-mobitru.adoc, vividus-plugin-mobitru/src/main/java/org/vividus/mobitru/client/MobitruClient.java, vividus-plugin-mobitru/src/main/java/org/vividus/mobitru/client/MobitruFacade.java, vividus-plugin-mobitru/src/main/java/org/vividus/mobitru/client/MobitruFacadeImpl.java, vividus-plugin-mobitru/src/main/java/org/vividus/mobitru/selenium/MobitruCapabilitiesAdjuster.java, vividus-plugin-mobitru/src/main/resources/properties/profile/mobitru/mobile_app/profile.properties, vividus-plugin-mobitru/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-mobitru/src/test/java/org/vividus/mobitru/client/MobitruClientTests.java, vividus-plugin-mobitru/src/test/java/org/vividus/mobitru/client/MobitruFacadeImplTests.java, vividus-plugin-mobitru/src/test/java/org/vividus/mobitru/selenium/MobitruCapabilitiesAdjusterTests.java
Add support of doInjection parameter for installing native applications in the Mobitru.
This query parameter enables the injection of special code into an application to allow emulation of "touch id" action and QR code scan.
=> add support of mobitru doInjection parameter

.github/workflows/code_quality.yml
Starting from version 2023.2 release versions of Qodana Linters require connection to Qodana Cloud. To continue using Qodana, it's required to have an access token and provide the token as the QODANA_TOKEN environment variable. But GitHub prevents PRs from forks from accessing secrets by default. Thus it's needed to disable Qodana workflow for PRs from forks.
=> [CI] Do not run Qodana checks on PRs from forks

docs/modules/plugins/pages/plugin-rest-api.adoc, docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc, vividus-extension-selenium/src/main/resources/templates/source-code.ftl, vividus-plugin-rest-api/src/main/java/org/vividus/http/validation/ResourceValidator.java, vividus-plugin-rest-api/src/main/java/org/vividus/http/validation/model/AbstractResourceValidation.java, vividus-plugin-rest-api/src/main/resources/http-resources-validation-results.ftl, vividus-plugin-rest-api/src/main/resources/properties/defaults/default.properties, vividus-plugin-rest-api/src/main/resources/resources-response-body-fragment.ftl, vividus-plugin-rest-api/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-rest-api/src/test/java/org/vividus/http/validation/ResourceValidatorTests.java, vividus-plugin-web-app-to-rest-api/src/main/resources/resources-validation-result.ftl, vividus-plugin-web-app-to-rest-api/src/main/resources/vividus-plugin/spring.xml, vividus-reporter/src/main/resources/templates/html-formatter-fragment.ftl
Closes #4918
Report
[allure.zip](https://github.com/user-attachments/files/15593391/allure.zip)
=> [plugin-web-app-to-rest-api] Publish response body for failed resource checks

docs/modules/plugins/pages/plugin-web-app-playwright.adoc, docs/modules/plugins/partials/web-cookie-steps.adoc, vividus-extension-web-app/build.gradle, vividus-extension-web-app/src/main/java/org/vividus/ui/web/action/CookieManager.java, vividus-extension-web-app/src/main/java/org/vividus/ui/web/action/InetAddressUtils.java, vividus-extension-web-app/src/test/java/org/vividus/ui/web/action/InetAddressUtilsTests.java, vividus-plugin-web-app-playwright/build.gradle, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/action/PlaywrightCookieManager.java, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/CookieSteps.java, vividus-plugin-web-app-playwright/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/action/PlaywrightCookieManagerTests.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/steps/CookieStepsTests.java, vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/HttpRequestSteps.java, vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/steps/integration/HttpRequestStepsTests.java, vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/CookieSteps.java, vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/WebDriverCookieManager.java, vividus-plugin-web-app/src/main/resources/vividus-plugin/spring.xml, vividus-plugin-web-app/src/test/java/org/vividus/steps/ui/web/CookieStepsTests.java, vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/WebDriverCookieManagerTests.java
* implement code logic for Playwright's cookie
* write corresponding tests
* write documentation
=> [plugin-web-app-playwright] Implement Cookie Steps code logic for Playwright

docs/modules/plugins/pages/plugin-web-app-playwright.adoc, vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/PageSteps.java, vividus-plugin-web-app-playwright/src/test/java/org/vividus/ui/web/playwright/steps/PageStepsTests.java
Report
[allure.zip](https://github.com/user-attachments/files/16049923/allure.zip)
=> [plugin-web-app-playwright] Add tab steps

vividus-plugin-json/src/main/java/org/vividus/json/steps/JsonSteps.java
JBehave step candidate 
```
When I $actionType baseline with name `$name` ignoring:$checkSettings
``` 
matches on JSON nested steps (example)
```
When I find >= `0` JSON elements from `<json>` by `<path>` and for each element do
{headerSeparator=!, valueSeparator=!}
!step                                                                                                 !
!When I change context to element located by `<locator>`           !
!When I ${visual-action} baseline with name `<name>` ignoring:  !
!|ACCEPTABLE_DIFF_PERCENTAGE                                                  |!
!|0.5                                                                                                 |!
```
=> [plugin-json] Prioritize JSON nested steps to avoid incorrect steps recognition

vividus-plugin-web-app-to-rest-api/build.gradle
It seems Crawler4J is not archived anymore: https://github.com/HHN/crawler4j/commit/9b4e2cfbda206b6f976243655aa19610c90aeaf1
=> [plugin-web-app-to-rest-api] Migrate back to original Crawler4J

vividus-plugin-email/build.gradle
https://jakartaee.github.io/mail-api/
August 18, 2021 - Jakarta Mail implementation moves to Eclipse Angus To break tight integration between Jakarta Mail Specification API and the implementation, sources of the implementation were moved to the new project - Eclipse Angus - and further development continues there. Eclipse Angus is the direct successor of JavaMail/JakartaMail.
=> [plugin-email] Migrate to Jakarat Mail 2.1

.github/workflows/gradle.yml
Some builds fail with the following errors:
- https://github.com/vividus-framework/vividus/actions/runs/11611021881/job/32336096362
- https://github.com/vividus-framework/vividus/actions/runs/11611021881/job/32337973732
The details can be found here: https://github.com/SeleniumHQ/selenium/issues/11798
The root cause is: https://bugs.openjdk.org/browse/JDK-8304701, which is fixed in JDK 22.
=> [CI] Use JDK 23 as runtime

docs/modules/plugins/pages/plugin-mobile-app.adoc
`automationName` capability is a technical one and it's already configured in the corresponding VIVIDUS profiles. Also there is only one engine per platform, no alternative engines are available. So the information is removed to simplify configuration from user side.
=> [docs] Remove information about `automationName` capability

vividus-plugin-web-app-playwright/src/main/resources/org/vividus/ui/web/playwright/action/check-element-in-viewport.js
=> [plugin-web-app-playwright] Fix invalid element viewport visibility logic

vividus-http-client/src/main/java/org/vividus/http/client/HttpResponse.java, vividus-http-client/src/test/java/org/vividus/http/client/HttpResponseTests.java
Spec:
- HTTP1.X - headers are case insensitive
- HTTP2.X - headers are in lower case
=> [http-client] Ignore case-sensitivity while matching header names

.github/workflows/gradle.yml
Secrets are not accessible in PRs created from forks.
See more why secrets can't be used in conditions: https://github.com/actions/runner/issues/520#issuecomment-1690859769
=> [CI] Do not run system SauceLabs tests on PRs from forks

.github/workflows/gradle.yml
Empty `selenium.grid.capabilities.platformName` property results in `"platformName" : "ANY"` capability. SauceLabs has changed the logic, previously ANY platform resulted in Windows, but now it can be MacOS, which in its turn may result in screen resolution conflicts:
```
(org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 404. Message: Misconfigured -- Resolution you specified is not available for this OS/browser/version/device combo: OS: 'Mac 12', Browser: 'googlechrome', Version: '134.0.6998.45', Device: 'unspecified', Screen Resolution: '1920x1080'; available resolutions: '1024x768', '1152x864', '1280x960', '1376x1032', '1440x900', '1600x1200', '1920x1440', '2048x1536'
```
=> [CI] Set platform name for SauceLabs desktop tests

vividus-plugin-visual/src/main/java/org/vividus/visual/engine/VisualTestingEngine.java, vividus-plugin-visual/src/test/java/org/vividus/visual/engine/VisualTestingEngineTests.java
Documentation:
**ui.visual.override-baselines** - Used for overriding existing ones or creating not existing baselines during compare action
Fix for "creating not existing baselines during compare action"
=> [plugin-visual] Save baseline during comparison when there is no original baseline

vividus-plugin-saucelabs/src/main/resources/properties/profile/saucelabs/profile.properties, vividus-plugin-saucelabs/src/main/resources/properties/profile/saucelabs/web/profile.properties
https://docs.saucelabs.com/dev/test-configuration-options/#idletimeout - Desktop only:
=> [plugin-saucelabs] Fix idle timeout configuration

vividus-tests/src/main/resources/properties/profile/browserstack/mobile_app/android/profile.properties
Google Pixel 4 is deprecated:
> org.openqa.selenium.WebDriverException: [BROWSERSTACK_DEPRECATED_DEVICE_ERROR] The device google pixel 4-10.0 has been deprecated from 18 July 2025 onwards. Going forward any tests on device google pixel 4-10.0 will not be supported on BrowserStack. We strongly recommend you update your test scripts. For the current list of supported devices on BrowserStack, please check here - https://www.browserstack.com/list-of-browsers-and-platforms/app_automate
=> [tests] Update device for BrowserStack Android native tests
